feat: added BOX doctype, Shipping Information as child table in Item
DigiThinkIT/erpnext pull request #1006
Opened 2021-02-03 12:00 UTC by MyuddinKhatri

Ref: [Asana](https://app.asana.com/0/1192407896547052/1199520543546492)

2021-02-15 10:44 UTC, hrwX requested changes

2021-02-15 10:44 UTC, hrwX commented on erpnext/stock/doctype/item/item.js
> +		var row = locals[cdt][cdn];
```suggestion
		let row = locals[cdt][cdn];
```

2021-02-15 10:44 UTC, hrwX commented on erpnext/stock/doctype/item/item.js
> +cur_frm.fields_dict['shipping_information'].grid.get_field('uom').get_query = function(doc,cdt,cdn) {
```suggestion
frm.set_query('shipping_information', 'uom', function(doc,cdt,cdn) {
```

Move this to refesh trigger

2021-02-15 10:44 UTC, hrwX commented on erpnext/stock/doctype/item/item.js
> +	var row = locals[cdt][cdn];
```suggestion
	let row = locals[cdt][cdn];
```

2021-02-15 10:44 UTC, hrwX commented on erpnext/stock/doctype/item/item.js
> +	let box = doc.shipping_information.map(info=> info.box);
```suggestion
	let uom = doc.shipping_information.map(info => info.uom);
	let box = doc.shipping_information.map(info => info.box);
```

2021-02-15 10:44 UTC, hrwX commented on erpnext/stock/doctype/item/item.js
> +	if(box.includes(row.box)) {
```suggestion
	if (box.includes(row.box)) {
```

2021-02-15 10:44 UTC, hrwX commented on erpnext/stock/doctype/item/item.js
> +			filters:{
```suggestion
			filters : {
```

2021-02-15 10:44 UTC, hrwX commented on erpnext/stock/doctype/packing_slip/packing_slip.js
> +		var row = locals[cdt][cdn];
```suggestion
		let row = locals[cdt][cdn];
```

2021-02-15 10:44 UTC, hrwX commented on erpnext/stock/doctype/packing_slip/packing_slip.js
> +					if (r.message) {
```suggestion
					if (r && r.message) {
```

2021-02-15 10:44 UTC, hrwX commented on erpnext/stock/doctype/packing_slip/packing_slip.js
> +						frappe.model.set_value(cdt, cdn, "no_of_boxes_required", r.message)
```suggestion
						frappe.model.set_value(cdt, cdn, "no_of_boxes_required", r.message);
```

2021-02-15 10:44 UTC, hrwX commented on erpnext/stock/doctype/packing_slip/packing_slip.js
> +			})
```suggestion
			});
```

2021-02-15 10:44 UTC, hrwX commented on erpnext/stock/doctype/packing_slip/packing_slip.js
> +}
Change this to one suggested above

2021-02-15 10:44 UTC, hrwX commented on erpnext/stock/doctype/packing_slip/packing_slip.py
> +	""",filters.get("item_code"))
Use ORM

2021-02-16 07:16 UTC, rvpasari commented
Waiting on a sign off on the functionality from Kenneth before I approve the PR.

2021-02-16 15:00 UTC, rvpasari submitted a review, later dismissed

2021-02-17 10:29 UTC, rvpasari approved these changes

2021-02-17 10:32 UTC, sahil28297 approved these changes

2021-02-17 10:32 UTC, merged