fix: made Default Direct Expenses and Default Indirect Expenses field mandatory in Company master
DigiThinkIT/erpnext pull request #1066
Opened 2021-03-02 12:35 UTC by MyuddinKhatri

Ref: [Asana](https://app.asana.com/0/1192407896547052/1199955032007483)

![screenshot-bloomstack_demo_8000-2021 03 02-18_05_42](https://user-images.githubusercontent.com/53251406/109649483-fc5ec900-7b81-11eb-952b-9622e6a63220.png)

2021-03-03 04:33 UTC, vishdha approved these changes, later dismissed

2021-03-03 05:32 UTC, sahil28297 commented
@MyuddinKhatri @vishdha what about the existing sites where these accounts are not set, we are not setting a "default" value for these fields before making it mandatory, things might break.

2021-03-04 09:47 UTC, hrwX requested changes

2021-03-04 09:47 UTC, hrwX commented on erpnext/setup/doctype/company/company.js
> +		frm.toggle_reqd("default_indirect_expenses", 1);
Do this in refresh

2021-03-05 05:55 UTC, sahil28297 approved these changes

2021-03-05 05:56 UTC, merged