fix: fixed status updation of production plan on the basis of purchase receipt submission
DigiThinkIT/erpnext pull request #1073
Opened 2021-03-05 13:14 UTC by MyuddinKhatri

Ref: [Asana](https://app.asana.com/0/1192407896547052/1199138927951885)

2021-03-08 04:27 UTC, hrwX requested changes

2021-03-08 04:27 UTC, hrwX commented on erpnext/manufacturing/doctype/production_plan/production_plan.py
> +	produced_qty = [item.produced_qty if item.produced_qty else int(0) for item in production_plan.mr_items if item.material_request_type == "Manufacture"]
```suggestion
	all_received = [item.per_received if item.per_received else 0 for item in production_plan.mr_items if item.material_request_type == "Purchase"]
	produced_qty = [item.produced_qty if item.produced_qty else 0 for item in production_plan.mr_items if item.material_request_type == "Manufacture"]
```

2021-03-08 06:07 UTC, hrwX approved these changes

2021-03-10 09:43 UTC, sahil28297 approved these changes

2021-03-10 09:43 UTC, merged