fix: assign default validation method if blank before save
DigiThinkIT/erpnext pull request #1074
Opened 2021-03-05 13:33 UTC by hitenshKharva

Ref: [Asana Task](https://github.com/hitenshKharva/erpnext/pull/new/validation_method_default_update)

Default Validation Method Set: Moving Average 
![image](https://user-images.githubusercontent.com/56474017/110117426-d7b35d00-7dde-11eb-94d2-408088dd1fa1.png)

https://user-images.githubusercontent.com/56474017/110122292-72af3580-7de5-11eb-94c6-ffeeb5711722.mp4

2021-03-08 04:17 UTC, hrwX requested changes

2021-03-08 04:17 UTC, hrwX commented on erpnext/stock/doctype/item/item.py
> +				self.valuation_method = method
- Set the default in Stock Settings
- Before saving stock settings, if empty set FIFO in there

2021-03-08 11:59 UTC, rvpasari approved these changes, later dismissed

2021-03-10 09:28 UTC, hrwX approved these changes

2021-03-10 09:46 UTC, hrwX requested changes

2021-03-10 09:46 UTC, hrwX commented on erpnext/stock/doctype/stock_settings/stock_settings.js
> +		}
```suggestion
	before_save: function(frm){
		if (!frm.doc.valuation_method){
			frm.set_value("valuation_method", "FIFO");
		}
```
Set FIFO as default in stock settings json

2021-03-11 12:51 UTC, sahil28297 commented
@hitenshKharva you'll need to add a patch as well to set it in stock_settings

2021-03-11 13:56 UTC, hitenshKharva commented
@sahil28297 added patch

2021-03-12 09:57 UTC, hrwX approved these changes

2021-03-12 10:10 UTC, merged

2021-03-15 06:15 UTC, sahil28297 commented
@hitenshKharva add proper task link

2021-03-15 06:17 UTC, hitenshKharva commented
@sahil28297 the link was copied wrong by mistake. Corrected it.