fix: added patch to assign default valuation method FIFO in item master
DigiThinkIT/erpnext pull request #1091
Opened 2021-03-16 04:52 UTC by hitenshKharva

Ref: [Asana Task](https://app.asana.com/0/1199082161983365/1199608531478425)

Patch added to update the valuation method for existing/older items in item master.

2021-03-16 05:02 UTC, rvpasari approved these changes, later dismissed

2021-03-16 05:07 UTC, hrwX requested changes

2021-03-16 05:07 UTC, hrwX commented on erpnext/patches/v13_0/set_stock_valuation_method.py
> +            frappe.db.set_value("Item", item.name, "valuation_method", "FIFO", update_modified=False)
- Use SQL to set it as FIFO where value doesn't exist.
- We can save time taken in fetching all the items and then iterating over them

2021-03-17 10:18 UTC, hrwX approved these changes

2021-03-17 10:31 UTC, rvpasari approved these changes

2021-03-17 10:37 UTC, sahil28297 approved these changes

2021-03-17 10:37 UTC, merged