Linking Sticker Items to the Batch they're created for in Material Request
DigiThinkIT/erpnext pull request #1094
Opened 2021-03-16 07:47 UTC by vishdha

TASK ID: [ASANA](https://app.asana.com/0/1192407894480744/1200009803660563)
Changes:
1. Added Material Request in Dashboard
2.  Added Create Material Request (coa batch) button to create a material request for coa bath
3.  carry forward coa batch and label details from material request to subsequent document like purchase order, purchase receipt, and purchase invoice

2021-03-17 11:41 UTC, hrwX requested changes

2021-03-17 11:41 UTC, hrwX commented on erpnext/stock/doctype/material_request_item/material_request_item.json
> +  "coa_batch",
was removing label_qty intentional ?

2021-03-17 13:00 UTC, vishdha commented on erpnext/stock/doctype/material_request_item/material_request_item.json
> +  "coa_batch",
yes

2021-03-17 13:08 UTC, sahil28297 submitted a review, later dismissed

2021-03-17 13:08 UTC, sahil28297 commented
@vishdha please fix the conflicts for this PR.

2021-03-18 04:51 UTC, hrwX approved these changes

2021-03-18 04:55 UTC, sahil28297 approved these changes

2021-03-18 04:56 UTC, merged