fix: stock reconciliation list pulling item with 0 stock
DigiThinkIT/erpnext pull request #1095
Opened 2021-03-16 10:26 UTC by hitenshKharva

Ref: [Asana Task](https://app.asana.com/0/1199082161983365/1200026413350136)

https://user-images.githubusercontent.com/56474017/111294171-0e576600-8670-11eb-9ac1-b20c0a6181f0.mp4

2021-03-16 11:30 UTC, rvpasari requested changes

2021-03-16 11:30 UTC, rvpasari commented on erpnext/stock/doctype/stock_reconciliation/stock_reconciliation.py
> +		if (frappe.db.get_value("Item", d[0], "disabled") == 0) and stock_bal[0]:
check for greater than zero, in case of negative balances

2021-03-17 06:03 UTC, vishdha approved these changes, later dismissed

2021-03-17 06:03 UTC, vishdha commented on erpnext/stock/doctype/stock_reconciliation/stock_reconciliation.py
> +		if (frappe.db.get_value("Item", d[0], "disabled") == 0) and (stock_bal[0]>0):
```suggestion
		if (frappe.db.get_value("Item", d[0], "disabled") == 0) and (stock_bal[0] > 0):
```

2021-03-17 10:30 UTC, hrwX requested changes

2021-03-17 10:30 UTC, hrwX commented on erpnext/stock/doctype/stock_reconciliation/stock_reconciliation.py
> +		if (frappe.db.get_value("Item", d[0], "disabled") == 0) and (stock_bal[0]>0):
```suggestion
		if frappe.db.get_value("Item", d[0], "disabled") == 0 and stock_bal[0] > 0:
```

2021-03-17 12:30 UTC, hrwX approved these changes, later dismissed

2021-03-17 12:44 UTC, rvpasari commented
@sahil28297 don't merge this yet.

2021-03-18 10:48 UTC, rvpasari approved these changes

2021-03-18 11:00 UTC, rvpasari commented
@sahil28297 resolved the queries I had related to this task, we can merge it now.

2021-03-19 07:37 UTC, sahil28297 approved these changes

2021-03-19 07:37 UTC, merged