fix: added popup to select customer and create Sales Order from Batch
DigiThinkIT/erpnext pull request #1106
Opened 2021-03-18 11:24 UTC by MyuddinKhatri

Ref: [Asana](https://app.asana.com/0/1188891334286779/1199981947354523)

![screencast-bloomstack_demo_8000-2021 03 18-16_50_18 (1)](https://user-images.githubusercontent.com/53251406/111618392-5611f500-880a-11eb-874f-c142d8d9d6d6.gif)

2021-03-18 12:38 UTC, rvpasari submitted a review, later dismissed

2021-03-19 06:44 UTC, hrwX requested changes

2021-03-19 06:44 UTC, hrwX commented on erpnext/stock/doctype/batch/batch.js
> +			})
Commonize this function

2021-03-19 07:35 UTC, sahil28297 approved these changes

2021-03-19 07:35 UTC, merged