feat: Batch Selector in Deliver Note for each new Batch add a new line
DigiThinkIT/erpnext pull request #1111
Opened 2021-03-19 16:31 UTC by vishdha

TASK ID: [ASANA](https://app.asana.com/0/1192407894480744/1200038837128969)

2021-03-19 16:33 UTC, vishdha commented
depends on pull request https://github.com/Bloomstack/erpnext/pull/1109#issue-596324105

2021-03-22 05:49 UTC, hrwX requested changes

2021-03-22 05:49 UTC, hrwX commented on erpnext/public/js/controllers/transaction.js
> +				let blank_item_row = ""
```suggestion
				let existing_item_row = null;
				let blank_item_row = null;
```

2021-03-22 05:51 UTC, sahil28297 approved these changes

2021-03-22 05:51 UTC, merged