fix: added check to throw error if sample retention warehouse is not set if user selects retain sample in stock entry
DigiThinkIT/erpnext pull request #1120
Opened 2021-03-25 09:12 UTC by MyuddinKhatri

Ref: [Asana](https://app.asana.com/0/1192407896547052/1200103871317991)

2021-03-25 09:51 UTC, hrwX requested changes

2021-03-25 09:51 UTC, hrwX commented on erpnext/stock/doctype/stock_entry/stock_entry.py
> +		frappe.throw(_("Please set Sample Retention Warehouse in Stock Settings"))
```suggestion

	if not retention_warehouse:
		frappe.throw(_("Please set Sample Retention Warehouse in Stock Settings"))

```

2021-03-25 09:52 UTC, hrwX approved these changes

2021-03-26 04:36 UTC, sahil28297 approved these changes

2021-03-26 04:36 UTC, merged