feat: added ability to pick a select number of random questions from a question pool while showing a quiz
DigiThinkIT/erpnext pull request #1128
Opened 2021-03-30 10:01 UTC by MyuddinKhatri

Ref: [Asana](https://app.asana.com/0/1192407896547052/1200048723927510)

2021-03-31 00:58 UTC, rvpasari requested changes

2021-03-31 00:58 UTC, rvpasari commented on erpnext/education/doctype/quiz/quiz.py
> +		if self.assessment_questions:
Comments please

2021-03-31 00:58 UTC, rvpasari commented on erpnext/education/doctype/quiz/quiz.py
> +			for question in response_dict.items():
Is there a cleaner way to do this? Its a nested loop with a try catch block inside of it - just looks ugly

2021-04-05 05:05 UTC, hrwX requested changes

2021-04-05 05:05 UTC, hrwX commented on erpnext/education/doctype/quiz/quiz.py
>  			status = "Fail"
Can you commonify the two loops, looks like duplicate code

2021-04-05 08:49 UTC, hrwX requested changes

2021-04-05 08:49 UTC, hrwX commented on erpnext/education/doctype/quiz/quiz.py
> +				result = evaluate_response(answers, response_dict)
- evaluate_response returns a dict, I think we will have to do dict.update instead of assigning a value directly

2021-04-05 12:33 UTC, hrwX approved these changes

2021-04-05 17:06 UTC, rvpasari commented on erpnext/education/doctype/quiz/quiz.py
> +def evaluate_response(answers, response_dict):
please drop docstrings and comments on what this function does, will make code review easier

2021-04-06 10:08 UTC, sahil28297 approved these changes

2021-04-06 10:08 UTC, merged