fix: hide unhide fields for Sales Invoice Print Format
DigiThinkIT/erpnext pull request #1167
Opened 2021-04-08 13:18 UTC by bhattdevarsh

[TASK](https://app.asana.com/0/1192407897953440/1200104237401110/f)

2021-04-09 05:47 UTC, sahil28297 commented
@bhattdevarsh can you add screenshots for the changes?

2021-04-12 07:39 UTC, vishdha commented on erpnext/accounts/doctype/sales_invoice_item/sales_invoice_item.json
> +   "read_only": 1
@bhattdevarsh   is this intentional because after that user not able to enter the amount in this field

2021-04-12 07:39 UTC, vishdha commented on erpnext/accounts/doctype/sales_invoice/sales_invoice.json
> -   "allow_on_submit": 1
@bhattdevarsh same with this field

2021-04-12 07:39 UTC, vishdha commented on erpnext/accounts/doctype/sales_invoice/sales_invoice.json
> -   "allow_on_submit": 1
@bhattdevarsh same with this field

2021-04-15 09:47 UTC, hrwX commented
@bhattdevarsh Can you update the PR

2021-04-15 12:20 UTC, nehasacher143 requested changes
@bhattdevarsh  The only property that you have to touch for this task is the 'Print Hide' nothing else
Please make the changes

2021-04-16 05:43 UTC, bhattdevarsh commented
@hrwX @vishdha @nehasacher143  if you notice closely the properties are moved from one line to another. there are no changes. I have updated where changes were really required.

2021-04-16 07:37 UTC, sahil28297 commented
Closing this as a we'll be making new print formats and not tinker with the standard print formats.

2021-04-16 07:37 UTC, closed without merging