fix: Pick List Applied Filters for unused package tag and updating package tag on submit/cancel of Purchase Receipt
DigiThinkIT/erpnext pull request #1181
Opened 2021-04-14 11:13 UTC by bhattdevarsh

Purchase Receipt:
[TASK1](https://app.asana.com/0/1192407897953440/1200116476785917/f)

![PR_update_Packagetag_isused](https://user-images.githubusercontent.com/58166671/114701273-38b84400-9d40-11eb-954d-47d056ee7d8d.gif)

Pick List:
[TASK2](https://app.asana.com/0/1192407897953440/1200116476785918/f)

![picklist_packagetag_filter](https://user-images.githubusercontent.com/58166671/114700925-ca738180-9d3f-11eb-88d8-aae99df520d7.gif)

2021-04-16 09:20 UTC, hrwX requested changes

2021-04-16 09:20 UTC, hrwX commented on erpnext/stock/doctype/pick_list/pick_list.js
> +					"item_code": ["IN", [row.item_code, ""]],
```suggestion
```
- Package tags with is_used = 0 are considered as empty package tags

2021-04-19 05:04 UTC, sahil28297 approved these changes

2021-04-19 05:05 UTC, sahil28297 approved these changes

2021-04-19 05:05 UTC, merged