made changes in packing slip files
DigiThinkIT/erpnext pull request #1182
Opened 2021-04-14 11:29 UTC by shantanu-kadam-epi

> Please provide enough information so that others can review your pull request:

> Explain the **details** for making this change. What existing problem does the pull request solve?

> Screenshots/GIFs

2021-04-14 12:13 UTC, shantanu-kadam-epi commented
Asana Ticket Link: https://app.asana.com/0/1200151327710888/1200022610032012

2021-04-16 09:19 UTC, hrwX requested changes

2021-04-16 09:19 UTC, hrwX commented on erpnext/stock/doctype/packing_slip/packing_slip.js
> +		frappe.msgprint(__("'To Package No.' cannot be less than 'From Package No.'"));
```suggestion
		frappe.msgprint(__("<b>To Package No.</b> cannot be less than <b>From Package No.</b>"));
```

2021-04-16 09:19 UTC, hrwX commented on erpnext/stock/doctype/packing_slip/packing_slip.py
> +			frappe.msgprint(_("'To Package No.' cannot be less than 'From Package No.'"),
```suggestion
			frappe.msgprint(_("<b>To Package No.</b> cannot be less than <b>From Package No.</b>"),
```

2021-04-16 10:19 UTC, shantanu-kadam-epi commented
Closing this, New pull request created.
https://github.com/Bloomstack/erpnext/pull/1185

2021-04-16 10:19 UTC, closed without merging