fix: remove wise from cost center financial report
DigiThinkIT/erpnext pull request #1184
Opened 2021-04-16 06:11 UTC by hitenshKharva

Ref : [Asana Task](https://app.asana.com/0/1199082161983365/1199966341817846)

![image](https://user-images.githubusercontent.com/56474017/114979532-a54e5280-9ea8-11eb-9fa3-a7882dc3cfc2.png)

2021-04-16 09:37 UTC, hrwX requested changes, later dismissed

2021-04-16 09:37 UTC, hrwX commented on erpnext/accounts/report/cost_center_financial_statements/cost_center_financial_statements.js
> +				console.log(frappe.query_report.get_filter_value("company"));
```suggestion
```

2021-04-16 09:37 UTC, hrwX commented on erpnext/accounts/report/cost_center_financial_statements/cost_center_financial_statements.js
> +
```suggestion
```

2021-04-16 09:37 UTC, hrwX commented on erpnext/patches.txt
> +execute:frappe.delete_doc("Report", "Cost Center Wise Financial Statements")
```suggestion
execute:frappe.delete_doc_if_exists("Report", "Cost Center Wise Financial Statements")
```

2021-04-17 01:37 UTC, rvpasari approved these changes, later dismissed

2021-04-17 01:37 UTC, rvpasari commented on erpnext/accounts/report/cost_center_financial_statements/cost_center_financial_statements.js
> +				return frappe.db.get_link_options('Cost Center', txt, {
This is an interesting function, will discuss @hrwX

2021-04-19 05:10 UTC, sahil28297 commented
@hitenshKharva Did you delete the files for the existing "wise" report? I cannot see old files being deleted in this PR.

2021-04-19 05:35 UTC, hitenshKharva commented
@sahil28297 I deleted files and tried to commit, Git shows files renamed. Therefore, I wrote a patch to delete the old files. I have committed deletion of files. Review it and let me know the changes.

2021-04-19 05:55 UTC, sahil28297 approved these changes

2021-04-19 05:58 UTC, merged