chore: packing slip msg display bold
DigiThinkIT/erpnext pull request #1185
Opened 2021-04-16 10:17 UTC by shantanu-kadam-epi

2021-04-17 01:33 UTC, rvpasari requested changes
Why are we converting this message to bold, without the actual package nos in the message?

2021-04-19 04:51 UTC, shantanu-kadam-epi commented
Packing slip message should be in bold, it is suggested by Himanshu

2021-04-21 07:27 UTC, hrwX submitted a review, later dismissed

2021-04-21 07:55 UTC, sahil28297 requested changes

2021-04-21 07:55 UTC, sahil28297 commented on erpnext/stock/doctype/packing_slip/packing_slip.py
> +			frappe.msgprint(_("<b>To Package No.: {0}</b> cannot be less than <b>From Package No.: {1}</b>",[doc.to_case_no , doc.from_case_no]),
```suggestion
			frappe.msgprint(_("<b>To Package No.: {0}</b> cannot be less than <b>From Package No.: {1}</b>").format(doc.to_case_no, doc.from_case_no),
```

2021-04-21 09:01 UTC, shantanu-kadam-epi commented
![image](https://user-images.githubusercontent.com/60215482/115526934-2bee9f80-a2ae-11eb-9718-a1144fc72b2a.png)

2021-04-22 05:45 UTC, sahil28297 approved these changes

2021-04-22 05:45 UTC, merged