Fix: Rename field name from Delivered to Fulfilled
DigiThinkIT/erpnext pull request #1186
Opened 2021-04-16 14:00 UTC by meshramsaroj

**Task Link:** https://app.asana.com/0/1188891334286779/1200085162814890/f

**Description:**  Rename field name from Delivered to Fulfilled

**Screenshot:**

![image](https://user-images.githubusercontent.com/53329367/115035229-fc284c00-9ee9-11eb-90e4-6796f333b66c.png)

2021-04-17 01:31 UTC, rvpasari requested changes
@hrwX should we change the fieldname as well and run a patch to update it? I'm thinking that would be a better long term fix.

@meshramsaroj if Himanshu's signs off on it, please change the field name to "fulfilled" as well. Ask Sahil/Himanshu on what the patch should exactly be.

2021-04-19 05:07 UTC, hrwX commented
> @hrwX should we change the fieldname as well and run a patch to update it? I'm thinking that would be a better long term fix.
> 
> @meshramsaroj if Himanshu's signs off on it, please change the field name to "fulfilled" as well. Ask Sahil/Himanshu on what the patch should exactly be.

No need for a patch since we are just changing the label

2021-04-19 05:08 UTC, hrwX approved these changes

2021-04-19 05:12 UTC, sahil28297 approved these changes

2021-04-19 05:12 UTC, merged