fix: its create Separate Line Items for Batch nos and Package Tags
DigiThinkIT/erpnext pull request #1207
Opened 2021-04-29 09:48 UTC by MyuddinKhatri

Ref: [Asana](https://app.asana.com/0/1192407896547052/1200099124039411)

2021-04-29 11:30 UTC, rvpasari requested changes

2021-04-29 11:30 UTC, rvpasari commented on erpnext/stock/doctype/stock_reconciliation/stock_reconciliation.py
> +			package_tags_and_batch_nos = frappe.get_all("Stock Ledger Entry",
please add comments or I will block the PR from being merged

2021-04-30 06:10 UTC, neilLasrado approved these changes

2021-04-30 06:13 UTC, sahil28297 approved these changes

2021-04-30 06:13 UTC, merged