Fix: Added a check for creation of material request in production plan
DigiThinkIT/erpnext pull request #1227
Opened 2021-05-04 21:00 UTC by shruti2323

1. Once the production plan is created and if Material Request Plan Item is not present i.e not selected Get Raw Material for Production. Then it should not be able to see an option of create material request once we submit the production plan and click on create button.
2. Below is the attached img and gif for the same. 
3. ![MR_without_get_raw_material](https://user-images.githubusercontent.com/80836439/117067992-5594d580-ad48-11eb-860a-1a698228290a.PNG)
4. Uploading MR_saving_skeptical_without_Get_raw_material.mp4…

Fix : for not  selecting Get Raw Material for Production, once we submit the production plan and click on create button. The material request option is made hidden i.e unless mr_list[0] not present (data) -> grade the option to create material request.
Below is the fix attached img for the same. 
![MR_fix_without_get_raw_material](https://user-images.githubusercontent.com/80836439/117068412-e10e6680-ad48-11eb-89e0-2c1181a49178.PNG)

1. Once the production plan is created and if Material Request Plan Item is present i.e selected Get Raw Material for Production. Then it should be able to see an option of create material request once we submit the production plan and click on create button.
2. Also if we click outside the prompt button once it asks to confirm whether we need to create a material request or not . Depending upon the options it should create material request 
YES -  should create material req.
NO- should notcreate material req.
Clicked outside the prompt -  should not  create material req.
3. Below is the attached img and gif for the same. 
4. ![MR_with_get_raw_material](https://user-images.githubusercontent.com/80836439/117068979-8e817a00-ad49-11eb-9a06-82eb992e16e7.PNG)
5. https://user-images.githubusercontent.com/80836439/117068984-8fb2a700-ad49-11eb-800a-fb16360e9c71.mp4

Fix : on selecting Get Raw Material for Production, once we submit the production plan and click on create button and confirms yes to create material request , then and only it should create it else prompt a message "No material request created"
Below is the fix attached img and gif for the same. 
![MR_fix_get_raw_materials](https://user-images.githubusercontent.com/80836439/117069211-dc967d80-ad49-11eb-9040-1bd31bd5e59d.PNG)

https://user-images.githubusercontent.com/80836439/117069222-ddc7aa80-ad49-11eb-8ffa-fc0d7a23a16d.mp4

2021-05-05 07:01 UTC, hrwX requested changes

2021-05-05 07:01 UTC, hrwX commented on erpnext/manufacturing/doctype/production_plan/production_plan.js
> +		}
- This is an incorrect fix.
- Check in `make_material_request`, 
    - check if doc is submitted, then directly trigger `create_material_request` function
    - if the doc is not submitted, then show `frappe.confirm`

2021-05-05 11:22 UTC, shruti2323 commented on erpnext/manufacturing/doctype/production_plan/production_plan.js
> +		frm.events.create_material_request(frm, 1);
frm.events.create_material_request(frm, 1)
Above code , passes the docstatus as "1" which Submitted , only then create material request via Create button/ Dashboard + option 
Below are the attached image for this fix: - 
![MR_not_saved](https://user-images.githubusercontent.com/80836439/117133657-28850900-adc2-11eb-9cd5-0131761bf862.PNG)
![MR_saved1](https://user-images.githubusercontent.com/80836439/117133660-29b63600-adc2-11eb-8d2f-5bf5e0933d2e.PNG)
![MR_saved](https://user-images.githubusercontent.com/80836439/117133663-29b63600-adc2-11eb-8176-90432b6cee95.PNG)

https://user-images.githubusercontent.com/80836439/117133665-2a4ecc80-adc2-11eb-9bf3-ce8aaa36fdd0.mp4

2021-05-06 06:43 UTC, hrwX requested changes

2021-05-06 06:43 UTC, hrwX commented on erpnext/manufacturing/doctype/production_plan/production_plan.js
> +		if (frm.doc.docstatus === 1 && frm.doc.mr_items.length>0
```suggestion
		if (frm.doc.docstatus === 1 && frm.doc.mr_items.length
```

2021-05-06 07:15 UTC, closed without merging