[WIP] Prompt user to select batch numbers
DigiThinkIT/erpnext pull request #123
Opened 2018-12-28 13:54 UTC by Alchez

**Todo:**

- Test to ensure this doesn't violently break workflows elsewhere, or just violently break, in general.

2019-01-02 05:04 UTC, vjFaLk commented
Add screenshot please.

2019-01-02 06:15 UTC, Alchez commented
@vjFaLk 

![batch-select](https://user-images.githubusercontent.com/13396535/50581890-e4953880-0e83-11e9-9cbe-48c25ad94363.gif)

2019-01-02 11:04 UTC, vjFaLk requested changes

2019-01-02 11:04 UTC, vjFaLk commented on erpnext/accounts/doctype/sales_invoice/sales_invoice.py
> +			and frappe.db.get_single_value("Stock Settings", "automatically_set_batch_nos_based_on_fifo"):
Er, technically according to syntax, but not really?

2019-01-02 11:04 UTC, vjFaLk commented on erpnext/stock/doctype/delivery_note/delivery_note.py
> +			and frappe.db.get_single_value("Stock Settings", "automatically_set_batch_nos_based_on_fifo"):
Er, technically according to syntax, but not really?

2019-01-07 09:05 UTC, vjFaLk commented
Make this to Upstream, probably to develop.

2019-01-07 10:19 UTC, Alchez commented
Made upstream: https://github.com/frappe/erpnext/pull/16353

2019-01-07 10:31 UTC, vjFaLk commented
Thought - Maybe have a button to bring up that dialog again. In case the User accidentally dismisses the popup (which they do a lot) they can bring it back up. 

I know hitting "Save" will bring it up, but that's bad UX

2019-01-07 10:32 UTC, Alchez commented
Yeah, good call.

2019-01-10 08:47 UTC, vjFaLk approved these changes

2019-01-10 08:47 UTC, merged