fix: added docstring to purchase_receipt.py and stock_entry.py
DigiThinkIT/erpnext pull request #1279
Opened 2021-05-12 06:04 UTC by MyuddinKhatri

Ref: [Asana](https://app.asana.com/0/1192407896547052/1200245199510484)

2021-05-12 06:50 UTC, hrwX submitted a review, later dismissed

2021-05-17 04:36 UTC, rvpasari requested changes

2021-05-17 04:36 UTC, rvpasari commented on erpnext/stock/doctype/purchase_receipt/purchase_receipt.py
> +		# update batch doc with supplier if batch doc don't have supplier
This comment is pretty useless, it does nothing that the function header does not already explain.

2021-05-17 04:36 UTC, rvpasari commented on erpnext/stock/doctype/stock_entry/stock_entry.py
> +		# update batch doc with provided by customer if batch doc don't have provided by customer
Same case here, comment is useless.

2021-05-17 04:36 UTC, rvpasari commented on erpnext/stock/doctype/stock_entry/stock_entry.py
> +		# update batch doc with provided by customer if batch doc don't have provided by customer
Specify that is is being done only when the stock entry is a "Material Receipt". Each of the "if" statements should have a comment before explaining the purpose of the cases. The logic of the function should be visible in the comments.

2021-05-20 05:27 UTC, sahil28297 approved these changes

2021-05-20 05:27 UTC, merged