chore :Due date validation in quotation
DigiThinkIT/erpnext pull request #1294
Opened 2021-05-18 13:15 UTC by shantanu-kadam-epi

Asana Ticket Link:  https://app.asana.com/0/1200301108563886/1199893804493437

![image](https://user-images.githubusercontent.com/60215482/118657578-3c405e80-b809-11eb-971c-3f2d83056e06.png)

2021-05-19 06:46 UTC, hrwX requested changes

2021-05-19 06:46 UTC, hrwX commented on erpnext/controllers/accounts_controller.py
> +			if self.doctype in ("Sales Invoice", "Quotation") and getdate(d.due_date) < getdate(self.transaction_date):
- Was there any reason to change sales order to sales invoice ?

2021-05-19 07:52 UTC, shantanu-kadam-epi commented
@hrwX , I referred the above condition, so it was by mistake. I have updated doctype name

2021-05-21 07:05 UTC, vishdha commented
@sahil28297  validated with @neilLasrado

2021-05-21 07:46 UTC, sahil28297 approved these changes

2021-05-21 07:46 UTC, merged