Fix: Fix the Requested Delivery Date back dated with comparison to Da…
DigiThinkIT/erpnext pull request #1296
Opened 2021-05-18 21:43 UTC by shruti2323

System allows to set "Requested Delivery Date" back dated with comparison to "Date" calendar field value & save details. 
Added an validation from both backend end and frontend to validate - 
1. "**Requested Delivery Date**" back dated with comparison to "**Date**" value.
2. "**Valid Till Date**" back dated with comparison to "**Date**" value.

Below is the Snap and gif attached : -
**BEFORE FIELD BEHAVIOUR**
![QuotationList-Before](https://user-images.githubusercontent.com/80836439/118727204-0bcfe300-b850-11eb-86fb-6fcbb9748028.PNG)

https://user-images.githubusercontent.com/80836439/118727211-0d011000-b850-11eb-9648-0cf6468256d1.mp4

**AFTER FIX : FIELD BEHAVIOUR**
![QuotationList-After-valid-till](https://user-images.githubusercontent.com/80836439/118727243-19856880-b850-11eb-90ed-fc63712d5878.PNG)
![QuotationList-After-req-del-date](https://user-images.githubusercontent.com/80836439/118727247-1a1dff00-b850-11eb-9626-8107f2d46cda.PNG)

https://user-images.githubusercontent.com/80836439/118727248-1ab69580-b850-11eb-9036-944146eb5ae1.mp4

2021-05-19 06:41 UTC, hrwX requested changes

2021-05-19 06:41 UTC, hrwX commented on erpnext/selling/doctype/quotation/quotation.js
> +
```suggestion
```

2021-05-19 06:49 UTC, hrwX approved these changes

2021-05-19 11:55 UTC, sahil28297 commented
@shruti2323 please add the the task in the PR description

2021-05-19 14:12 UTC, shruti2323 commented
> @shruti2323 please add the the task in the PR description

Asana Task : - https://app.asana.com/0/1200073273462988/1199893804493435

2021-05-21 07:05 UTC, vishdha commented
@sahil28297  validated with @neilLasrado

2021-05-21 07:45 UTC, sahil28297 approved these changes

2021-05-21 07:45 UTC, merged