fix: Email COA's from Sales Invoice
DigiThinkIT/erpnext pull request #1301
Opened 2021-05-20 09:18 UTC by hitenshKharva

Ref: [Asana Task](https://app.asana.com/0/1199082161983365/1200166130781170)

![image](https://user-images.githubusercontent.com/56474017/118953439-6feec600-b97a-11eb-9026-03783d9fa6e8.png)

2021-05-20 11:17 UTC, hrwX requested changes

2021-05-20 11:17 UTC, hrwX commented on erpnext/accounts/doctype/sales_invoice/sales_invoice.py
> +		delivery_note = frappe.get_doc("Delivery Note", item.delivery_note).as_dict()
```suggestion
		delivery_note = frappe.db.get_value("Delivery Note", item., "contact_email"delivery_note)
```

2021-05-20 11:17 UTC, hrwX commented on erpnext/accounts/doctype/sales_invoice/sales_invoice.js
> +	email_coas: function(doc) {
```suggestion
	email_coa: function(frm) {
```

2021-05-20 11:17 UTC, hrwX commented on erpnext/accounts/doctype/sales_invoice/sales_invoice.js
> +				docname: doc.name
```suggestion
				docname: frm.doc.name
```

2021-05-20 11:17 UTC, hrwX commented on erpnext/accounts/doctype/sales_invoice/sales_invoice.js
> +				if(r.message == "success"){
```suggestion
				if(r && r.message == "success"){
```

2021-05-20 11:17 UTC, hrwX commented on erpnext/accounts/doctype/sales_invoice/sales_invoice.js
> +						message: __('Email Queued')
```suggestion
						message: __('Email Sent')
```

2021-05-20 11:17 UTC, hrwX commented on erpnext/accounts/doctype/sales_invoice/sales_invoice.json
> +  "email_coas",
```suggestion
  "email_coa",
```

2021-05-20 11:17 UTC, hrwX commented on erpnext/accounts/doctype/sales_invoice/sales_invoice.json
> +   "fieldname": "email_coas",
```suggestion
   "fieldname": "email_coa",
```

2021-05-20 11:17 UTC, hrwX commented on erpnext/accounts/doctype/sales_invoice/sales_invoice.py
> +		if not delivery_note.get("contact_email"):
```suggestion
		if not delivery_note:
```

2021-05-20 11:17 UTC, hrwX commented on erpnext/accounts/doctype/sales_invoice/sales_invoice.py
> +			frappe.throw(_("No contact email found"))
```suggestion
			frappe.throw(_("No contact email found in Delivery Note {0}").format(item.delivery_note))
```

2021-05-20 11:17 UTC, hrwX commented on erpnext/accounts/doctype/sales_invoice/sales_invoice.py
> +		attachments = []
```suggestion
		attachments = []
```

- Only attachments for last item will be sent.
- move attachments list out of for loop

2021-05-21 04:54 UTC, hrwX requested changes

2021-05-21 04:54 UTC, hrwX commented on erpnext/accounts/doctype/sales_invoice/sales_invoice.py
> +			frappe.msgprint(_("No Certificates of Analysis attached"))
```suggestion
			frappe.msgprint(_("No Certificates of Analysis attached for Item {0} in Delivery Note {1}.").format(item.item_code, item.delivery_note))
```

2021-05-21 04:54 UTC, hrwX commented on erpnext/accounts/doctype/sales_invoice/sales_invoice.js
> +	email_coa: function(doc) {
```suggestion
	email_coa: function() {
```

2021-05-21 04:54 UTC, hrwX commented on erpnext/accounts/doctype/sales_invoice/sales_invoice.js
> +				docname: doc.name
```suggestion
				docname: this.frm.doc.name
```

2021-05-21 04:56 UTC, sahil28297 requested changes

2021-05-21 04:56 UTC, sahil28297 commented on erpnext/accounts/doctype/sales_invoice/sales_invoice.py
> +		attachments.append({"fid": coa_file_id})
```suggestion

		if not coa_file_id:
			frappe.msgprint(_("No File found for {0}").format(coas))
			return

		attachments.append({"fid": coa_file_id})
```

2021-05-21 04:56 UTC, sahil28297 commented on erpnext/accounts/doctype/sales_invoice/sales_invoice.py
> +			frappe.throw(_("No contact email found in Delivery Note {0}").format(item.delivery_note))
```suggestion
			frappe.msgprint(_("No contact email found in Delivery Note {0}").format(item.delivery_note))
			return
```

2021-05-21 04:58 UTC, hrwX requested changes

2021-05-21 04:58 UTC, hrwX commented on erpnext/accounts/doctype/sales_invoice/sales_invoice.py
> +			return
```suggestion
			continue
```

2021-05-21 04:58 UTC, hrwX commented on erpnext/accounts/doctype/sales_invoice/sales_invoice.py
> +			return
```suggestion
			continue
```

2021-05-21 04:58 UTC, hrwX commented on erpnext/accounts/doctype/sales_invoice/sales_invoice.py
> +			return
```suggestion
			continue
```

2021-05-21 05:01 UTC, hrwX submitted a review, later dismissed

2021-05-21 05:12 UTC, sahil28297 requested changes

2021-05-21 05:12 UTC, sahil28297 commented on erpnext/accounts/doctype/sales_invoice/sales_invoice.py
> +	)
```suggestion
	if delivery_note.get("contact_email") and attachments:
		frappe.sendmail(
			recipients=delivery_note.get("contact_email"),
			subject="Certificate of Analysis",
			attachments=attachments
		)
```

2021-05-21 07:07 UTC, rvpasari requested changes

2021-05-21 07:07 UTC, rvpasari commented on erpnext/accounts/doctype/sales_invoice/sales_invoice.py
> +def email_coa(docname):
Where is the docstring?

2021-05-21 07:07 UTC, rvpasari commented on erpnext/accounts/doctype/sales_invoice/sales_invoice.py
> +	for item in sales_invoice.items:
comments for each block

2021-05-21 07:07 UTC, rvpasari commented on erpnext/accounts/doctype/sales_invoice/sales_invoice.py
> +			frappe.msgprint(_("No contact email found in Delivery Note {0}").format(item.delivery_note))
Have you tested if this message print works? Does the .format() have to be inside the _("") or outside?

2021-05-21 07:07 UTC, rvpasari commented on erpnext/accounts/doctype/sales_invoice/sales_invoice.py
> +	if delivery_note.get("contact_email") and attachments:
add description in comments

2021-05-21 07:47 UTC, hitenshKharva commented on erpnext/accounts/doctype/sales_invoice/sales_invoice.py
> +			frappe.msgprint(_("No contact email found in Delivery Note {0}").format(item.delivery_note))
![image](https://user-images.githubusercontent.com/56474017/119101641-d33e2e00-ba36-11eb-8690-451ca680e6fa.png)

yes

2021-05-21 08:06 UTC, hitenshKharva commented on erpnext/accounts/doctype/sales_invoice/sales_invoice.py
> +			frappe.msgprint(_("No contact email found in Delivery Note {0}").format(item.delivery_note))
Yes. Please find the attached screenshot for your reference.

![image](https://user-images.githubusercontent.com/56474017/119104047-6f693480-ba39-11eb-9ba6-08b0d1a3e066.png)

2021-05-21 08:26 UTC, sahil28297 approved these changes

2021-05-21 08:26 UTC, merged