feat: procument tracker report batch_no and package tag info added
DigiThinkIT/erpnext pull request #1307
Opened 2021-05-21 17:47 UTC by vishdha

Task ID:[ASANA](https://app.asana.com/0/1192407894480744/1200251298276131)

2021-05-24 05:55 UTC, hrwX requested changes, later dismissed

2021-05-24 05:55 UTC, hrwX commented on erpnext/buying/report/procurement_tracker/procurement_tracker.py
> +			package_tag = pr_records.get(po.name).get('package_tag')
```suggestion
		posting_date, batch_no, package_tag = None, None, None
		if pr_records.get(po.name):
			posting_date = pr_records.get(po.name).get('posting_date')
			batch_no = pr_records.get(po.name).get('batch_no')
			package_tag = pr_records.get(po.name).get('package_tag')
```

2021-05-25 07:38 UTC, hrwX submitted a review, later dismissed

2021-05-26 08:11 UTC, sahil28297 approved these changes

2021-05-26 08:11 UTC, merged