feat: add reports to desk, create reports page
DigiThinkIT/erpnext pull request #1317
Opened 2021-05-27 07:01 UTC by rvpasari

https://app.asana.com/0/1198955099016653/1200351819266681

2021-05-27 07:01 UTC, rvpasari commented
![Screen Shot 2021-05-27 at 12 30 58 PM](https://user-images.githubusercontent.com/3510207/119780465-7c799e00-bee7-11eb-8aca-ce42d675c9b7.png)
![Screen Shot 2021-05-27 at 12 30 42 PM](https://user-images.githubusercontent.com/3510207/119780476-7f748e80-bee7-11eb-8b2d-0d03eafc818c.png)

2021-05-28 05:18 UTC, hrwX requested changes, later dismissed

2021-05-28 05:18 UTC, hrwX commented on erpnext/config/desktop.py
> +		},
- do not add the reports module before accounting.
- put it at the end of the existing modules

2021-05-28 05:18 UTC, hrwX commented on erpnext/config/reports.py
> +    ]
- Fix indentations.

2021-05-31 04:43 UTC, hrwX requested changes, later dismissed

2021-05-31 04:43 UTC, hrwX commented on erpnext/config/reports.py
> +	]
- Indentation is still not correct, please fix it

2021-05-31 10:33 UTC, hrwX approved these changes

2021-06-01 08:14 UTC, sahil28297 approved these changes

2021-06-01 08:16 UTC, merged