feat: added product recall feature in erpnext
DigiThinkIT/erpnext pull request #1329
Opened 2021-05-28 12:25 UTC by MyuddinKhatri

Ref: [Asana](https://app.asana.com/0/1192407896547052/1200295554169058)

2021-05-28 16:26 UTC, rvpasari requested changes

2021-05-28 16:26 UTC, rvpasari commented on erpnext/stock/doctype/product_recall_notice/product_recall_notice.py
> +def create_stock_entry(product_recall_notice):
comments and docstrings please

2021-05-28 16:26 UTC, rvpasari commented on erpnext/stock/doctype/product_recall/product_recall.py
> +	def on_submit(self):
comments and docstrings please. Also, can this function be broken down into smaller functions? Specially because its on_submit - should ideally just call other functions that do the job in hand

2021-05-28 16:26 UTC, rvpasari commented on erpnext/stock/doctype/product_recall/product_recall.py
> +			sle_list.pop(0)
doing a pop(0) on a list is ineffecient - its an O(N) operation. @hrwX can we use the collections package over here? Thinking of using queues that come as part of it

2021-05-28 16:26 UTC, rvpasari commented on erpnext/stock/doctype/product_recall/product_recall.py
> +						sle_list = sle_list + sle_data
use a .append() if you are adding stuff to a list. + does the same thing, but .append() is better practice

2021-05-28 16:26 UTC, rvpasari commented on erpnext/stock/doctype/product_recall_notice/product_recall_notice.py
> +	elif product_recall_notice.get("recall_from") == "Customer":
why is this an elseif? Can the recall_from field have values other than "Warehouse" or customer?

2021-05-28 16:26 UTC, rvpasari commented on erpnext/stock/doctype/product_recall/product_recall.py
> +			doc_recall_from_customer.product_recall = self.name
can we do all of this inside the update()?

2021-05-28 16:26 UTC, rvpasari commented on erpnext/stock/doctype/product_recall_notice/product_recall_notice.js
> +		if(frm.doc.docstatus == 1) {
add a comment above this code block explaining what it does

2021-05-31 04:49 UTC, hrwX requested changes

2021-05-31 04:49 UTC, hrwX commented on erpnext/stock/doctype/product_recall/product_recall.py
> +			sle_list.pop(0)
- @MyuddinKhatri  any reason to pop the zeroth element ?

2021-05-31 10:48 UTC, MyuddinKhatri commented on erpnext/stock/doctype/product_recall/product_recall.py
> +			sle_list.pop(0)
want to remove first element one by one

2021-05-31 11:07 UTC, MyuddinKhatri commented on erpnext/stock/doctype/product_recall/product_recall.py
> +						sle_list = sle_list + sle_data
when i do .append() it creates list of list which gives error while iterating

2021-05-31 13:57 UTC, rvpasari commented on erpnext/stock/doctype/product_recall/product_recall.py
> +						sle_list = sle_list + sle_data
then use .extend()

2021-06-01 01:08 UTC, rvpasari submitted a review, later dismissed

2021-06-01 01:08 UTC, rvpasari commented on erpnext/stock/doctype/product_recall/product_recall.py
> +						sle_list = sle_list + sle_data
then use .extend()

2021-06-01 01:08 UTC, rvpasari commented on erpnext/stock/doctype/product_recall/product_recall.py
> +			if sle_doc.voucher_type == "Delivery Note":
Comments are still missing across the function. This function is anyways too huge. Please try breaking down the function into smaller pieces and comment the blocks

2021-06-01 01:08 UTC, rvpasari commented on erpnext/stock/doctype/product_recall_notice/product_recall_notice.py
> +def create_stock_entry(product_recall_notice):
please choose a better name for the function as well, create_stock_entry is very generic

2021-06-01 01:08 UTC, rvpasari commented on erpnext/stock/doctype/product_recall_notice/product_recall_notice.py
> +	for item in product_recall_notice.get("items"):
comments please

2021-06-01 01:08 UTC, rvpasari commented on erpnext/stock/doctype/product_recall_notice/product_recall_notice.py
> +			"item_code":item.get("item_code"),
```suggestion
			"item_code": item.get("item_code"),
```

2021-06-01 01:08 UTC, rvpasari commented on erpnext/stock/doctype/product_recall_notice/product_recall_notice.py
> +			"qty":item.get("qty"),
```suggestion
			"qty": item.get("qty"),
```

2021-06-01 01:08 UTC, rvpasari commented on erpnext/stock/doctype/product_recall_notice/product_recall_notice.py
> +			"batch_no":item.get("batch_no"),
```suggestion
			"batch_no": item.get("batch_no"),
```

2021-06-01 01:08 UTC, rvpasari commented on erpnext/stock/doctype/product_recall_notice/product_recall_notice.py
> +	stock_entry_doc.save()
@hrwX should we ideally be running .save() with ignore_permissions=True?

2021-06-01 01:08 UTC, rvpasari commented on erpnext/stock/doctype/product_recall/product_recall.py
> +				"product_recall" : self.name,
```suggestion
				"product_recall": self.name,
```

2021-06-01 01:08 UTC, rvpasari commented on erpnext/stock/doctype/product_recall/product_recall.py
> +				"recall_from" : "Warehouse",
```suggestion
				"recall_from": "Warehouse",
```

2021-06-01 01:08 UTC, rvpasari commented on erpnext/stock/doctype/product_recall/product_recall.py
> +				"recall_warehouse" : self.recall_warehouse,
```suggestion
				"recall_warehouse": self.recall_warehouse,
```

2021-06-01 01:08 UTC, rvpasari commented on erpnext/stock/doctype/product_recall/product_recall.py
> +				"recall_from" : "Customer",
```suggestion
				"recall_from": "Customer",
```

2021-06-01 01:08 UTC, rvpasari commented on erpnext/stock/doctype/product_recall/product_recall.py
> +				"recall_warehouse" : self.recall_warehouse,
```suggestion
				"recall_warehouse": self.recall_warehouse,
```

2021-06-02 05:12 UTC, sahil28297 requested changes

2021-06-02 05:12 UTC, sahil28297 commented on erpnext/stock/doctype/product_recall/product_recall.py
> +			sle_list.pop(0)
You should never change the list on which you are currently iterating on, create a separate list and pop it from there if you want to use the updated list further.

2021-06-02 05:12 UTC, sahil28297 commented on erpnext/stock/doctype/product_recall/product_recall.py
> +		prn_doc_list = ["""<a href="#Form/Product Recall Notice/{0}">{1}</a>""".format(m.name, m.name) for m in prn_doc_list]
```suggestion
		prn_doc_list = ["""<a href="#Form/Product Recall Notice/{0}">{0}</a>""".format(m.name) for m in prn_doc_list]
```

2021-06-02 05:12 UTC, sahil28297 commented on erpnext/stock/doctype/product_recall_notice/product_recall_notice.py
> +	stock_entry_doc.save()
```suggestion
	stock_entry_doc.save(ignore_permissions=True)
```

2021-06-02 13:35 UTC, MyuddinKhatri commented on erpnext/stock/doctype/product_recall/product_recall.py
> +			sle_list.pop(0)
Will be pairing up with @vishdha  to have a look at the alternate solution for this

2021-06-03 08:12 UTC, sahil28297 approved these changes, later dismissed

2021-06-03 08:25 UTC, hrwX approved these changes

2021-06-03 08:36 UTC, sahil28297 approved these changes

2021-06-03 08:36 UTC, merged