feat: added produced qty field in material request plan item
DigiThinkIT/erpnext pull request #1341
Opened 2021-06-01 09:02 UTC by MyuddinKhatri

Ref: [Asana](https://app.asana.com/0/1192407896547052/1200009659795579)

![screenshot-bloomstack_demo_8000-2021 06 01-14_31_23](https://user-images.githubusercontent.com/53251406/120296914-39a03780-c2e6-11eb-94e2-1b8ba9c1a850.jpg)

2021-06-01 09:18 UTC, rvpasari commented on erpnext/manufacturing/doctype/production_plan/production_plan.py
> +		# calculate produced_percentage on the basis on requested_qty and produced_qty
Good boy.

2021-06-01 09:19 UTC, rvpasari requested changes

2021-06-01 09:19 UTC, rvpasari commented on erpnext/manufacturing/doctype/production_plan/production_plan.py
> +				produced_percentage = (mr_item.requested_qty / mr_item.produced_qty) * 100
```suggestion
				produced_percentage = (flt(mr_item.requested_qty) / flt(mr_item.produced_qty)) * 100
```

2021-06-01 09:32 UTC, rvpasari approved these changes

2021-06-01 14:07 UTC, rvpasari approved these changes, later dismissed

2021-06-02 04:50 UTC, sahil28297 requested changes

2021-06-02 04:50 UTC, sahil28297 commented on erpnext/manufacturing/doctype/production_plan/production_plan.py
> +				mr_item.produced_percentage = produced_percentage
```suggestion
				mr_item.produced_percentage = (flt(mr_item.requested_qty) / flt(mr_item.produced_qty)) * 100
```

2021-06-02 04:51 UTC, sahil28297 approved these changes

2021-06-02 05:19 UTC, merged