fix: restricted creation of muliple stock entries against single product recall notice
DigiThinkIT/erpnext pull request #1374
Opened 2021-06-09 08:42 UTC by MyuddinKhatri

Ref: [Asana](https://app.asana.com/0/1192407896547052/1200426337727461)

2021-06-14 06:07 UTC, sahil28297 approved these changes, later dismissed

2021-06-14 10:11 UTC, hrwX commented on erpnext/stock/doctype/stock_entry_detail/stock_entry_detail.json
> +   "hidden": 1,
- Any reason for hiding this ?

2021-06-14 15:13 UTC, rvpasari requested changes

2021-06-14 15:13 UTC, rvpasari commented on erpnext/stock/doctype/product_recall_notice/product_recall_notice.py
> +		if item.get("qty") != item.get("received_qty"):
@MyuddinKhatri where are the comments? Also, why is this being merged into may-sprint-2?

2021-06-14 15:16 UTC, rvpasari requested changes

2021-06-14 15:16 UTC, rvpasari commented on erpnext/stock/doctype/product_recall_notice/product_recall_notice.py
> +			if se_item.product_recall_notice_item:
use .get()

2021-06-17 05:34 UTC, sahil28297 approved these changes

2021-06-17 05:34 UTC, merged