fix: added ompany filter to Stock Entry's Package tag
DigiThinkIT/erpnext pull request #1377
Opened 2021-06-10 12:55 UTC by nehasacher143

Task: https://app.asana.com/0/1188592895233593/1200283340859497/f

2021-06-11 04:02 UTC, hrwX requested changes

2021-06-11 04:02 UTC, hrwX commented on erpnext/stock/doctype/stock_entry/stock_entry.js
> +			filters["company"] = frm.doc.company
```suggestion
			if (frm.doc.company) {
				filters["company"] = frm.doc.company
			}
```

2021-06-11 05:48 UTC, sahil28297 approved these changes, later dismissed

2021-06-11 05:48 UTC, sahil28297 commented
@nehasacher143 fix sider issues

2021-06-14 04:23 UTC, hrwX approved these changes

2021-06-14 04:25 UTC, rvpasari approved these changes

2021-06-14 05:55 UTC, sahil28297 approved these changes

2021-06-14 05:55 UTC, merged