fix: add quantity field while moving from batch
DigiThinkIT/erpnext pull request #1389
Opened 2021-06-17 09:12 UTC by pritishsal

2021-06-17 09:38 UTC, hrwX requested changes

2021-06-17 09:38 UTC, hrwX commented on erpnext/stock/doctype/batch/batch.js
> +								fieldname: 'moveQty',
```suggestion
								fieldname: 'qty',
```

2021-06-17 09:38 UTC, hrwX commented on erpnext/stock/doctype/batch/batch.js
> +								'default': $btn.attr('data-qty')
```suggestion
								default: $btn.attr('data-qty')
```

2021-06-17 09:38 UTC, hrwX commented on erpnext/stock/doctype/batch/batch.js
> +										// $btn.attr('data-qty'),
```suggestion
										qty: data.qty,
```

2021-06-18 04:34 UTC, hrwX approved these changes

2021-06-18 05:09 UTC, sahil28297 approved these changes

2021-06-18 05:09 UTC, merged