fix(work_order): Add item name in Work Order
DigiThinkIT/erpnext pull request #139
Opened 2019-02-04 12:29 UTC by Alchez

**Refs:**

- https://corp.bloomstack.garden/desk#Form/Issue/ISS-2019-00009
- https://github.com/DigiThinkIT/delta9/pull/96

<hr>

**Patch:**

![image](https://user-images.githubusercontent.com/13396535/52208359-59ee9180-28a6-11e9-9e87-77efc5bda618.png)

**Form View:**

![image](https://user-images.githubusercontent.com/13396535/52205561-72a67980-289d-11e9-824c-0991fa2d9c10.png)

2019-02-05 09:46 UTC, vjFaLk requested changes

2019-02-05 09:46 UTC, vjFaLk commented on erpnext/manufacturing/doctype/work_order/work_order.json
>  {
Pls fix

2019-02-05 10:29 UTC, Alchez commented on erpnext/manufacturing/doctype/work_order/work_order.json
>  {
The spaces are actually ERPNext convention (don't ask), so this is actually a fix. :man_facepalming:

2019-02-08 09:54 UTC, vjFaLk commented
Fix conflict and make to upstream

2019-02-08 10:07 UTC, Alchez commented
Made upstream at https://github.com/frappe/erpnext/pull/16608.

2019-02-08 10:43 UTC, merged