fix: filtered the columns in report and add the filters
DigiThinkIT/erpnext pull request #1395
Opened 2021-06-22 17:31 UTC by harshmule-git

Asana Task Link:

https://app.asana.com/0/1200471303892628/1200402551564283/f

2021-06-22 17:35 UTC, rvpasari requested changes

2021-06-22 17:35 UTC, rvpasari commented on erpnext/stock/report/ordered_items_to_be_delivered/ordered_items_to_be_delivered.js
> +            "fieldtype": "Data",
change to link field

2021-06-22 17:35 UTC, rvpasari commented on erpnext/stock/report/ordered_items_to_be_delivered/ordered_items_to_be_delivered.js
> +            "fieldtype": "Data",
link field

2021-06-22 17:36 UTC, rvpasari commented
@harshmule-git ensure to post a screenshot of how the old report looked like, and how a new report looks like

2021-06-30 05:45 UTC, sahil28297 commented
@harshmule-git why is this in Draft state? Also fix sider issues.

2021-06-30 08:09 UTC, harshmule-git commented
hey @sahil28297 actually working on finding a fix for filter queries which is creating a blocker on the report!

2021-07-07 04:34 UTC, hrwX commented
@harshmule-git Whats the status of this PR ?

2021-07-07 04:42 UTC, harshmule-git commented
hey @hrwX we'll be closing this PR after today's discussion, as we have to create a new report!

2021-07-10 12:34 UTC, closed without merging

2021-07-10 12:34 UTC, harshmule-git commented
@rvpasari as discussed, closed this PR!