fix: Move the code from bloomstack_core to erpnext for work order
DigiThinkIT/erpnext pull request #1396
Opened 2021-06-22 20:54 UTC by shruti2323

Fix Description: Moved the code from bloomstack_core to erpnext.
Asana Link: https://app.asana.com/0/1200073273462988/1200278560808264

2021-06-22 20:56 UTC, shruti2323 commented on erpnext/manufacturing/doctype/work_order/work_order.js
> +		// get meta information of doctype Work Order Operation
Code shuffled from app bloomstack_core work_order.js to erpnext.

2021-06-22 21:01 UTC, shruti2323 commented on erpnext/manufacturing/doctype/work_order/work_order.json
> +  "title",
Below is the Image attached for Work Order custom form fields and Doctype field difference, where "Title" was the custom field which added to Work Order doctype fields.

https://user-images.githubusercontent.com/80836439/122998481-ba74bf80-d3ca-11eb-9d81-12e0a73d0470.mp4

![Work_order_before](https://user-images.githubusercontent.com/80836439/122998679-f871e380-d3ca-11eb-8a42-dcd1bff6d5ae.PNG)
![Work_order_before1](https://user-images.githubusercontent.com/80836439/122998691-fc056a80-d3ca-11eb-9710-84e2275d0fe8.PNG)

2021-06-25 06:25 UTC, vishdha requested changes

2021-06-25 06:25 UTC, vishdha commented on erpnext/manufacturing/doctype/work_order/work_order.js
>  	},
```suggestion
	
```
you directly add this indicator color and condition in work_order_list.js

2021-06-25 08:05 UTC, shruti2323 commented on erpnext/manufacturing/doctype/work_order/work_order_list.js
> +frappe.ui.form.on("Work Order", {
Suggested Change: you directly add this indicator color and condition in work_order_list.js

2021-06-30 05:51 UTC, vishdha requested changes
@shruti2323  can you update the pr. request changes is not here. work_order_list.js missing and outdated code still in pr

2021-06-30 06:26 UTC, shruti2323 commented
> @shruti2323 can you update the pr. request changes is not here. work_order_list.js missing and outdated code still in pr

2021-06-30 06:26 UTC, closed without merging

2021-06-30 10:31 UTC, shruti2323 commented
> @shruti2323 can you update the pr. request changes is not here. work_order_list.js missing and outdated code still in pr



> @shruti2323 can you update the pr. request changes is not here. work_order_list.js missing and outdated code still in pr
Hello @vishdha, 
since the "operation" is a child table for the work order.
adding a logic inside work_order_list.js would not suffice.
frappe.listview_settings would work for all DocTypes except Child Tables and Single DocTypes.
and we are adding this logic under work_order.js to trigger once the form is getting created.

As per your suggestion, moving logic to work_order_list will not work because the return would trigger to doc, not to the child table.

![image](https://user-images.githubusercontent.com/80836439/123945562-eb9d5300-d9bb-11eb-887d-d132d139c409.png)