feat: sync bank transaction from bank reconciliation feat added
DigiThinkIT/erpnext pull request #1416
Opened 2021-06-30 10:00 UTC by vishdha

2021-06-30 10:28 UTC, hrwX requested changes, later dismissed

2021-06-30 10:28 UTC, hrwX commented on erpnext/accounts/doctype/bank_reconciliation_tool/bank_reconciliation_tool.js
> +		frappe.db.get_value("Bank Account", cur_frm.doc.bank_account, "bank", (r) => {
Why cur_frm ?

2021-07-02 07:01 UTC, sahil28297 approved these changes

2021-07-02 07:01 UTC, sahil28297 commented
@vishdha fix sider issues

2021-07-07 04:38 UTC, hrwX approved these changes

2021-07-07 04:39 UTC, hrwX commented
@vishdha Fix sider issues.

2021-07-07 06:23 UTC, sahil28297 approved these changes

2021-07-07 06:23 UTC, merged