chore: add domain for cannabis in the system
DigiThinkIT/erpnext pull request #1433
Opened 2021-07-11 17:09 UTC by harshmule-git

**Purpose:**
* To add domain for Cannabis in the system.

**Asana Task Link:**

https://app.asana.com/0/1200497651535074/1200483767482371/f

2021-07-12 06:37 UTC, rvpasari commented
@harshmule-git you'll have to add the domain to the domain list as well

2021-07-12 09:18 UTC, harshmule-git commented
> @harshmule-git you'll have to add the domain to the domain list as well

Hey @rvpasari to add it in the domain list we created a patch, i think that will fulfill the requirement!

2021-07-13 06:24 UTC, hrwX requested changes

2021-07-13 06:24 UTC, hrwX commented on erpnext/setup/setup_wizard/operations/install_fixtures.py
> +		{'doctype': 'Domain', 'domain': 'Cannabis'},
- Are we not moving Cannabis related fields to custom fields ??
- eg: If I am not a cannabis user, I dont want to see Package Tag field anywhere

2021-07-13 07:19 UTC, sahil28297 commented on erpnext/setup/setup_wizard/operations/install_fixtures.py
> +		{'doctype': 'Domain', 'domain': 'Cannabis'},
As discussed in the product tea meet, we'll first add the domain, make reports based on the domain and in the meanwhile, we'll plan on moving existing fields to the domain.

2021-07-13 07:20 UTC, sahil28297 approved these changes

2021-07-13 07:20 UTC, merged