feat: Reconciled data table added in bank reconciliation tool
DigiThinkIT/erpnext pull request #1435
Opened 2021-07-12 09:39 UTC by vishdha

TASK ID: https://app.asana.com/0/1192407894480744/1200483480709848

2021-07-13 10:57 UTC, hrwX requested changes, later dismissed

2021-07-13 10:57 UTC, hrwX commented on erpnext/accounts/doctype/bank_reconciliation_tool/bank_reconciliation_tool.py
> +	filters.append(['allocated_amount', '>', 0])
```suggestion
	filters = [
		['bank_account', '=', bank_account],
		['docstatus', '=', 1],
		['allocated_amount', '>', 0]
	]
```

2021-07-13 10:57 UTC, hrwX commented on erpnext/accounts/doctype/bank_transaction/bank_transaction.py
> +		payment_entries_references = self.payment_entries_references or ""
```suggestion
		payment_entries_references = self.payment_entries_references.split(",") if self.payment_entries_references else []
```

2021-07-13 10:57 UTC, hrwX commented on erpnext/accounts/doctype/bank_transaction/bank_transaction.py
> +		frappe.db.set_value(self.doctype, self.name, "payment_entries_references", payment_entries_references)
```suggestion
		frappe.db.set_value(self.doctype, self.name, "payment_entries_references", ", ".join(payment_entries_references))
```

2021-07-13 10:57 UTC, hrwX commented on erpnext/accounts/doctype/bank_transaction/bank_transaction.py
> +		frappe.db.set_value(self.doctype, self.name, "payment_entries_references", payment_entries_references)
```suggestion
		frappe.db.set_value(self.doctype, self.name, "payment_entries_references", ", ".join(payment_entries_references))
```

2021-07-13 10:57 UTC, hrwX commented on erpnext/accounts/doctype/bank_transaction/bank_transaction.py
> +		frappe.db.set_value(self.doctype, self.name, "payment_entries_references", payment_entries_references)
```suggestion
		frappe.db.set_value(self.doctype, self.name, "payment_entries_references", ",".join(payment_entries_references))
```

2021-07-13 10:57 UTC, hrwX commented on erpnext/public/js/bank_reconciliation_tool/data_table_manager.js
> +		// );
```suggestion

```

2021-07-14 05:45 UTC, sahil28297 approved these changes

2021-07-14 06:23 UTC, merged