fix: create events on custom button click
DigiThinkIT/erpnext pull request #1445
Opened 2021-07-16 13:43 UTC by hrwX

> Please provide enough information so that others can review your pull request:

> Explain the **details** for making this change. What existing problem does the pull request solve?

> Screenshots/GIFs

2021-07-16 13:51 UTC, sahil28297 submitted a review, later dismissed

2021-07-19 06:25 UTC, vishdha requested changes

2021-07-19 06:25 UTC, vishdha commented on erpnext/hr/doctype/holiday_list/holiday_list.js
> +						console.log(r)
```suggestion
```
Remove Console log

2021-07-19 11:36 UTC, sahil28297 approved these changes

2021-07-19 11:36 UTC, merged