fix: removed event for contract
DigiThinkIT/erpnext pull request #1447
Opened 2021-07-19 11:38 UTC by vishdha

TASK ID: [ASANA](https://app.asana.com/0/1200595970312551/1200018129970471)

2021-07-19 12:49 UTC, hrwX requested changes

2021-07-19 12:49 UTC, hrwX commented on erpnext/crm/doctype/contract/contract.json
> +   "options": "Company:company:default_currency"
- Rebase the PR to `bs-jul-sprint-2`

2021-07-20 04:05 UTC, vishdha commented on erpnext/crm/doctype/contract/contract.json
> +   "options": "Company:company:default_currency"
already rebased with bs-jul-sprint-2

2021-07-20 04:08 UTC, hrwX approved these changes

2021-07-22 11:01 UTC, sahil28297 approved these changes

2021-07-22 11:01 UTC, merged