chore: Taxjar signup button
DigiThinkIT/erpnext pull request #1449
Opened 2021-07-19 14:15 UTC by shantanu-kadam-epi

Asana link : https://app.asana.com/0/1200595970312551/1200571214737045

![image](https://user-images.githubusercontent.com/60215482/126174316-a235e975-5657-43cd-9c67-cf4b4cb73ea4.png)

2021-07-20 04:13 UTC, vishdha requested changes

2021-07-20 04:13 UTC, vishdha commented on erpnext/erpnext_integrations/doctype/taxjar_settings/taxjar_settings.js
> +			var myWin = window.open('https://app.taxjar.com/api_sign_up');
```suggestion
			window.open('https://app.taxjar.com/api_sign_up');
```

2021-07-20 04:14 UTC, vishdha requested changes

2021-07-20 04:14 UTC, vishdha commented on erpnext/erpnext_integrations/doctype/taxjar_settings/taxjar_settings.js
> +    frm.add_custom_button("Sign Up For Taxjar", function(){
```suggestion
frappe.ui.form.on("TaxJar Settings", "refresh", function(frm) {
    frm.add_custom_button("Sign Up For Taxjar", function() {
```

2021-07-20 05:24 UTC, vishdha approved these changes

2021-07-22 10:59 UTC, sahil28297 commented
@vishdha why are we adding a signup button in our product?

2021-07-22 12:07 UTC, vishdha commented
@sahil28297 https://developers.taxjar.com/integrations/certification-checklist/

2021-07-23 05:34 UTC, sahil28297 approved these changes

2021-07-23 05:34 UTC, merged