feat: unique account head added for each bank account
DigiThinkIT/erpnext pull request #1452
Opened 2021-07-20 10:14 UTC by vishdha

TASK ID: [ASANA](https://app.asana.com/0/1192407894480744/1200608072172230)

Gif:
![Peek 2021-07-20 15-42](https://user-images.githubusercontent.com/6947417/126307128-c7e1a1f4-e966-47aa-a93e-a223dddddb40.gif)

2021-07-22 13:35 UTC, hrwX requested changes, later dismissed

2021-07-22 13:35 UTC, hrwX commented on erpnext/erpnext_integrations/doctype/plaid_settings/plaid_settings.py
> +	new_account_head=frappe.get_doc({
```suggestion
	new_account_head = frappe.get_doc({
```

2021-07-22 13:35 UTC, hrwX commented on erpnext/erpnext_integrations/doctype/plaid_settings/plaid_settings.py
> +		})
```suggestion
	})
```

2021-07-27 05:18 UTC, hrwX approved these changes

2021-07-28 06:34 UTC, sahil28297 approved these changes

2021-07-28 06:34 UTC, merged