chore: taxjar add api version
DigiThinkIT/erpnext pull request #1453
Opened 2021-07-20 14:10 UTC by shantanu-kadam-epi

Asana link: https://app.asana.com/0/1200595970312551/1200571032531975

![image](https://user-images.githubusercontent.com/60215482/126338732-2a502a8b-d28b-4ea6-b0a5-efd884947bc6.png)

2021-07-20 16:57 UTC, vishdha approved these changes, later dismissed

2021-07-22 10:48 UTC, sahil28297 approved these changes

2021-07-22 10:48 UTC, sahil28297 commented
@shantanu-kadam-epi fix sider issues

2021-07-22 10:49 UTC, sahil28297 requested changes

2021-07-22 10:49 UTC, sahil28297 commented on erpnext/erpnext_integrations/taxjar_integration.py
> +		client =  taxjar.Client(api_key=api_key, api_url=api_url)
```suggestion
		client = taxjar.Client(api_key=api_key, api_url=api_url)
```

2021-07-22 10:49 UTC, merged