fix: fixed the issue once completed cannot change status
DigiThinkIT/erpnext pull request #1458
Opened 2021-07-22 11:25 UTC by vishdha

TASK ID: [ASANA](https://app.asana.com/0/1200595970312551/1200564303948578)

![Peek 2021-07-22 16-55](https://user-images.githubusercontent.com/6947417/126631997-575135fb-6df2-48f1-bc2f-272cf6fe7123.gif)

2021-07-22 13:27 UTC, hrwX submitted a review, later dismissed

2021-07-23 05:24 UTC, sahil28297 requested changes

2021-07-23 05:24 UTC, sahil28297 commented on erpnext/projects/doctype/task/task.py
> +			self.progress = 0
Why are we setting the progress as 0 if the task is incomplete, intermediate values are not allowed? Also we are removing the auto setting of status if progress is 100%

2021-07-26 04:50 UTC, hrwX submitted a review, later dismissed

2021-07-27 03:28 UTC, sahil28297 requested changes

2021-07-27 03:28 UTC, sahil28297 commented on erpnext/projects/doctype/task/task.py
> +			frappe.throw(_("Task progress cannot be set 100% untill status is not set as Completed"))
```suggestion
			frappe.throw(_("Task progress cannot be set 100% until status is not set as Completed"))
```

2021-07-27 03:28 UTC, sahil28297 approved these changes

2021-07-27 03:28 UTC, merged