chore: taxjar added nexus address
DigiThinkIT/erpnext pull request #1459
Opened 2021-07-25 08:19 UTC by shantanu-kadam-epi

Asana link : https://app.asana.com/0/1200595970312551/1200571032531985

![image](https://user-images.githubusercontent.com/60215482/126892556-5764e099-f95a-4228-9f04-07bdfaf6b4b6.png)

2021-07-26 05:09 UTC, hrwX requested changes

2021-07-26 05:09 UTC, hrwX commented on erpnext/erpnext_integrations/taxjar_integration.py
> +    }]
```suggestion
	tax_dict['nexus_address'] = [{
		'id': doc.company_address,
		'country': tax_dict.get("from_country"),
		'zip': tax_dict.get("from_zip"),
		'state': tax_dict.get("from_state"),
		'city': tax_dict.get("from_city"),
		'street': tax_dict.get("from_street")
	}]
```

2021-07-27 05:27 UTC, hrwX approved these changes, later dismissed

2021-07-29 06:36 UTC, sahil28297 commented
@shantanu-kadam-epi resolve the conflicts

2021-07-29 07:03 UTC, sahil28297 approved these changes

2021-07-29 07:04 UTC, merged