fix(quality_inspection): Fix tests for Quality Inspection
DigiThinkIT/erpnext pull request #147
Opened 2019-02-11 14:01 UTC by Alchez

Please read the pull request checklist to make sure your changes are merged: https://github.com/frappe/erpnext/wiki/Pull-Request-Checklist

2019-02-12 10:08 UTC, vjFaLk requested changes

2019-02-12 10:08 UTC, vjFaLk commented on erpnext/stock/doctype/quality_inspection/quality_inspection.json
> +   "options": "\nNew\nAccepted\nRejected\nPartially Rejected\nSkipped",
"Untested" instead of "New"

2019-02-12 10:08 UTC, vjFaLk commented on erpnext/stock/doctype/quality_inspection/quality_inspection_list.js
> +		} else if (in_list(["New", "Partially Rejected"], doc.status)) {
"Red" instead of "Orange"

2019-02-14 07:06 UTC, Alchez commented on erpnext/stock/doctype/quality_inspection/quality_inspection.json
> +   "options": "\nNew\nAccepted\nRejected\nPartially Rejected\nSkipped",
Updated

2019-02-14 07:06 UTC, Alchez commented on erpnext/stock/doctype/quality_inspection/quality_inspection_list.js
> +		} else if (in_list(["New", "Partially Rejected"], doc.status)) {
Updated

2019-02-14 09:29 UTC, vjFaLk commented
Let's make the whole feature upstream as well

2019-02-14 09:46 UTC, Alchez commented
That's a whole nother deal. Since they also made some QI/QA changes to core. Merge this for now, so atleast our tests pass.

2019-02-14 09:58 UTC, merged