Added sidebar and fixed color text as per DOD
DigiThinkIT/erpnext pull request #1474
Opened 2021-08-03 13:59 UTC by meshramsaroj

**Task Link:** https://app.asana.com/0/0/1200711512519955/f

**Gif:**
![fix-text-color-with-sidbar](https://user-images.githubusercontent.com/53329367/128028543-2774fa3b-3531-4354-89bf-045742a8a513.gif)

2021-08-04 04:55 UTC, hrwX requested changes

2021-08-04 04:55 UTC, hrwX commented on erpnext/www/lms/course.html
> +		color: #d1d8dd;
- Use brand primary colour
- Not sticking to the default colour palette will result into bad UX

2021-08-04 12:03 UTC, nehasacher143 commented
@meshramsaroj Please add a mobile view GIF as well

2021-08-04 13:33 UTC, meshramsaroj commented
> @meshramsaroj Please add a mobile view GIF/Screenshot as well

currently, I'm only working on desktop view. so there is no mobile view for now

2021-08-06 10:28 UTC, meshramsaroj commented
I am closing this PR and creating a new PR with sorted code
@neilLasrado  @nehasacher143

2021-08-06 10:28 UTC, closed without merging