fix: fixed the serial number issue for customer
DigiThinkIT/erpnext pull request #1491
Opened 2021-08-05 14:35 UTC by nehasacher143

Task: https://app.asana.com/0/1199639423748061/1200681044211594/f

GIF:
![Peek 2021-08-05 20-05](https://user-images.githubusercontent.com/45919049/128368367-3556f4dd-b46e-4627-8d7a-bb2a7cc07ed4.gif)

2021-08-06 04:57 UTC, hrwX requested changes

2021-08-06 04:57 UTC, hrwX commented on erpnext/support/doctype/warranty_claim/warranty_claim.js
> -		frm.add_fetch('serial_no', 'customer', 'customer');
- Why change something in erpnext when you can always override it via custom app ??

2021-08-06 17:01 UTC, hrwX requested changes

2021-08-06 17:01 UTC, hrwX commented on erpnext/support/doctype/warranty_claim/warranty_claim.js
> +					frm.set_value(res.message)
```suggestion
					for (let key in res.message) {
						frm.set_value(key, res.message[key]);
					}
```

2021-08-06 17:01 UTC, hrwX commented on erpnext/support/doctype/warranty_claim/warranty_claim.js
> +		frm.set_query('serial_no',() => {
```suggestion
		frm.set_query('serial_no', () => {
```

2021-08-06 17:01 UTC, hrwX commented on erpnext/support/doctype/warranty_claim/warranty_claim.js
> +		})
```suggestion
		});
```

2021-08-09 06:12 UTC, sahil28297 commented
@nehasacher143 please update your PR with the requested changes and also resolve sider issues.

2021-08-09 14:54 UTC, sahil28297 requested changes

2021-08-09 14:54 UTC, sahil28297 commented on erpnext/support/doctype/warranty_claim/warranty_claim.py
> +	doc= frappe.get_doc("Serial No", serial_no)
```suggestion
	doc = frappe.get_doc("Serial No", serial_no)
```

2021-08-09 14:54 UTC, sahil28297 approved these changes

2021-08-09 14:55 UTC, merged