fix: fixed set sales_tax_exempted to 0 for Quotation for Lead
DigiThinkIT/erpnext pull request #1503
Opened 2021-08-11 07:53 UTC by MyuddinKhatri

2021-08-11 07:58 UTC, MyuddinKhatri commented
@neilLasrado please look into this.

2021-08-12 09:28 UTC, neilLasrado requested changes

2021-08-12 09:28 UTC, neilLasrado commented on erpnext/erpnext_integrations/taxjar_integration.py
> +		sales_tax_exempted = 0
check if hasattr(doc, "exempt_from_sales_tax") and doc.exempt_from_sales_tax is true then set sales_tax_exempted as 1

2021-08-12 09:28 UTC, neilLasrado commented on erpnext/erpnext_integrations/taxjar_integration.py
> +		sales_tax_exempted = 0
exempt_from_sales_tax can be set as true even for a Lead.

2021-08-13 04:44 UTC, sahil28297 submitted a review, later dismissed

2021-08-13 04:46 UTC, sahil28297 approved these changes

2021-08-13 04:47 UTC, merged