chore: Added the fix to resolve test case test_outstanding_amount_after_advance_payment_entry_cancelation
DigiThinkIT/erpnext pull request #1532
Opened 2021-08-24 21:28 UTC by shruti2323

Test case for test_outstanding_amount_after_advance_payment_entry_cancelation  is now succeed.
Kindly refer to 
![testcase_sales_invoice_test_outstanding_amount_after_advance_payment_entry_cancelation1](https://user-images.githubusercontent.com/80836439/130692457-1054e02d-825e-4790-8674-959ee192919c.PNG)
the below image.

2021-08-24 21:31 UTC, shruti2323 commented on erpnext/accounts/doctype/payment_entry/payment_entry.py
>  						self.base_total_allocated_amount) / self.source_exchange_rate
The test case was failing due to the mathematical calculation of the 
![testcase_sales_invoice_test_outstanding_amount_after_advance_payment_entry_cancelation](https://user-images.githubusercontent.com/80836439/130692777-f06ce661-226c-497a-bd7d-cb9e3e15c5a7.png)
NoneType operand. Please refer to below image.

2021-08-25 05:20 UTC, sahil28297 requested changes

2021-08-25 05:20 UTC, sahil28297 commented on erpnext/accounts/doctype/payment_entry/payment_entry.py
> +
This is over intended by 1 tab, fix the indentation for rest of this function as well

2021-08-25 14:18 UTC, sahil28297 commented
@shruti2323 fix the other lines for that function as well

2021-08-26 10:45 UTC, sahil28297 approved these changes

2021-08-26 10:58 UTC, merged