chore: added company field in erpnext
DigiThinkIT/erpnext pull request #1569
Opened 2021-08-31 13:44 UTC by shruti2323

Task link: https://bloomstack.com/desk#Form/Task/TASK-2021-00247

Bloomstack Core link : https://github.com/Bloomstack/bloomstack_core/pull/628

**Before : **
![Compliance_before](https://user-images.githubusercontent.com/80836439/131512682-a79bc605-9992-4c93-8444-b32e92852225.png)

**After : **
![Uploading Compliance_after.PNG…]()

2021-09-01 12:45 UTC, sahil28297 requested changes

2021-09-01 12:45 UTC, sahil28297 commented on erpnext/compliance/doctype/compliance_info/compliance_info.json
> +   "fieldname": "section_break_2",
```suggestion
   "fieldname": "section_break_1",
```

2021-09-01 15:12 UTC, shruti2323 commented on erpnext/compliance/doctype/compliance_info/compliance_info.json
> +   "fieldname": "section_break_2",
Made correction to the field name

2021-09-02 07:49 UTC, sahil28297 approved these changes

2021-09-02 07:50 UTC, merged