fix quotation.json
DigiThinkIT/erpnext pull request #1594
Opened 2021-09-02 11:24 UTC by meshramsaroj

**Task Link:** https://bloomstack.com/desk#Form/Task/TASK-2021-00249

**Issue:** bloomstack_core/bloomstack_core/bloomstack_core/custom/quotation.json

**Description:** Moved required field of quotation doctype from bloomstack core to erpnext and also deleted quotation.json from bloomstack_core

**Deleted file PR link:** https://github.com/Bloomstack/bloomstack_core/pull/647

**Screenshot:**

- Before

1. In ERPNext
![image](https://user-images.githubusercontent.com/53329367/131834694-9958a152-ff96-4da1-b444-4b0cf2bdef0c.png)

2. In Bloomstack core
![image](https://user-images.githubusercontent.com/53329367/131834707-b229d134-fdd5-4116-9a16-3d5b91019270.png)

- After
1. In ERPNext
![image](https://user-images.githubusercontent.com/53329367/131834787-bb8047cb-5297-48a8-8fb8-6d46ad490576.png)

2. In Bloomstack core
![image](https://user-images.githubusercontent.com/53329367/131834716-8a2e485a-f88a-40a3-a405-ac80c42200af.png)

2021-09-06 06:45 UTC, sahil28297 requested changes
customer_signature and signature fields are missing

2021-09-07 08:27 UTC, meshramsaroj commented on erpnext/selling/doctype/quotation/quotation.json
>    "signature",
@sahil28297
signature is already there, I have added the customer signature field.
Please check

2021-09-07 13:44 UTC, sahil28297 requested changes

2021-09-07 13:44 UTC, sahil28297 commented on erpnext/selling/doctype/quotation/quotation.json
> +   "label": "Customer Signature"
"read_only": 1, "print_hide": 1,

2021-09-08 05:49 UTC, meshramsaroj commented on erpnext/selling/doctype/quotation/quotation.json
> +   "label": "Customer Signature"
added required changes

2021-09-08 06:19 UTC, sahil28297 approved these changes

2021-09-08 06:20 UTC, merged