chore: rename project field to default_project
DigiThinkIT/erpnext pull request #1599
Opened 2021-09-02 12:23 UTC by shruti2323

Task Link : https://bloomstack.com/desk#Form/Task/TASK-2021-00231

**Before :**
![Default_project_before](https://user-images.githubusercontent.com/80836439/131842733-276caff8-ecf8-4c04-a6a3-69ba0e363877.png)
![Default_project_task_before](https://user-images.githubusercontent.com/80836439/131842740-6ae0fcf3-bc56-4e64-a693-bff589f23950.png)

**After :**
![Default_project_task_after](https://user-images.githubusercontent.com/80836439/131842771-0abe25bd-8bfc-4932-8ef8-ada7da0f7134.png)

2021-09-06 11:04 UTC, sahil28297 requested changes
@shruti2323 Please do a global search on the word `project` and then do the necessary changes, chenges are to be done in all the files where `task.project` is referenced. These are the changes I found.
erpnext/erpnext/projects/doctype/task/task.js line 8, 36, 50, 69, 70, 73, 74, 75
erpnext/erpnext/hr/doctype/employee_onboarding/employee_onboarding.js line 31
erpnext/erpnext/hr/doctype/employee_onboarding/test_employee_onboarding.py line 42, 77
erpnext/erpnext/hr/doctype/employee_separation/employee_separation.js line 23
erpnext/erpnext/hr/doctype/expense_claim/expense_claim.py line 40
erpnext/erpnext/projects/utils.py line 66
erpnext/erpnext/projects/doctype/project/project.py line 40, 57, 385
erpnext/erpnext/projects/doctype/project/test_project.py line 22
erpnext/erpnext/projects/doctype/task/test_task.py line 36, 40, 148
erpnext/erpnext/projects/doctype/timesheet/timesheet.py
erpnext/erpnext/projects/web_form/tasks/tasks.py
erpnext/erpnext/templates/pages/projects.py

2021-09-08 09:07 UTC, shruti2323 commented on erpnext/projects/web_form/tasks/tasks.py
> +	elif context.doc and context.doc.get('default_project'):
Under **context.doc.get('default_project')** we are getting correct project name
![context_project](https://user-images.githubusercontent.com/80836439/132480790-a291b3ec-f1d3-4080-8df5-62f963f24f8b.PNG)

2021-09-13 09:10 UTC, sahil28297 approved these changes

2021-09-15 12:26 UTC, neilLasrado requested changes, later dismissed

2021-09-15 12:26 UTC, neilLasrado commented on erpnext/agriculture/utils.py
> +			"default_project": project_name
This should add the project to the child table and mark it as default

2021-09-15 12:26 UTC, neilLasrado commented on erpnext/crm/doctype/contract/contract.py
> +				"default_project": project_name
This should add the project to the child table and mark it as default

2021-09-15 12:26 UTC, neilLasrado commented on erpnext/hr/doctype/employee_onboarding/employee_onboarding.js
> -				frappe.set_route('List', 'Task', {project: frm.doc.project});
this should not be changed, it should filter based on the child table.

2021-09-15 12:26 UTC, neilLasrado commented on erpnext/hr/doctype/employee_separation/employee_separation.js
> +				frappe.set_route('List', 'Task', {default_project: frm.doc.default_project});
this should not be changed, it should filter based on the child table.

2021-09-15 12:26 UTC, neilLasrado commented on erpnext/hr/utils.py
> +					"default_project": self.project,
This should add the project to the child table and mark it as default

2021-09-15 12:26 UTC, neilLasrado commented on erpnext/patches.txt
> +erpnext.patches.v13_0.rename_project_field_to_default_project
rename_project_field_to_default_project needs to be executed before add_default_project_into_project_details_child_table

2021-09-15 12:26 UTC, neilLasrado commented on erpnext/patches/v5_0/update_projects.py
> +				"default_project": m.parent,
don't change a v5 patch maybe @sahil28297 please confirm

2021-09-15 12:26 UTC, neilLasrado commented on erpnext/projects/doctype/project/project.py
> +					default_project = self.name,
set in child table and mark default

2021-09-15 12:26 UTC, neilLasrado commented on erpnext/projects/doctype/project/project.py
> +		new_task.default_project = project.name
set in child table and mark default

2021-09-15 12:26 UTC, neilLasrado commented on erpnext/projects/doctype/task/task.js
> +		frm.set_query("default_project", function () {
this set_query doesn't make sense as default project is read_only. Move this to the child table maybe?

2021-09-15 12:26 UTC, neilLasrado commented on erpnext/projects/doctype/task/task.js
> +			frm.toggle_display("default_project", 0);
this code should not be needed

2021-09-15 12:26 UTC, neilLasrado commented on erpnext/projects/doctype/task/task.js
> +		frm.doc.default_project && frappe.model.remove_from_locals("Default_Project",
@sahil28297 any idea what this does? (remove_from_locals)  also should Default_Project be Default Project??

2021-09-15 12:26 UTC, neilLasrado commented on erpnext/projects/doctype/task/task.js
> +	default_project: (frm) => {
will also have to add a JS trigger if a project is set as default on child table to ensure that this block of code runs

2021-09-15 12:26 UTC, neilLasrado commented on erpnext/projects/doctype/task/test_task.py
> +		task.default_project = project or "_Test Project"
This should add the project to the child table and mark it as default

2021-09-15 15:00 UTC, sahil28297 requested changes
@vishdha can you take this up?

2021-09-15 15:00 UTC, sahil28297 commented on erpnext/agriculture/utils.py
> +			"default_project": project_name
@vishdha I'm not sure if it happens now, but whenever we set a "default_project" directly, it should automatically insert it in the child table and mark it as default.

2021-09-15 15:00 UTC, sahil28297 commented on erpnext/hr/doctype/employee_onboarding/employee_onboarding.js
> -				frappe.set_route('List', 'Task', {project: frm.doc.project});
@vishdha can you look into this, i think you'll have to use `frappe.route_options` to filter based on child table

2021-09-15 15:00 UTC, sahil28297 commented on erpnext/patches.txt
> +erpnext.patches.v13_0.add_default_project_into_project_details_child_table
```suggestion
erpnext.patches.v13_0.rename_project_field_to_default_project
erpnext.patches.v13_0.add_default_project_into_project_details_child_table
```

2021-09-15 15:00 UTC, sahil28297 commented on erpnext/patches.txt
> +erpnext.patches.v13_0.rename_project_field_to_default_project
```suggestion
```

2021-09-15 15:00 UTC, sahil28297 commented on erpnext/patches/v5_0/update_projects.py
> +				"default_project": m.parent,
Its reloading the task doctype so in case it the patch executes (which it wont coz there's no old account), this will break, hence needed.

2021-09-15 15:00 UTC, sahil28297 commented on erpnext/projects/doctype/task/task.js
> +		frm.doc.default_project && frappe.model.remove_from_locals("Default_Project",
this removes it from the locals dict (cache)
```suggestion
		frm.doc.default_project && frappe.model.remove_from_locals("Default Project",
```

2021-09-16 08:46 UTC, neilLasrado commented on erpnext/agriculture/utils.py
> +			"default_project": project_name
It's going to be the other way round. This PR makes the project table mandatory - https://github.com/Bloomstack/erpnext/pull/1656

2021-09-16 08:46 UTC, neilLasrado commented on erpnext/agriculture/utils.py
> +			"default_project": project_name
the default_project is read-only

2021-09-16 08:47 UTC, neilLasrado commented on erpnext/projects/doctype/task/task.js
> +		frm.doc.default_project && frappe.model.remove_from_locals("Default_Project",
@vishdha can you test this?

2021-09-17 08:13 UTC, sahil28297 submitted a review, later dismissed

2021-09-17 08:13 UTC, sahil28297 commented on erpnext/projects/doctype/task/test_task.py
> +
```suggestion

```

2021-09-23 08:39 UTC, vishdha commented
@sahil28297 Added set route filter based on the child table.

2021-09-23 08:44 UTC, vishdha approved these changes, later dismissed

2021-09-23 08:44 UTC, vishdha commented on erpnext/hr/doctype/employee_onboarding/employee_onboarding.js
> -				frappe.set_route('List', 'Task', {project: frm.doc.project});
@neilLasrado  There is no need to filter based on child table. Because when you set the project in child table it set default project at parent level
tested and worked fine
@neilLasrado

2021-09-23 08:44 UTC, vishdha commented on erpnext/projects/doctype/task/task.js
> +	default_project: (frm) => {
yeah it worked

2021-09-30 04:44 UTC, vishdha commented
closing this. Rebased PR is here https://github.com/Bloomstack/erpnext/pull/1728

2021-09-30 04:44 UTC, closed without merging