Move: batch.js file from bloomstack_core into erpnext
DigiThinkIT/erpnext pull request #1618
Opened 2021-09-07 09:49 UTC by imdadhussain

2021-09-13 05:08 UTC, vishdha requested changes

2021-09-13 05:08 UTC, vishdha commented on erpnext/stock/doctype/batch/batch.js
> +						method: "bloomstack_core.utils.move_expired_batches",
@imdadhussain  Path should be correct

2021-09-15 13:27 UTC, sahil28297 requested changes

2021-09-15 13:27 UTC, sahil28297 commented on erpnext/utils.py
> +
```suggestion
```

2021-09-15 13:29 UTC, sahil28297 requested changes

2021-09-15 13:29 UTC, sahil28297 commented on erpnext/utils.py
> +	new_authorization_request.save()
```suggestion
	new_authorization_request.save()
```

2021-09-15 13:30 UTC, sahil28297 requested changes

2021-09-15 13:30 UTC, sahil28297 commented on erpnext/utils.py
> +	new_authorization_request.save()
```suggestion
	new_authorization_request.save()

```

2021-09-15 13:34 UTC, sahil28297 requested changes

2021-09-15 13:34 UTC, sahil28297 commented on erpnext/utils.py
> +	new_authorization_request.save()
revert this file change

2021-09-15 14:17 UTC, sahil28297 requested changes

2021-09-15 14:17 UTC, sahil28297 commented on erpnext/stock/doctype/batch/batch.js
> +
```suggestion
```

2021-09-15 14:17 UTC, sahil28297 commented on erpnext/stock/doctype/batch/batch.js
> +
```suggestion
```

2021-09-15 14:20 UTC, sahil28297 approved these changes

2021-09-15 14:26 UTC, merged