fix: move customer.py code to erpnext from bloomstack_core
DigiThinkIT/erpnext pull request #1624
Opened 2021-09-08 06:23 UTC by MyuddinKhatri

2021-09-08 06:30 UTC, vishdha requested changes
@MyuddinKhatri  I'm not able to see the account_opend_date field in custom. is that field move please check

2021-09-08 06:39 UTC, MyuddinKhatri commented
> @MyuddinKhatri I'm not able to see the account_opend_date field in custom. is that field move please check
> if this custom_field move to the Erpnext then add PR link here

@vishdha account_opened_date is moved to erpnext in this PR https://github.com/Bloomstack/erpnext/pull/1593

2021-09-08 06:46 UTC, vishdha submitted a review, later dismissed

2021-09-14 13:30 UTC, sahil28297 requested changes

2021-09-14 13:30 UTC, sahil28297 commented on erpnext/selling/doctype/customer/customer.py
> +		"""update lead account opend date"""
```suggestion
		"""update lead account opened date"""
```

2021-09-14 13:31 UTC, sahil28297 approved these changes

2021-09-14 13:33 UTC, merged