chore: added bloomstack_core's file changes into erpnext file
DigiThinkIT/erpnext pull request #1641
Opened 2021-09-13 12:37 UTC by meshramsaroj

**Filename:** bloomstack_core/bloomstack_core/public/js/item.js

**Deleted file PR:**

**Dependent files:** bloomstack_core/bloomstack_core/hook_events/item.py

2021-09-14 07:06 UTC, sahil28297 commented
@meshramsaroj add proper PR title

2021-09-14 11:20 UTC, sahil28297 requested changes

2021-09-14 11:20 UTC, sahil28297 commented on erpnext/stock/doctype/item/item.js
> +					query: "erpnext.hook_events.item.metrc_item_category_query",
The path is not proper, coordinate with Myuddin for putting the correct path

2021-09-14 11:20 UTC, sahil28297 commented on erpnext/stock/doctype/item/item.js
> +					query: "erpnext.hook_events.item.metrc_uom_query",
The path is not proper, coordinate with Myuddin for putting the correct path

2021-09-14 11:20 UTC, sahil28297 commented on erpnext/stock/doctype/item/item.js
> +					query: "erpnext.hook_events.item.metrc_unit_uom_query",
The path is not proper, coordinate with Myuddin for putting the correct path

2021-09-14 11:20 UTC, sahil28297 commented on erpnext/stock/doctype/item/item.js
> +			method: "erpnext.hook_events.item.autoname_item",
The path is not proper, coordinate with Myuddin for putting the correct path

2021-09-20 14:24 UTC, sahil28297 commented
@meshramsaroj any update on this?

2021-09-21 11:55 UTC, meshramsaroj commented
> @meshramsaroj any update on this?

Yes, I have added the correct path.
Please check

2021-09-22 04:47 UTC, sahil28297 approved these changes

2021-09-22 04:58 UTC, merged