feat: if default project status update will replicate on parent status in task
DigiThinkIT/erpnext pull request #1656
Opened 2021-09-15 10:58 UTC by vishdha

TASK ID: https://bloomstack.com/desk#Form/Task/TASK-2021-00288

Gif: 
![Peek 2021-09-15 16-28](https://user-images.githubusercontent.com/6947417/133421604-993a385f-4794-462a-90bc-98f8839eb43e.gif)

2021-09-15 12:30 UTC, neilLasrado requested changes

2021-09-15 12:30 UTC, neilLasrado commented on erpnext/projects/doctype/task/task.py
>  		elif not len(self.projects):
you can remove this elif as we are making projects mandatory

2021-09-15 12:30 UTC, neilLasrado commented on erpnext/projects/doctype/task/task.json
> +   "label": "Default Status",
leave the label as Status, don't change it, instead add a description that the status of the default project will be set.

2021-09-15 14:55 UTC, neilLasrado approved these changes, later dismissed

2021-09-16 05:01 UTC, Anurag810 submitted a review, later dismissed

2021-09-16 05:01 UTC, Anurag810 commented on erpnext/projects/doctype/task/task.json
> +   "description": "the status of the default project will fetch from the projects table.",
It should be like .... "**T**he......default **P**roject........**P**rojects table". 
As the label of the table is Projects and Project is also a DocType.

2021-09-16 07:30 UTC, sahil28297 requested changes

2021-09-16 07:30 UTC, sahil28297 commented on erpnext/projects/doctype/task/task.json
> +   "description": "The status of the default Project will fetch from the Projects table.",
```suggestion
   "description": "The status of the default Project is fetched from the Projects table.",
```

2021-09-16 07:30 UTC, sahil28297 approved these changes

2021-09-16 07:33 UTC, merged