chore: move public css file from bloomstack_core to erpnext
DigiThinkIT/erpnext pull request #1672
Opened 2021-09-16 11:29 UTC by vishdha

**Task ID**: https://bloomstack.com/desk#Form/Task/TASK-2021-00282
**Description**: Move public css from core to erpnext
**Tested**: No
**Gif Added**: No 
**Dependency PR**: https://github.com/Bloomstack/erpnext/pull/1670
**Bloomstack Core PR**:

2021-09-20 07:30 UTC, sahil28297 requested changes
@vishdha Some of these files are to be moved in frappe app like we discussed, eg:
erpnext/public/css/buttons.css
erpnext/public/css/desk.css
erpnext/public/css/login.css
erpnext/public/css/reports.css
erpnext/public/css/trees.css
erpnext/public/css/nprogress.css not sure about this, ask @DeveloperMetal

2021-09-21 09:11 UTC, vishdha commented
> @vishdha Some of these files are to be moved in frappe app like we discussed, eg:
> erpnext/public/css/buttons.css
> erpnext/public/css/desk.css
> erpnext/public/css/login.css
> erpnext/public/css/reports.css
> erpnext/public/css/trees.css
> erpnext/public/css/nprogress.css not sure about this, ask @DeveloperMetal

we can eliminate erpnext/public/css/reports.css because it contains cash flow related changes only

2021-09-21 11:10 UTC, sahil28297 requested changes
@vishdha benner, login and mobile-fixes will also go in frappe

2021-09-22 04:38 UTC, sahil28297 approved these changes

2021-09-22 04:40 UTC, sahil28297 approved these changes

2021-09-22 04:40 UTC, merged