feat: add progress bar to strain doctype
DigiThinkIT/erpnext pull request #1685
Opened 2021-09-20 09:20 UTC by nehasacher143

**Task:** https://bloomstack.com/desk#Form/Task/TASK-2021-00243

**Screenshot:**
![Peek 2021-09-19 22-14](https://user-images.githubusercontent.com/45919049/133979519-477af77f-6a53-46a1-9162-e5f82941da09.gif)

2021-09-20 16:18 UTC, rvpasari requested changes

2021-09-20 16:18 UTC, rvpasari commented on erpnext/agriculture/doctype/strain/strain.json
> +   "options": "Compliance Document\nReported to Bloomtrace\nSuccessful on Bloomtrace\nFailed on Bloomtrace\nReported to METRC\nSuccessful on METRC\nFailed on METRC\nMETRC ID Reported to Bloomstack"
This should be a read only field

2021-09-21 05:09 UTC, nehasacher143 commented on erpnext/agriculture/doctype/strain/strain.json
> +   "options": "Compliance Document\nReported to Bloomtrace\nSuccessful on Bloomtrace\nFailed on Bloomtrace\nReported to METRC\nSuccessful on METRC\nFailed on METRC\nMETRC ID Reported to Bloomstack"
@rvpasari This will be a read-only, once we have an API ready to change the field value, For testing, I have kept it editable

2021-09-23 03:03 UTC, rvpasari commented on erpnext/agriculture/doctype/strain/strain.json
> +   "options": "Compliance Document\nReported to Bloomtrace\nSuccessful on Bloomtrace\nFailed on Bloomtrace\nReported to METRC\nSuccessful on METRC\nFailed on METRC\nMETRC ID Reported to Bloomstack"
ah got it

2021-09-23 03:03 UTC, rvpasari commented
Progress bar looks good to me guys @neilLasrado @sahil28297 @DeveloperMetal

2021-10-11 10:41 UTC, sahil28297 requested changes
@nehasacher143 Fix sider Issues. Also @DeveloperMetal can yu have a look at this, can we generalize some of the hard-coded things in this?

2021-10-19 14:13 UTC, DeveloperMetal requested changes
Only really issue I have is injecting css with javascript on the header.
Everything else is looking bueno.

2021-10-19 14:13 UTC, DeveloperMetal commented on erpnext/agriculture/doctype/strain/strain.js
> +$('head').append('<link rel="stylesheet" type="text/css" href="assets/erpnext/css/progressbar.css">');
any reason we are not adding this into build.json? should probably go into the desk.css

2021-11-02 06:44 UTC, neilLasrado commented
@nehasacher143 whats going on with this?

2021-11-07 09:22 UTC, neilLasrado commented
@nehasacher143 @sahil28297 any updates?

2021-11-16 19:08 UTC, neilLasrado commented
@nehasacher143 close this PR if we don't intend to finish it. 

@sahil28297

2021-12-03 11:42 UTC, Anurag810 commented
@nehasacher143 Closing this pr due to no activity. make it alive if you are still working on this.

2021-12-03 11:42 UTC, closed without merging