fix: fixed test_auto_batch test case of purchase invoice
DigiThinkIT/erpnext pull request #1737
Opened 2021-10-05 10:22 UTC by meshramsaroj

**Task Link:** https://bloomstack.com/desk#Form/Task/TASK-2021-00346

**Screenshot:**

- Before
![image](https://user-images.githubusercontent.com/53329367/136005424-1dbe3f96-4df5-48c9-aca4-f7ef8d460bac.png)

- After
![image](https://user-images.githubusercontent.com/53329367/136005495-871e59c6-e7d7-43ec-8430-674a330942ee.png)

2021-10-05 14:45 UTC, vishdha requested changes

2021-10-05 14:45 UTC, vishdha commented on erpnext/controllers/stock_controller.py
> -						batch_naming_series=d.batch_naming_series,
@meshramsaroj Why did you removed this. Its used for stock entry and purchase receipt
don't remove this

2021-10-05 14:45 UTC, vishdha commented on erpnext/stock/doctype/batch/batch.py
> +				if batch_number_series:
@meshramsaroj you have to fix test because of this change. do not remove code from controller and doctype to fixed test

2021-10-06 05:13 UTC, sahil28297 commented
Closing this as invalid PR, fix the test case and not controllers

2021-10-06 05:13 UTC, closed without merging