feat: Added Integration Request for TaxJar API
DigiThinkIT/erpnext pull request #1750
Opened 2021-10-07 10:08 UTC by vishdha

**TASK ID:** : https://bloomstack.com/desk#Form/Task/TASK-2021-00296

- [x] Development

**Masters Document Type**
Integration Request
Added Integration Request log for TaxJar API

**Workflow:**
Once TaxJar API hits it will create Integration request log in Integration Request doctype. Users can track the status of API
If it is executed successfully it will record output 
if it gets failed it will record an error log 

**screenshot**
![TaxJar-477779a2ff](https://user-images.githubusercontent.com/6947417/136364397-3d48adbe-272a-4ef8-9d58-0107e085b585.png)

2021-10-18 05:39 UTC, sahil28297 requested changes
@

2021-10-18 05:39 UTC, sahil28297 commented on erpnext/erpnext_integrations/doctype/taxjar_configuration/taxjar_configuration.py
> +			self.integration_request.update_status(data, "Failed")
why are we storing the "integration request" at two places? Can we not just create the integration request at store the reference in taxjar doctype. Also this won't catch any error thrown while creating the request log, I'll suggest creating a separate function that handles the request log, there's duplication of code at many places.

2021-10-18 05:39 UTC, sahil28297 commented on erpnext/erpnext_integrations/taxjar_integration.py
> +
```suggestion

```

2021-10-18 05:39 UTC, sahil28297 commented on erpnext/erpnext_integrations/taxjar_integration.py
> +		doc.integration_request.update_status(tax_dict, "Failed")
there's no tax_dict defined in this function

2021-10-18 05:39 UTC, sahil28297 commented on erpnext/erpnext_integrations/taxjar_integration.py
> +		doc.integration_request.update_status(tax_dict, "Completed")
there's no tax_dict defined in this function

2021-10-19 14:54 UTC, neilLasrado commented on erpnext/erpnext_integrations/doctype/taxjar_configuration/taxjar_configuration.py
> +			self.integration_request.update_status(data, "Failed")
Make a common function that creates an integration request and add it to utils. 

Something like https://github.com/Bloomstack/bloomstack_core/blob/production/bloomstack_core/bloomtrace/utils.py#L27
 (This will also need to be refactored)

2021-11-02 06:44 UTC, neilLasrado commented
@vishdha whats going on with this PR?

2021-11-02 07:09 UTC, vishdha commented
Hey @neilLasrado  Modified some change will be pushing today

2021-11-02 13:51 UTC, vishdha commented
closing this new pr added https://github.com/Bloomstack/erpnext/pull/1810

2021-11-02 13:51 UTC, closed without merging