fix: Wrong condition and and removed company query
DigiThinkIT/erpnext pull request #1752
Opened 2021-10-07 13:35 UTC by Anurag810

**TODO:**
- [x] Fixes

<h3>Traceback/Bug Report:</h3>  

* the user is not allowed to save the timesheet when he selects a task and default project.
* User is not able to select the default project due to a set_query.

![Screenshot from 2021-10-07 18-31-05](https://user-images.githubusercontent.com/32095923/136393697-0f89f692-57d5-48dd-9b4e-e8d6eecbcdba.png)
```
Traceback:
 File "/home/anurag/workspace/apps/erpnext/erpnext/projects/doctype/timesheet/timesheet.py", line 26, in validate
    self.validate_time_logs()
  File "/home/anurag/workspace/apps/erpnext/erpnext/projects/doctype/timesheet/timesheet.py", line 148, in validate_time_logs
    self.validate_task_project()
  File "/home/anurag/workspace/apps/erpnext/erpnext/projects/doctype/timesheet/timesheet.py", line 160, in validate_task_project
    frappe.throw(_("Row #{0}. Project {1} is not set as default project for Task {2}. ". format(log.idx, log.project, log.task)))
  File "/home/anurag/workspace/apps/frappe/frappe/__init__.py", line 380, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable)
  File "/home/anurag/workspace/apps/frappe/frappe/__init__.py", line 359, in msgprint
    _raise_exception()
  File "/home/anurag/workspace/apps/frappe/frappe/__init__.py", line 319, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Row #1. Project Bloomtrace is not set as default project for Task TASK-2021-00075.

```
<h3>Steps to replicate:</h3> 

* Create Task and Set default project. 
* Try to save timesheet for that task and project

<h3>Fixes:</h3> 
changed condition and removed set query as there is no company field for tasks that cause conflict during the project selectioln.

2021-10-07 13:52 UTC, vishdha commented
@Anurag810 Can you confirm this change again. Its Validation that added for project

2021-10-07 14:01 UTC, vishdha requested changes

2021-10-07 14:01 UTC, vishdha commented on erpnext/projects/doctype/timesheet/timesheet.js
> -		};
@Anurag810 why did you remove this? This is needed for the project that should belongs to that company. otherwise it will create a timesheet for the project which belongs to different company

2021-10-07 14:01 UTC, vishdha commented on erpnext/projects/doctype/timesheet/timesheet.py
> +			project = frappe.db.get_value("Task", log.task, "project")
@Anurag810 why moved up from if condition. what if there is no task in times_log it will return None

2021-10-11 10:46 UTC, sahil28297 requested changes

2021-10-11 10:46 UTC, sahil28297 commented on erpnext/projects/doctype/timesheet/timesheet.py
> +			project = frappe.db.get_value("Task", log.task, "project")
@Anurag810 this will break if the task field is not filled in child table, `log.task` will return none. It should go below `if log.task:` line

2021-10-18 05:26 UTC, sahil28297 requested changes

2021-10-18 05:26 UTC, sahil28297 commented on erpnext/projects/doctype/timesheet/timesheet.py
> +			project = frappe.db.get_value("Task", log.task, "project")
@Anurag810 any update on this?

2021-10-20 06:48 UTC, Anurag810 commented
@sahil28297  I have already tested that, you can merge this. as the Project table is mandatory in a task so it will never return "None", and also checked the saving timesheet without tasks and projects.  It is working fine. I also discussed this with Vishal too offline
Sorry, I just forgot to reply.

2021-10-25 07:36 UTC, sahil28297 approved these changes

2021-10-25 07:37 UTC, merged