fix: remove travis and add coverage
DigiThinkIT/erpnext pull request #1769
Opened 2021-10-13 11:54 UTC by vishdha

**Decription**

Removed travis .yml

2021-10-18 05:23 UTC, sahil28297 requested changes

2021-10-18 05:23 UTC, sahil28297 commented on .github/workflows/server-tests.yml
> +        run: cd ~/frappe-bench/ && bench --site test_site run-tests --app erpnext --coverage
```suggestion
        run: cd ~/frappe-bench/ && bench --site test_site run-tests --app erpnext
```
I'll add coverage command separately.

2021-10-18 05:25 UTC, sahil28297 requested changes
delete the .travis folder as well

2021-11-02 06:45 UTC, neilLasrado commented
@vishdha whats going on with this PR?

2021-11-07 09:29 UTC, neilLasrado commented
@vishdha @sahil28297 what's going on with this?

2021-11-10 10:25 UTC, sahil28297 commented
Closing this, refer https://github.com/Bloomstack/erpnext/pull/1815

2021-11-10 10:25 UTC, closed without merging