feat(contract): Improvised the sales order workflow to add contract
DigiThinkIT/erpnext pull request #178
Opened 2019-04-12 10:16 UTC by DeeMysterio

Please read the pull request checklist to make sure your changes are merged: https://github.com/frappe/erpnext/wiki/Pull-Request-Checklist

The contract can be done on a submitted quotation through the "make" button on the latter.The data in the quotation is replicated in the contract which we can save.This saved contract is then served to the customer through a unique link that is valid for 24 hours.The customer can read the contract and put a sign on it and submits.The submitted data gets saved in the backend and the sales order is created.

2019-04-15 09:41 UTC, vjFaLk requested changes

2019-04-15 09:41 UTC, vjFaLk commented on erpnext/crm/doctype/contract/contract.json
> +   "fieldname": "hash",
Don't call it "hash" call it a "token"

2019-04-15 09:41 UTC, vjFaLk commented on erpnext/crm/doctype/contract/contract.py
> -# Copyright (c) 2018, Frappe Technologies Pvt. Ltd. and contributors
Put this back 😅

2019-04-15 09:41 UTC, vjFaLk commented on erpnext/crm/doctype/contract/contract.py
> +	def create_hash(self):
Call this `generate_token` instead of `create_hash`

2019-04-15 09:41 UTC, vjFaLk commented on erpnext/crm/doctype/contract/contract.py
> +		recipients = ["dikshajadhav11.dj@gmail.com"]
Your email is hardcoded 😅, change it to the rightrecipientt

2019-04-15 09:41 UTC, vjFaLk commented on erpnext/crm/doctype/contract/contract.py
> +			Email the contract link to user for him to sign it
Use gender neutral terminology, or rather avoid using it at all.

2019-04-15 09:41 UTC, vjFaLk commented on erpnext/crm/doctype/contract/contract.py
> +	def send_contract_email_notification(self):
This function isn't being called anywhere?

2019-04-15 09:41 UTC, vjFaLk commented on erpnext/crm/doctype/contract/contract.py
> +		recipients = ["diksha@digithinkit.com"]
Same as above, change the code to get the right recipients. Also, you've hardcoded the URL as well, you want to generate that dynamically too. You can get the current site name from `frappe.local.site`

2019-04-15 09:41 UTC, vjFaLk commented on erpnext/crm/doctype/contract/contract.py
> +		self.create_sales_invoice()
Why are we creating Sales Invoice on submit?

2019-04-15 09:41 UTC, vjFaLk commented on erpnext/crm/doctype/contract/contract.py
> +	try:
No need to wrap this around try except

2019-04-15 09:41 UTC, vjFaLk commented on erpnext/crm/doctype/contract/contract.py
> +		return "couldn't submit signing"
Returning this won't do anything. If you want to throw an exception, you'll have to do `frappe.throw("Exception message")`

2019-04-15 09:41 UTC, vjFaLk commented on erpnext/crm/doctype/contract/contract.py
> +	try:
Same, no need to wrap this around try except.

2019-04-15 09:41 UTC, vjFaLk commented on erpnext/crm/doctype/contract/contract.py
> +		return "Your sign is shared successfully!"
Grammar!

2019-04-15 09:41 UTC, vjFaLk commented on erpnext/selling/doctype/quotation/quotation.py
> +def _make_sales_order(source_name, target_doc = None, ignore_permissions=False):
Inconsistent spacing `target_doc = None`

2019-04-15 09:41 UTC, vjFaLk commented on erpnext/selling/doctype/quotation/quotation.py
> +		target.contract_terms = "These are our contract terms"
Don't hardcode this, keep it empty

2019-04-15 09:41 UTC, vjFaLk commented on erpnext/selling/doctype/quotation/quotation.py
> +	def update_item(obj, target, source_parent):
Where did this come from?

2019-04-15 09:41 UTC, vjFaLk commented on erpnext/www/contract_generated.py
> +    for i in a:
There has to be a better way of getting the token from the query_string

2019-04-16 05:31 UTC, DeveloperMetal reviewed
I agree with all of Valmik's comments
I do want to add that you should also add images(gif or static) of what we should expect to see when testing your addition/changes as it makes finding your work faster. Also, helps on catching "it works on my machine" issues as well

2019-05-23 11:33 UTC, closed without merging