feat(taxjar) :added support for Line item for taxjar
DigiThinkIT/erpnext pull request #1789
Opened 2021-10-25 06:05 UTC by vishdha

TODO:(Mandatory)
- [x] Development.

...

<h3>Description (Mandatory):</h3>
Added Line items to show item description on taxjar.

Screenshots/GIFs (Mandatory)
![image](https://user-images.githubusercontent.com/6947417/138642639-09900e31-eda3-4185-8a18-460d1f86dd95.png)

2021-11-02 07:40 UTC, neilLasrado requested changes

2021-11-02 07:40 UTC, neilLasrado commented on erpnext/erpnext_integrations/taxjar_integration.py
> +def get_doc_discount(doc):
you have not considered shipping here?

2021-11-07 09:21 UTC, neilLasrado commented on erpnext/erpnext_integrations/taxjar_integration.py
> +def get_doc_discount(doc):
@vishdha please check this

2021-11-16 19:09 UTC, neilLasrado commented
@vishdha what's going on with this PR?

2021-11-17 07:00 UTC, vishdha commented
closing this new pull request added https://github.com/Bloomstack/erpnext/pull/1831

2021-11-17 07:00 UTC, closed without merging