fix(delivery): Add more context for dispatch notification email + formatting fixes
DigiThinkIT/erpnext pull request #179
Opened 2019-04-15 10:06 UTC by Alchez

**Ref:** https://github.com/DigiThinkIT/bloomstack/issues/178

2019-04-15 10:33 UTC, vjFaLk requested changes

2019-04-15 10:33 UTC, vjFaLk commented on erpnext/stock/doctype/delivery_trip/delivery_trip.py
> +			items = frappe.get_all("Sales Invoice Item", filters={"parent": stop.sales_invoice, "docstatus": 1}, fields=["*"])
Get Items from Delivery Note, not Sales Invoice

2019-04-15 10:33 UTC, vjFaLk commented on erpnext/stock/doctype/delivery_trip/delivery_trip.py
> +	context.pop("delivery_stops", None)
Remove this line

2019-05-06 11:27 UTC, vjFaLk commented
Upstream?

2019-06-17 10:36 UTC, vjFaLk commented
@Alchez PLS UPSTREAM

2019-06-17 10:47 UTC, Alchez commented
Made upstream to [hotfix](https://github.com/frappe/erpnext/pull/17966) and [develop](https://github.com/frappe/erpnext/pull/17967).

2019-06-17 12:17 UTC, vjFaLk approved these changes

2019-06-17 12:18 UTC, merged