feat: Added Periodicity to Consolidate Financial Statements and Cost Center Financial Statements and Added Variance feature to Consolidated Financial Statements
DigiThinkIT/erpnext pull request #1793
Opened 2021-10-26 05:52 UTC by imdadhussain

Task ID: https://bloomstack.com/desk#Form/Task/TASK-2021-00395

Screenshot/ GIFS

Periodicity GIF
![period](https://user-images.githubusercontent.com/15030453/141101669-e7e02d2b-d5c5-45af-8a6e-5a302ea4bd5b.gif)

Compare with Company Variance (A-B)GIF
![varaince](https://user-images.githubusercontent.com/15030453/141101958-a0b5b4ee-6699-4baf-bb71-f105531e58b9.gif)

Profit and losses GIF
![profit and losses](https://user-images.githubusercontent.com/15030453/141111447-f81a9012-a56a-4b91-ade0-945be6aec627.gif)

Cost Center Financial Statement GIF
![cost center](https://user-images.githubusercontent.com/15030453/141111532-b9a1cea5-189c-4ea1-9114-5cfc266054a1.gif)

workflow:
1. Added Period List for balance_sheet_data. which call get_data and added the period key and company key 
2. Added company + Period Key for get_columns
3. company + period key and data generated by company + Period Key will append into data like above
4. Added and changes to get_profit_and_losses_data which call get_data and added period key and company in data as shown in GIF.
5. Made same changes for Cash Flow.
6. Made changes in Cost Center Financial Statement to make work as Consolidated Financial Statement because same method are in these and also attached Gif.

2021-11-07 09:28 UTC, neilLasrado commented
@imdadhussain what's going on with this? The PR is in draft since 12 Days!

2021-11-10 12:42 UTC, imdadhussain commented
> @imdadhussain what's going on with this? The PR is in draft since 12 Days!



> @imdadhussain what's going on with this? The PR is in draft since 12 Days!

@neilLasrado just created PR for reference for @vishdha

2021-11-10 13:00 UTC, vishdha requested changes

2021-11-10 13:00 UTC, vishdha commented on erpnext/accounts/report/consolidated_financial_statement/consolidated_financial_statement.py
> +
@imdadhussain  Remove unwanted comments

2021-11-10 13:00 UTC, vishdha commented on erpnext/accounts/report/consolidated_financial_statement/consolidated_financial_statement.py
> +					row[f"{company}(total)"] = total
This code and lines 386 to 400 are kind of redundant you may optimize code here

2021-11-10 13:00 UTC, vishdha commented on erpnext/accounts/report/balance_sheet/balance_sheet.py
> +					total_row[f"{company}(total)"] = total_row_total
This code and lines 167 to 184 are kind of redundant we can optimize this

2021-11-10 13:00 UTC, vishdha commented on erpnext/accounts/report/consolidated_financial_statement/consolidated_financial_statement.py
> +						})
This also optimizes Lines 218 to 233 same

2021-11-11 06:25 UTC, vishdha requested changes

2021-11-11 06:25 UTC, vishdha commented on erpnext/accounts/report/consolidated_financial_statement/consolidated_financial_statement.py
> +			#row[company] = 0.0
```suggestion
		
```

2021-11-16 19:10 UTC, neilLasrado commented
@vishdha please review this

2021-11-23 05:26 UTC, vishdha approved these changes

2021-11-23 07:39 UTC, sahil28297 approved these changes
Approving and merging this as it has been tested locally by @vishdha

2021-11-23 07:40 UTC, merged