fix: removed status- Unsubscribed from Email Campaign
DigiThinkIT/erpnext pull request #1821
Opened 2021-11-12 13:55 UTC by MyuddinKhatri

TODO:

- [x] Fixes
- [x] Patches
- [ ] Test Cases(not required)

<h3>Traceback/Bug Report:</h3>  
Email Campaign Status was changed to Unsubscribed for completed campaign

<h3>Expected Behaviour/Fixes:</h3> 
Unsubscribed status is removed from the Email Campaign Doctype

2021-11-15 06:42 UTC, neilLasrado submitted a review, later dismissed

2021-11-17 13:49 UTC, sahil28297 approved these changes

2021-11-17 13:55 UTC, sahil28297 requested changes

2021-11-17 13:55 UTC, sahil28297 commented on erpnext/crm/doctype/email_campaign/email_campaign.py
> +	email_campaigns = frappe.get_all("Email Campaign", filters = { 'status': ('not in', ['Completed', 'Scheduled']) })
```suggestion
	email_campaigns = frappe.get_all("Email Campaign", filters = {'status': ('not in', ['Completed', 'Scheduled'])})
```

2021-11-17 14:18 UTC, merged