fix: disable payment gateway page if payment request is cancelled
DigiThinkIT/erpnext pull request #1833
Opened 2021-11-24 05:54 UTC by MyuddinKhatri

- [x] Fixes
- [ ] Patches(not required)
- [ ] Test Cases(notrequired)

<h3>Traceback/Bug Report:</h3>  
Payment can be done though Payment request is cancelled

<h3>Expected Behaviour/Fixes:</h3> 
This is the behaviour after fixes.

Ex: This pull request ensures that on clicking the Select all button, it will select all items.
Payment Link says 404 if Payment Request is Cancelled

2021-11-24 08:03 UTC, nehasacher143 submitted a review, later dismissed
Looks fine to me

2021-11-24 11:36 UTC, vishdha submitted a review, later dismissed

2021-11-24 16:06 UTC, DeveloperMetal requested changes

2021-11-24 16:06 UTC, DeveloperMetal commented on erpnext/templates/pages/integrations/authorizenet_checkout.py
> +	context["status"] = frappe.db.get_value("Payment Request", payment_context.get("reference_docname"), "status")
Future proof this and use payment_context.get("reference_doctype") instead of hard coding "Payment Requests"

2021-11-25 05:42 UTC, MyuddinKhatri commented
@DeveloperMetal please check

2021-11-25 12:42 UTC, DeveloperMetal approved these changes

2021-11-29 03:06 UTC, vishdha approved these changes

2021-11-29 06:45 UTC, sahil28297 approved these changes

2021-11-29 06:45 UTC, merged