feat: Backfill Transaction feature added
DigiThinkIT/erpnext pull request #1845
Opened 2021-12-02 13:37 UTC by vishdha

2021-12-03 11:33 UTC, Anurag810 requested changes, later dismissed
Please update description

2021-12-03 11:33 UTC, Anurag810 commented on erpnext/erpnext_integrations/taxjar_integration.py
> +	# 	print(traceback.format_exc(ex))
`<br><br>`  will cause problem during translation. will recommend adding tags on translated string.

2021-12-03 11:33 UTC, Anurag810 commented on erpnext/erpnext_integrations/taxjar_integration.py
> +	# except Exception as ex:
remove commented code

2021-12-03 11:33 UTC, Anurag810 commented on erpnext/erpnext_integrations/taxjar_integration.py
> +		# frappe.throw(_(error_msg))
remove commented code.

2021-12-03 11:33 UTC, Anurag810 commented on erpnext/erpnext_integrations/taxjar_integration.py
> +		error_msg = """There seems to be an error <br><br>{0}""".format(sanitize_error_response(err))
use _() to translate the string and `<br><br>`  will cause problems during translation. will recommend to add tags on a translated string.

2021-12-03 11:33 UTC, Anurag810 commented on erpnext/erpnext_integrations/doctype/backfill_taxjar_transactions/backfill_taxjar_transactions.json
> +  "from_date",
why have you created a different section for only two fields you can put them together.

2021-12-07 07:17 UTC, sahil28297 requested changes
fix sider issues

2021-12-07 07:17 UTC, sahil28297 commented on erpnext/erpnext_integrations/taxjar_integration.py
> +	)
```suggestion
	)
```

2021-12-07 09:19 UTC, sahil28297 approved these changes

2021-12-07 09:19 UTC, merged