fix: added validation to to prevent net total from being negative
DigiThinkIT/erpnext pull request #1853
Opened 2022-02-09 17:17 UTC by MyuddinKhatri

[Issue](https://bloomstack.com/desk#Form/Issue/ISS-2022-00007)
- [x] Fixes
- [ ] Patches(not required)
- [ ] Test Cases(not required)

<h3>Traceback/Bug Report :</h3>  
When applying a 100% discount to a quote on the grand total it is causing the line items to have a negative value. Felipe took a look at this issue and the problem is related to Net total/Grand total discount.

![screenshot-jhaudio com-2022 02 09-22_41_45](https://user-images.githubusercontent.com/53251406/153253360-7ee8dbc1-c646-43e8-a84b-637da246d568.jpg)

<h3>Steps to replicate:</h3> 

* Step 1: Create Quotation
* Step 2: Tax should be applied
* Step 3: Set Additional Discount Percentage to 100 %
* Step 4 : Save Quotation

<h3>Expected Behaviour/Fixes:</h3> 
It does not set total to negative and net rate to negative even if 100 percent discount is applied

![screenshot-jhaudio_8008-2022 02 09-22_44_55](https://user-images.githubusercontent.com/53251406/153253908-766a2eeb-1315-41b4-87f0-96bebf972d9f.jpg)

2022-02-10 12:08 UTC, vishdha requested changes

2022-02-10 12:08 UTC, vishdha commented on erpnext/controllers/taxes_and_totals.py
> +								item.precision("net_amount"))
Why are doing this change?  as there is check apply_discount_on == Net Total. so your discount amount can not be greater than the Net total. so these changes are not required. 
please validate this and then remove this change

2022-02-10 12:08 UTC, vishdha commented on erpnext/public/js/controllers/taxes_and_totals.js
> +					}
Why are doing this change?  as there is check apply_discount_on == Net Total. so your discount amount can not be greater than the Net total. so these changes are not required.
please validate this and then remove this change

2022-02-14 04:03 UTC, MyuddinKhatri commented on erpnext/controllers/taxes_and_totals.py
> +								item.precision("net_amount"))
I did tested after removing this code but it was still setting negative value

2022-02-14 04:03 UTC, MyuddinKhatri commented on erpnext/public/js/controllers/taxes_and_totals.js
> +					}
I did tested after removing this code but it was still setting negative value

2022-02-14 09:30 UTC, MyuddinKhatri commented
@vishdha i have done the changes please check.

2022-02-14 14:06 UTC, neilLasrado approved these changes

2022-02-15 04:23 UTC, vishdha approved these changes
Please Add a description in PR why we decided to make net_amount zero. if someone revisits why this change apply

2022-02-15 04:23 UTC, vishdha commented on erpnext/controllers/taxes_and_totals.py
> +				if net_amount < 0 and  not self.doc.is_return:
```suggestion
				if net_amount < 0 and not self.doc.is_return:
```

2022-02-15 07:29 UTC, sahil28297 approved these changes

2022-02-15 07:29 UTC, merged