fix(upload attendance): better handle csv file validation
DigiThinkIT/erpnext pull request #274
Opened 2019-12-17 12:19 UTC by DeeMysterio

**Task:** [TASK-2019-00842](https://digithinkit.global/desk#Form/Task/TASK-2019-00842)

**Screenshots/Gifs:**

![Screenshot 2019-12-17 at 5 47 03 PM](https://user-images.githubusercontent.com/13060550/70994998-762da280-20f5-11ea-97ed-0ff9faa7e2cf.png)

2019-12-17 14:03 UTC, Alchez requested changes

2019-12-17 14:03 UTC, Alchez commented on erpnext/hr/doctype/upload_attendance/upload_attendance.py
> +	if not fname.lower().endswith(".csv"):
Add a simple check for `fname`, just to see if it's not empty, otherwise it'll fail at the `lower` call

2019-12-17 14:03 UTC, Alchez commented on erpnext/hr/doctype/upload_attendance/upload_attendance.py
> -
Don't remove this line, it's just using python's standard spacing conventions

2019-12-18 05:43 UTC, Alchez approved these changes

2019-12-18 05:46 UTC, merged

2019-12-23 11:50 UTC, DeeMysterio commented
Made to [v11](https://github.com/frappe/erpnext/pull/20055), [v12](https://github.com/frappe/erpnext/pull/20054) and [develop](https://github.com/frappe/erpnext/pull/20053).