Wfh
DigiThinkIT/erpnext pull request #276
Opened 2019-12-23 10:25 UTC by DeeMysterio

**Task:** [TASK-2019-00866](https://digithinkit.global/desk#Form/Task/TASK-2019-00866)

**Additions:**

- Added a "Work From Home" option in status field.

- Provided a button saying "Mark Work From Home" on the Employee Attendance Tool.

- Changed the styling of the buttons on Employee Attendance Tool and indicators on the attendance list view.

**Screenshots/Gifs:**

![Screenshot 2019-12-23 at 3 47 58 PM](https://user-images.githubusercontent.com/13060550/71352485-710c9f80-259c-11ea-81c8-d3dbd4a753f1.png)

![Screenshot 2019-12-23 at 3 53 46 PM](https://user-images.githubusercontent.com/13060550/71352490-723dcc80-259c-11ea-8587-e884e17ad920.png)

2019-12-23 10:29 UTC, vjFaLk commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 2
           

Complexity increasing per file
==============================
- erpnext/hr/doctype/attendance/attendance_list.js  4
         

Clones added
============
- erpnext/hr/doctype/employee_attendance_tool/employee_attendance_tool.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/DigiThinkIT/erpnext/pullRequest?prid=4723003&bid=15768291)

2019-12-24 12:07 UTC, Alchez requested changes
Also fix Codacy errors

2019-12-24 12:07 UTC, Alchez commented on erpnext/hr/doctype/attendance/attendance_list.js
> +		if (doc.status == "Present" || doc.status == "Work From Home") {
Combine the conditions, like:

```javascript
if (["Present", "Work From Home"].includes(doc.status) {
	// do things
}
```

Which is similar to doing the `<value> in <iterable>` check in Python

2019-12-26 06:17 UTC, vjFaLk commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- erpnext/hr/doctype/attendance/attendance_list.js  3
         

Clones added
============
- erpnext/hr/doctype/employee_attendance_tool/employee_attendance_tool.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/DigiThinkIT/erpnext/pullRequest?prid=4723003&bid=15768291)

2019-12-26 06:19 UTC, Alchez requested changes

2019-12-26 06:19 UTC, Alchez commented on erpnext/hr/doctype/attendance/attendance_list.js
> +		} else if (doc.status == "Absent" || doc.status == "On Leave") {
Here too

2019-12-26 06:30 UTC, vjFaLk commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- erpnext/hr/doctype/attendance/attendance_list.js  2
         

Clones added
============
- erpnext/hr/doctype/employee_attendance_tool/employee_attendance_tool.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/DigiThinkIT/erpnext/pullRequest?prid=4723003&bid=15768291)

2019-12-30 07:12 UTC, DeveloperMetal approved these changes

2019-12-30 07:48 UTC, Alchez commented
@DeeMysterio, make this upstream as well

2019-12-31 09:25 UTC, merged