feat(employee): send birthdays reminders to employees in the same com…
DigiThinkIT/erpnext pull request #278
Opened 2019-12-26 07:48 UTC by DeeMysterio

**Handle birthday reminders for multi-company setup:** - 

Send birthday reminders to employees that belong to the same company as that of the birthday guy/girl does. Handle the same for multiple birthdays.

2019-12-26 09:48 UTC, vjFaLk commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/app/DigiThinkIT/erpnext/pullRequest?prid=4732931&bid=15801796)

2019-12-26 11:29 UTC, Alchez requested changes

2019-12-26 11:29 UTC, Alchez commented on erpnext/hr/doctype/employee/employee.py
> +	companies_with_birthdays = set(employee['company'] for employee in employees)
A couple of things:

- Change the variable to something like `companies_with_employee_birthdays`
- Using `dict.get` is safer than simply getting the key

```suggestion
	companies_with_employee_birthdays = set(employee.get('company') for employee in employees)
```

2019-12-26 11:29 UTC, Alchez commented on erpnext/hr/doctype/employee/employee.py
> +		recipients_list = frappe.get_all('Employee', fields = ['name', 'company'], filters = {'status': 'Active', 'company': ('in', companies_with_birthdays)})
Break this into multiple lines, each for filters and fields, and fix codacy errors on this line

2019-12-26 11:29 UTC, Alchez commented on erpnext/hr/doctype/employee/employee.py
> +			recipients = [{'name': recipient['name']} for recipient in recipients_list if recipient['company'] == employee.company ]
Use `dict.get` here as well, and do we need a pass a dictionary to `get_employee_emails`? Wouldn't just the name do?

2019-12-27 05:57 UTC, Alchez approved these changes

2019-12-27 05:58 UTC, merged

2019-12-27 05:59 UTC, Alchez commented
@DeeMysterio, make this to `bloomstack-v12-staging` as well

2019-12-27 06:23 UTC, DeeMysterio commented
> @DeeMysterio, make this to `bloomstack-v12-staging` as well

[here](https://github.com/DigiThinkIT/erpnext/pull/279)