Replace Label  Fortnightly to Every two weeks
DigiThinkIT/erpnext pull request #343
Opened 2020-03-16 10:50 UTC by Dharmraj-48

Replace label as Every two week in Payroll Frequency
![Screenshot from 2020-03-16 16-15-33](https://user-images.githubusercontent.com/60173537/76748879-8c550880-67a1-11ea-835e-52cee3ea7c36.png)

2020-03-17 10:44 UTC, Alchez requested changes
Everything else looks fine

2020-03-17 10:44 UTC, Alchez commented on erpnext/hr/doctype/payroll_entry/payroll_entry.py
> +		'Every two weeks': {'days': 14},
Make the key lowercase

2020-03-17 10:44 UTC, Alchez commented on erpnext/hr/doctype/payroll_entry/payroll_entry.py
> +	# weekly, Every two weeks and daily intervals have fixed days so no problems
Make the key lowercase

2020-03-17 11:08 UTC, vishdha commented
@Dharmraj-48  Please do changes for salary slip and payroll entry too

2020-03-19 13:22 UTC, Alchez commented
Same as #348, closing

2020-03-19 13:22 UTC, closed without merging