Fix accounts settings changes
DigiThinkIT/erpnext pull request #344
Opened 2020-03-17 05:10 UTC by 0925-pinka

Before:

![Screenshot from 2020-03-17 10-35-03](https://user-images.githubusercontent.com/59438065/76823930-94618680-683b-11ea-9eb5-e4fc758be7b3.png)

After:

![Screenshot from 2020-03-17 10-39-19](https://user-images.githubusercontent.com/59438065/76823941-97f50d80-683b-11ea-9564-cac01f98fed4.png)

2020-03-17 05:16 UTC, vjFaLk commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 4
           

Complexity increasing per file
==============================
- erpnext/accounts/doctype/accounts_settings/regional/united_states.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/DigiThinkIT/erpnext/pullRequest?prid=5192234&bid=17031140)

2020-03-17 05:26 UTC, Alchez commented
@pinka0925 Can you please the add the task link and fix all the whitespace issues?

2020-03-17 06:17 UTC, Alchez requested changes

2020-03-17 06:17 UTC, Alchez commented on erpnext/regional/united_states/setup.py
> +    	custom_fields = {
Remove all changes from this file

2020-03-17 06:17 UTC, Alchez commented on erpnext/accounts/doctype/accounts_settings/regional/united_states.js
> +		frm.set_df_property("credit_controller","label","Credit Manager")
Add spaces between arguments

```suggestion
		frm.set_df_property("acc_frozen_upto", "label", "Books Closed Through"),
		frm.set_df_property("frozen_accounts_modifier", "label", "Role  Allowed to Close Books & Make Changes to Closed Periods"),
		frm.set_df_property("credit_controller", "label", "Credit Manager")
```

2020-03-17 06:17 UTC, vjFaLk commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- erpnext/accounts/doctype/accounts_settings/regional/united_states.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/DigiThinkIT/erpnext/pullRequest?prid=5192234&bid=17031140)

2020-03-17 06:32 UTC, vjFaLk commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- erpnext/accounts/doctype/accounts_settings/regional/united_states.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/DigiThinkIT/erpnext/pullRequest?prid=5192234&bid=17031140)

2020-03-17 09:17 UTC, vjFaLk commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- erpnext/accounts/doctype/accounts_settings/regional/united_states.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/DigiThinkIT/erpnext/pullRequest?prid=5192234&bid=17031140)

2020-03-17 09:24 UTC, Alchez approved these changes

2020-03-17 09:24 UTC, Alchez commented
@pinka0925, looks good. Can you make this upstream to develop as well?

2020-03-17 09:25 UTC, 0925-pinka commented
Yeah, sure

2020-03-20 10:32 UTC, merged

2020-03-20 10:33 UTC, Alchez commented
Made upstream to [hotfix](https://github.com/frappe/erpnext/pull/20964) and [develop](https://github.com/frappe/erpnext/pull/20965).