fix: nontype error for resolved and moved place order button at botto…
DigiThinkIT/erpnext pull request #345
Opened 2020-03-17 07:56 UTC by vishdha

2020-03-17 08:45 UTC, Alchez commented
@vishdha, @MyuddinKhatri, nice work!

@Er-Naren719, can you help these guys out with the placement for the "Place Order" button please? It seems to be floating above the line for the other buttons.

2020-03-17 08:47 UTC, Er-Naren719 commented
> @vishdha, @MyuddinKhatri, nice work!
> 
> @Er-Naren719, can you help these guys out with the placement for the "Place Order" button please? It seems to be floating above the line for the other buttons.

Sure.

2020-03-17 11:35 UTC, Er-Naren719 commented
@vishdha @Alchez 

I have fixed the Place Order button placement. 
Please review this PR: https://github.com/vishdha/erpnext/pull/1

2020-03-18 05:26 UTC, Alchez commented
@vishdha, can you pull Naren's changes and post a new screenshot please?

2020-03-18 18:01 UTC, DeveloperMetal submitted a review, later dismissed

2020-03-20 07:13 UTC, forellana-digithinkit commented
@vishdha @Alchez Where is this at? Did it make it upstream?

2020-03-20 07:17 UTC, Alchez commented
@forellana-digithinkit, haven't tested this one yet, will have a look today

@vishdha, can you also do this for the "Request for Quotation" button that shows up when checkout is disabled?

2020-03-23 16:48 UTC, forellana-digithinkit commented
@vishdha @Alchez any updates on this?

2020-03-24 04:53 UTC, vishdha commented
Develop: https://github.com/frappe/erpnext/pull/21034
hotfix: https://github.com/frappe/erpnext/pull/21035

2020-03-24 04:59 UTC, Alchez commented
> @vishdha, can you also do this for the "Request for Quotation" button that shows up when checkout is disabled?

@vishdha, can you check this request out too please?

2020-03-24 05:11 UTC, vishdha commented
yes.I will do that

2020-03-27 08:09 UTC, vishdha commented
@Alchez  request for quotation moved

2020-03-27 08:43 UTC, Alchez requested changes

2020-03-27 08:43 UTC, Alchez commented on erpnext/templates/includes/order/order_taxes.html
> +    {% if d.base_tax_amount %}
Don't change the spacing, keep it as tabs

2020-03-27 08:43 UTC, Alchez commented on erpnext/templates/pages/cart.html
> +	<div class="place-order-container"></div>
You've accidentally closed the `div` here, this won't display properly

Nest the conditions to make it easier to read, something like (pseudo-code):

```
if doc.items:
	<div>
		if cart_settings.enable_checkout:
			<button>Place Order</button>
		else:
			<button>Request for Quotation</button>
	</div>
```

2020-04-03 08:25 UTC, Alchez approved these changes

2020-04-03 08:25 UTC, merged