fix: Itemwise batch message added
DigiThinkIT/erpnext pull request #361
Opened 2020-04-07 12:01 UTC by vishdha

TASK ID:  https://bloomstack.com/desk#Form/Task/TASK-2020-00158
![New Stock Entry 2 - New Stock Entry 2](https://user-images.githubusercontent.com/6947417/78666803-84e2d400-78f5-11ea-94d2-881c40af9ca0.png)

2020-04-07 13:25 UTC, neilLasrado commented
@vishdha why have you done it this way?  why not fix the batch validation in Stock Ledger Entry rather than overriding it?

2020-04-07 14:32 UTC, vishdha commented
@neilLasrado check now

2020-04-08 10:16 UTC, neilLasrado requested changes

2020-04-08 10:16 UTC, neilLasrado commented on erpnext/controllers/stock_controller.py
> +	def get_batch_items(self):
You wont need this function now. right?

2020-04-09 05:44 UTC, vishdha commented
done

2020-04-09 06:11 UTC, neilLasrado approved these changes

2020-04-09 06:12 UTC, merged

2020-04-09 06:20 UTC, vishdha commented
Develop : https://github.com/frappe/erpnext/pull/21215
hotfix: https://github.com/frappe/erpnext/pull/21214