feat: order detail payment section fixed
DigiThinkIT/erpnext pull request #384
Opened 2020-05-04 12:08 UTC by nehasacher143

**Task:** Fix the order detail page for Authorizenet.

**Screenshot:
Before:**
![screenshot-localhost_8001-2020 05 04-17_37_24](https://user-images.githubusercontent.com/45919049/80964128-f434e080-8e2d-11ea-99a8-a5f800c22c37.png)

**After:**
![screenshot-localhost_8001-2020 05 04-17_36_35](https://user-images.githubusercontent.com/45919049/80964063-d8313f00-8e2d-11ea-890d-c050b9e009d0.png)

2020-05-04 12:13 UTC, Alchez requested changes

2020-05-04 12:13 UTC, Alchez commented on erpnext/templates/pages/order.html
> +<!--  -->
Remove this line

2020-05-04 12:13 UTC, Alchez commented on erpnext/templates/pages/order.html
> +								</div>
Fix the indentation for this block

2020-05-04 12:21 UTC, nehasacher143 commented
@Alchez Please review

2020-05-04 12:33 UTC, Alchez commented on erpnext/templates/pages/order.html
> +</script>
This threw a syntaxError the last time, revert this one

2020-05-04 16:04 UTC, Alchez approved these changes

2020-05-05 10:17 UTC, Alchez approved these changes

2020-05-05 10:18 UTC, merged

2020-05-05 10:20 UTC, Alchez commented
Updated to existing payment gateway [upstream PR](https://github.com/frappe/erpnext/pull/21374).