fix: modified sales taxes and charges template
DigiThinkIT/erpnext pull request #390
Opened 2020-05-11 08:16 UTC by vishdha

2020-05-11 16:44 UTC, DeveloperMetal submitted a review, later dismissed

2020-05-13 12:34 UTC, Alchez commented on erpnext/accounts/doctype/sales_taxes_and_charges_template/sales_taxes_and_charges_template.js
> +});
```suggestion
frappe.ui.form.on("Sales Taxes and Charges", {
	add_deduct_tax: function (frm, cdt, cdn) {
		let row = locals[cdt][cdn];

		if (!row.category && row.add_deduct_tax) {
			frappe.msgprint(__("Please select Category first"));
			row.add_deduct_tax = '';
		} else if (row.category != 'Total' && row.add_deduct_tax == 'Deduct') {
			frappe.msgprint(__("Cannot deduct when category is not 'Total'"));
			row.add_deduct_tax = '';
		}

		refresh_field('add_deduct_tax', row.name, 'taxes');
	},

	category: function (frm, cdt, cdn) {
		let row = locals[cdt][cdn];

		if (row.category != 'Total' && row.add_deduct_tax == 'Deduct') {
			frappe.msgprint(__("Cannot deduct when category is not 'Total'"));
			row.add_deduct_tax = '';
		}

		refresh_field('add_deduct_tax', row.name, 'taxes');
	},
});
```

2020-05-13 12:40 UTC, Alchez commented
@vishdha, can you move the category and add_deduct_tax logic inside the `accounts.js` file, below the other tax function:

https://github.com/DigiThinkIT/erpnext/blob/104cb3f3b8fbfbcc4bd27209be38848fb96ae291/erpnext/public/js/controllers/accounts.js#L12-L14

See how the `set_conditional_mandatory_rate_or_amount` function is setup

2020-05-13 12:41 UTC, Alchez commented
Added upstream to [hotfix](https://github.com/frappe/erpnext/pull/21637) and [develop](https://github.com/frappe/erpnext/pull/21636) PRs.

2020-05-14 08:07 UTC, Alchez commented
@neilLasrado, @vishdha, quick question: is Valuation even a thing for sales transacations? Should we just keep "Total" as the category option?

2020-05-14 08:23 UTC, Alchez requested changes

2020-05-14 08:23 UTC, Alchez commented on erpnext/public/js/controllers/accounts.js
> +				erpnext.taxes.update_category_and_add_deduct_tax(grid_row);
Don't call this on setup, it's throwing an error on the console trying to refresh the table

2020-05-14 08:23 UTC, Alchez commented on erpnext/public/js/controllers/accounts.js
> +		if(open_form) {
Running the trigger causes the following issue: `ReferenceError: open_form is not defined`

2020-05-14 09:33 UTC, Alchez commented on erpnext/public/js/controllers/accounts.js
> +		refresh_field('add_deduct_tax', d.name, 'taxes');
You already have the `open_form` object, no need for the `d` object, you can just do:

```suggestion
		refresh_field('add_deduct_tax', open_form.doc.name, 'taxes');
```

2020-05-14 09:57 UTC, Alchez approved these changes

2020-05-14 09:58 UTC, merged