Fixed duplication of expected start and end date
DigiThinkIT/erpnext pull request #443
Opened 2020-07-24 12:11 UTC by vigilantee

Marked the expected and end date of tasks.

2020-07-27 06:54 UTC, Alchez commented
@vigilantee, I think your editor might have auto-saved the JSON, which is causing the files here to be re-formatted. Can you save the doctypes again to re-generate the JSON properly?

2020-07-28 06:45 UTC, Alchez requested changes

2020-07-28 06:45 UTC, Alchez commented on erpnext/projects/doctype/task/task.json
> -   "in_preview": 1,
Keep this

2020-07-28 06:45 UTC, Alchez commented on erpnext/projects/doctype/task/task.json
> -   "fetch_from": "project.company",
Keep this

2020-07-28 07:04 UTC, vigilantee commented on erpnext/projects/doctype/task/task.json
> -   "fetch_from": "project.company",
Done.

2020-07-28 07:05 UTC, vigilantee commented on erpnext/projects/doctype/task/task.json
> -   "in_preview": 1,
Done.

2020-07-28 07:10 UTC, Alchez approved these changes

2020-07-28 07:11 UTC, merged