Added an endpoint to provide the user with a downloadable certificate of analysis coa link.
DigiThinkIT/erpnext pull request #462
Opened 2020-08-06 09:25 UTC by vigilantee

Task: https://bloomstack.com/desk#Form/Task/TASK-2020-01283

2020-08-06 09:59 UTC, Alchez requested changes
You have whitespace changes in your JSON file, please remove them

2020-08-06 09:59 UTC, Alchez commented on erpnext/stock/doctype/batch/batch.py
> +	active_batch = frappe.get_all("Batch", filters={"item": item_code, "display_on_website": 1}, fields=["name", "certificate_of_analysis"])
Add the `fields` key to the `get_active_batch` function above instead, let's not make multiple endpoints for this. If you want, rename the function to `get_active_batch_details`

2020-08-10 06:23 UTC, Alchez commented on erpnext/stock/doctype/batch/batch.py
> +	active_batch = frappe.get_all("Batch", filters={"item": item_code, "display_on_website": 1},  fields=fields )
You might want to get more fields then

```suggestion
def get_active_batch(item_code):
	active_batch = frappe.get_all("Batch", filters={"item": item_code, "display_on_website": 1},  fields=["name", "item", "item_name", "stock_uom", "thc", "cbd", "certificate_of_analysis"])
```

2020-08-11 11:01 UTC, vigilantee commented on erpnext/stock/doctype/batch/batch.py
> +	active_batch = frappe.get_all("Batch", filters={"item": item_code, "display_on_website": 1},  fields=fields )
Done.

2020-08-11 11:07 UTC, Alchez submitted a review, later dismissed

2020-08-11 12:09 UTC, Alchez commented
Moved to #470

2020-08-11 12:09 UTC, closed without merging