feat: appending each item's active batch to item object itself
DigiThinkIT/erpnext pull request #483
Opened 2020-08-17 16:13 UTC by nehasacher143

**Task:** Get the Active batch information for each Product/Item.

**Description:** We have appended the 'Active Batch' information to the product object itself.

2020-08-18 06:47 UTC, Alchez requested changes
This seems fine, just needs some minor tweaks

2020-08-18 06:47 UTC, Alchez commented on erpnext/www/all-products/index.py
> +from erpnext.stock.doctype.batch.batch import (get_active_batch)
Remove the parentheses

2020-08-18 06:47 UTC, Alchez commented on erpnext/www/all-products/index.py
> +	context.products = get_products_for_website(field_filters, attribute_filters, search)
Keep it as `context.items`, just in case it's being used somewhere else

2020-08-18 06:47 UTC, Alchez commented on erpnext/www/all-products/index.py
> +			product["active_batch"] = get_active_batch(product.name)
You've over-indented here

2020-08-19 13:50 UTC, DeveloperMetal requested changes
As @Alchez already mentioned:

- cleanup import parenthesis, that's not common python syntax
- Check your spacing, only use tabs for .py files on all of our projects

2020-08-19 15:48 UTC, nehasacher143 commented
Hey @Alchez @DeveloperMetal Please review

2020-08-20 07:25 UTC, Alchez approved these changes

2020-08-20 07:33 UTC, merged