feat: New Fields in opportunity doctype
DigiThinkIT/erpnext pull request #485
Opened 2020-08-18 07:10 UTC by nmimsnikhil

1.Added Service Fee
2.Added Software Fee
3. Calculate the total of all texts entered into the opportunity amount field.

![fee_opportunity](https://user-images.githubusercontent.com/56826544/90481781-f9553b80-e14f-11ea-9b48-523778833dac.gif)

2020-08-18 07:50 UTC, Alchez commented
@nmimsnikhil, please add the task link to the PR too

2020-09-02 12:29 UTC, nmimsnikhil commented
@Alchez changes are not done just updating my branch to make changes

2020-09-03 05:59 UTC, Alchez requested changes

2020-09-03 05:59 UTC, Alchez commented on erpnext/crm/doctype/opportunity/opportunity.json
> +   "default": "0",
Save this doctype again, the `modified` time doesn't seem to have changed. That's what Frappe uses for syncing new fields.

2020-09-03 05:59 UTC, Alchez commented on erpnext/crm/doctype/opportunity/opportunity.js
> +		}
```suggestion
		frm.toggle_display('service_fee', !frm.doc.with_items);
		frm.toggle_display('software_fee', !frm.doc.with_items);

		if (frm.doc.with_items == 1) {
			frm.trigger("calculate_amount");
		} else {
			frm.trigger("calculate_opportunity_cost");
		}
```

2020-09-03 06:21 UTC, Alchez commented on erpnext/crm/doctype/opportunity/opportunity.js
> +		let amount = frm.doc.service_fee + frm.doc.software_fee;
Use `flt` for float conversions here, just in case it's not the type we expect. If it's a non-float type, Frappe will set it to 0.

```suggestion
		let amount = flt(frm.doc.service_fee) + flt(frm.doc.software_fee);
```

2020-09-03 06:56 UTC, Alchez approved these changes

2020-09-03 07:09 UTC, merged