feat(selling): added delivery days to customer doctype
DigiThinkIT/erpnext pull request #488
Opened 2020-08-19 13:35 UTC by MyuddinKhatri

[Task](https://bloomstack.com/desk#Form/Task/TASK-2020-01316)

Customer
-[x] Add a hidden data field called Delivery Days to store the entered input from the user
-[x] Add a HTML field to show the days of the week as separate checkbox options (refer to the Employee Attendance Tool)
-[x] Collect input from the user in the HTML field, and compile it into the Delivery Days field 

Order Desk
-[x] When a user selects a delivery date, validate its day against the selected days for the customer
      -[x] If no days are selected for the customer, assume all days are valid, and let the user proceed
      -[x] If the selected day is not valid, show a warning to let the user know they've selected the wrong day, and let the user 
            proceed

2020-08-20 12:37 UTC, Alchez requested changes

2020-08-20 12:37 UTC, Alchez commented on erpnext/selling/doctype/customer/customer.js
> +		if(frm.doc.delivery_days) {
I don't see a difference between the `if` and `else` clauses :sweat_smile:

2020-08-20 12:37 UTC, Alchez commented on erpnext/selling/doctype/customer/customer.json
> +   "columns": 11,
Why 11?

2020-08-20 12:37 UTC, Alchez commented on erpnext/selling/doctype/customer/customer.json
> +   "fieldname": "days_of_the_week",
Call this delivery_days_html instead

2020-08-21 10:06 UTC, MyuddinKhatri commented on erpnext/selling/doctype/customer/customer.js
> +		if(frm.doc.delivery_days) {
Ohh My bad, First i use Set() to get unique values but once Neha does that showing selected boxes this will be solved

2020-08-21 10:23 UTC, Alchez requested changes

2020-08-21 10:23 UTC, Alchez commented on erpnext/selling/doctype/customer/customer.json
> +  "column_break_22"
You have an extra field

2020-08-21 10:23 UTC, Alchez commented on erpnext/selling/doctype/customer/customer.js
> +		});
Does this work?

```suggestion
		days_of_week.forEach(day => {
			let html = `
				<div class="col-sm-3">
					<div class="checkbox">
						<label><input type="checkbox" day="%(day)s" value="%(day)s"/>\%(day)s</label>
					</div>
				</div>
			`
			$(repl(html, {day: day})).appendTo(frm.fields_dict.days_of_the_week.wrapper);
		});
```

2020-08-24 11:00 UTC, Alchez commented
@MyuddinKhatri, the styling looks off, are we tackling that later?

![image](https://user-images.githubusercontent.com/13396535/91037635-f7dfb380-e626-11ea-81ae-f4884227a6a1.png)

Also, please rename "Delivery Window" to "Delivery Preferences"?

2020-08-24 12:04 UTC, MyuddinKhatri commented
> @MyuddinKhatri, the styling looks off, are we tackling that later?
> 
> ![image](https://user-images.githubusercontent.com/13396535/91037635-f7dfb380-e626-11ea-81ae-f4884227a6a1.png)
> 
> Also, please rename "Delivery Window" to "Delivery Preferences"? And check the Codacy issues.

Yes @Alchez the styling part will be taken care by @nehasacher143 and i'll do the changes.

2020-09-04 09:23 UTC, Alchez commented
@MyuddinKhatri, please check the issues reported by Codacy for this one

2020-09-07 12:46 UTC, hrwX commented
> > @MyuddinKhatri, the styling looks off, are we tackling that later?
> > ![image](https://user-images.githubusercontent.com/13396535/91037635-f7dfb380-e626-11ea-81ae-f4884227a6a1.png)
> > Also, please rename "Delivery Window" to "Delivery Preferences"? And check the Codacy issues.
> 
> Yes @Alchez the styling part will be taken care by @nehasacher143 and i'll do the changes.

There is a field `MultiCheck` or `MultiSelect` fieldtype in frappe where you just pass the values as options and the formatting will be handled by the field controller

2020-09-08 07:16 UTC, MyuddinKhatri commented
> > > @MyuddinKhatri, the styling looks off, are we tackling that later?
> > > ![image](https://user-images.githubusercontent.com/13396535/91037635-f7dfb380-e626-11ea-81ae-f4884227a6a1.png)
> > > Also, please rename "Delivery Window" to "Delivery Preferences"? And check the Codacy issues.
> > 
> > 
> > Yes @Alchez the styling part will be taken care by @nehasacher143 and i'll do the changes.
> 
> There is a field `MultiCheck` or `MultiSelect` fieldtype in frappe where you just pass the values as options and the formatting will be handled by the field controller

@Alchez and @hrwX have a look I have done the changes
![Customer_delivery_Days](https://user-images.githubusercontent.com/53251406/92445030-5bdeac00-f1d1-11ea-923f-b3840594c5a7.jpg)

2020-09-08 07:34 UTC, hrwX requested changes

2020-09-08 07:34 UTC, hrwX commented on erpnext/selling/doctype/customer/customer.js
> +		})
```suggestion
		});
		
```

2020-09-08 07:34 UTC, hrwX commented on erpnext/selling/doctype/customer/customer.js
> +		let days_of_week = moment.weekdays()
```suggestion
		let days_of_week = moment.weekdays();
```

2020-09-08 07:34 UTC, hrwX commented on erpnext/selling/doctype/customer/customer.js
> +		let fields = []
```suggestion
		let fields = [];
		
```

2020-09-08 07:34 UTC, hrwX commented on erpnext/selling/doctype/customer/customer.js
> +			)
```suggestion
			fields.push({
				"label": __(day),
				"value": day,
				"checked": frm.doc.delivery_days ? frm.doc.delivery_days.split(",").includes(day) : 0
			});
```

2020-09-08 07:34 UTC, hrwX commented on erpnext/selling/doctype/customer/customer.js
> +		refresh_field()
```suggestion
		});
```

2020-09-08 07:34 UTC, hrwX commented on erpnext/selling/doctype/customer/customer.js
> +			frm.set_value("delivery_days", frm.days_selected.get_value().toString())
```suggestion
			frm.set_value("delivery_days", JSON.stringify(frm.days_selected.get_value()));
```

2020-09-08 07:47 UTC, Alchez requested changes

2020-09-08 07:47 UTC, Alchez commented on erpnext/selling/doctype/customer/customer.js
> +			frm.set_value("delivery_days", frm.days_selected.get_value().toString())
Don't change this to a string, keep it as an array

```suggestion
			frm.set_value("delivery_days", frm.days_selected.get_value())
```

2020-09-08 07:47 UTC, Alchez commented on erpnext/selling/doctype/customer/customer.js
> +					"checked": frm.doc.delivery_days ? frm.doc.delivery_days.split(",").includes(day) : 0
If you have an array, this is easier to compare:

```suggestion
					"checked": frm.doc.delivery_days ? frm.doc.delivery_days.includes(day) : 0
```

2020-09-08 08:02 UTC, Alchez approved these changes

2020-09-08 09:22 UTC, merged