feat(stock): Added Manufacturing Type to BOM, Work Order and Stock Entry.
DigiThinkIT/erpnext pull request #494
Opened 2020-08-20 10:08 UTC by MyuddinKhatri

[Task](https://bloomstack.com/desk#Form/Task/TASK-2020-01146)

**BOM**
- [x] Add a select field called Manufacturing Type with the options of Discrete and Process
- [x] Write a patch to set the type in old BOMs as Discrete
- [x] If the manufacturing type is set to Process, do not allow more than one item in the Raw Materials table
- [x] When making a Work Order from BOM, prompt a dialog that asks the user to enter:
             Raw Material quantity

**Work Order**
- [x] Add a select field called Manufacturing Type with the options of Discrete and Process
- [x] Write a patch to set the type in old Work Orders as Discrete
- [x] If created from a BOM set to Process,
- [x] Calculate finished good quantity based on the entered raw material quantity (proportionately based on the BOM)

**Stock Entry**
- [x] Add a select field called Manufacturing Type with the options of Discrete and Process
- [x] Write a patch to set the type in old Stock Entries as Discrete

2020-08-20 10:39 UTC, Alchez requested changes

2020-08-20 10:39 UTC, Alchez commented on erpnext/patches/v13_0/set_manufacturing_type_in_boms.py
> +def execute():
Combine these into a single patch

2020-08-20 10:39 UTC, Alchez commented on erpnext/manufacturing/doctype/bom/bom.js
> +		}
```suggestion
		fields = [{
			fieldtype: 'Float',
			label: frm.doc.manufacturing_type == "Process" ? __('Raw Material Qty') : __('Qty To Manufacture'),
			fieldname: 'qty',
			reqd: 1,
			default: 1
		}];
```

2020-08-20 10:39 UTC, Alchez commented on erpnext/manufacturing/doctype/bom/bom.js
> +					finished_good_qty: frm.doc.items[0].qty || 0,
```suggestion
					finished_goods_qty: frm.doc.items[0].qty || 0,
```

2020-08-20 10:39 UTC, Alchez commented on erpnext/manufacturing/doctype/work_order/work_order.py
> +def make_work_order(bom_no, item, manufacturing_type, finished_good_qty=0, qty=0, project=None):
Always add new arguments to the end of the function, to avoid breaking existing calls for this function

2020-08-20 10:39 UTC, Alchez commented on erpnext/manufacturing/doctype/work_order/work_order.py
> +			wo_doc.qty = int(qty)/int(finished_good_qty)
```suggestion
			wo_doc.qty = int(qty) / int(finished_good_qty)
```

2020-08-20 11:24 UTC, Alchez requested changes

2020-08-20 11:24 UTC, Alchez commented on erpnext/manufacturing/doctype/bom/bom.js
> +		fields = [{
Revert these 2 lines

2020-08-20 11:24 UTC, Alchez commented on erpnext/manufacturing/doctype/work_order/work_order.py
>  	if not frappe.has_permission("Work Order", "write"):
Add a default for `manufacturing_type` here:

```
if manufacturing_type is None:
	manufacturing_type = "Discrete"
```

2020-08-20 13:08 UTC, neilLasrado approved these changes, later dismissed

2020-08-20 13:08 UTC, neilLasrado commented on erpnext/patches/v13_0/set_manufacturing_types.py
> +def execute():
do -

for dt in ('BOM', 'Work Order', 'Stock Entry'):
       frappe.reload_doctype(dt)

2020-08-20 13:08 UTC, neilLasrado commented on erpnext/stock/doctype/stock_entry/stock_entry.json
> +   "options": "\nDiscrete\nProcess"
set depends_on as from_bom and move this below the BOM No field

2020-08-20 13:08 UTC, neilLasrado commented on erpnext/manufacturing/doctype/bom/bom.py
> +				frappe.throw(_("Only one item for raw material is allowed"))
Change the message to - 'For Process Manufacturing, only one item is allowed as Raw material'

2020-08-21 05:47 UTC, Alchez requested changes

2020-08-21 05:47 UTC, Alchez commented on erpnext/patches/v13_0/set_manufacturing_types.py
> +	for dt in ('BOM', 'Work Order', 'Stock Entry'):
Hmm, if we're looping anyway, use string formatting to run the SQL updates too

2020-08-21 05:47 UTC, Alchez commented on erpnext/manufacturing/doctype/bom/bom.py
> +				frappe.throw(_("'For Process Manufacturing, only one item is allowed as Raw material"))
You have an extra single-quote in there

2020-08-24 10:11 UTC, Alchez requested changes

2020-08-24 10:11 UTC, Alchez commented on erpnext/manufacturing/doctype/bom/bom.js
>  			default: 1
Default this to the set quantity, based on the manufacturing type:

```suggestion
			default: frm.doc.manufacturing_type == "Process" ? frm.doc.items[0].qty : frm.doc.quantity
```

2020-08-24 10:11 UTC, Alchez commented on erpnext/manufacturing/doctype/bom/bom.py
> +				frappe.throw(_("For Process Manufacturing, only one item is allowed as Raw material"))
```suggestion
				frappe.throw(_("For Process Manufacturing, only one item is allowed as raw material"))
```

2020-08-24 10:11 UTC, Alchez commented on erpnext/manufacturing/doctype/work_order/work_order.py
> +	wo_doc.get_items_and_operations_from_bom()
Call this under the same conditions, when the qty is greater than 0

2020-08-26 11:24 UTC, neilLasrado commented
@MyuddinKhatri Can you please resolve these?

2020-08-31 05:53 UTC, Alchez commented on erpnext/patches.txt
> +>>>>>>> cde8bbfc34ef4c7b9916dd02ecd312254f787515
Have a look at this conflict

2020-09-23 05:36 UTC, hrwX requested changes

2020-09-23 05:36 UTC, hrwX commented on erpnext/manufacturing/doctype/work_order/work_order.js
> +		}
```suggestion
		frm.toggle_reqd("raw_material_qty", frm.doc.manufacturing_type == "Process");
```

2020-09-23 05:36 UTC, hrwX commented on erpnext/manufacturing/doctype/work_order/work_order.py
> +			self.qty = (bom.quantity / bom.get("items")[0].qty) * self.raw_material_qty
```suggestion
			bom = frappe.get_doc("BOM", self.bom_no)
			self.qty = (bom.quantity / bom.items[0].qty) * self.raw_material_qty
```

2020-09-23 05:36 UTC, hrwX commented on erpnext/manufacturing/doctype/work_order/work_order.py
> +			if flt(raw_material_qty) > 0:
```suggestion
		elif manufacturing_type == "Process" and flt(raw_material_qty) > 0:
```

2020-09-24 08:47 UTC, neilLasrado commented
@MyuddinKhatri can you please update the PR with the requested changed and resolve the conflicts?

2020-09-30 05:50 UTC, neilLasrado commented
@hrwX @Alchez can you please review this?

2020-09-30 05:53 UTC, Alchez approved these changes

2020-10-05 13:18 UTC, neilLasrado approved these changes

2020-10-06 12:28 UTC, merged