feat(job card): Added quality inspection for job card
DigiThinkIT/erpnext pull request #498
Opened 2020-08-21 10:24 UTC by vishdha

TASK ID: https://bloomstack.com/desk#Form/Task/TASK-2020-01142
![Peek 2020-08-21 15-34](https://user-images.githubusercontent.com/6947417/90880721-93261e00-e3c6-11ea-8039-7724773c1ce4.gif)

2020-08-21 10:37 UTC, Alchez requested changes

2020-08-21 10:37 UTC, Alchez commented on erpnext/manufacturing/doctype/job_card/job_card.py
> +class QualityInspectionNotSubmittedError(frappe.ValidationError): pass
Just import these from Stock Controller instead of defining them again

2020-08-21 10:37 UTC, Alchez commented on erpnext/manufacturing/doctype/job_card/job_card_dashboard.py
> +				'items': ['Material Request', 'Stock Entry', 'Quality Inspection']
Put this inside another section called "Quality"

2020-08-21 10:37 UTC, Alchez commented on erpnext/stock/doctype/quality_inspection/quality_inspection.py
> +	doc = get_mapped_doc("Job Card", source_name, {
Don't change the existing function, you won't be able to create Job Cards from BOMs. Create a different function for making QIs from Job Card.

2020-08-21 10:37 UTC, Alchez commented on erpnext/manufacturing/doctype/job_card/job_card.js
> +	},
Shouldn't this be automatically set whenever a QI is made from a Job Card and submitted?

2020-08-21 10:37 UTC, Alchez commented on erpnext/manufacturing/doctype/job_card/job_card.json
> +   "options": "Quality Inspection"
Should this be read-only? What is the case in other documents?

2020-08-24 16:53 UTC, vishdha commented on erpnext/manufacturing/doctype/job_card/job_card.js
> +	},
it does that way

2020-08-26 07:12 UTC, Alchez requested changes
@vishdha, I'm getting an error if I select Job Card and try to select an item

![job-card-issue](https://user-images.githubusercontent.com/13396535/91272197-fe8e3800-e798-11ea-990a-99f2c29e00f4.gif)

<details>
<summary>Details</summary>

```python
Traceback (most recent call last):
  File "/home/rohan/psych/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/rohan/psych/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/rohan/psych/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/rohan/psych/apps/frappe/frappe/handler.py", line 63, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/rohan/psych/apps/frappe/frappe/__init__.py", line 1054, in call
    return fn(*args, **newargs)
  File "/home/rohan/psych/apps/frappe/frappe/desk/search.py", line 53, in search_link
    search_widget(doctype, txt, query, searchfield=searchfield, page_length=page_length, filters=filters, reference_doctype=reference_doctype, ignore_user_permissions=ignore_user_permissions)
  File "/home/rohan/psych/apps/frappe/frappe/desk/search.py", line 78, in search_widget
    searchfield, start, page_length, filters, as_dict=as_dict)
  File "/home/rohan/psych/apps/frappe/frappe/__init__.py", line 1054, in call
    return fn(*args, **newargs)
  File "/home/rohan/psych/apps/erpnext/erpnext/stock/doctype/quality_inspection/quality_inspection.py", line 98, in item_query
    {'parent': filters.get('parent'), 'txt': "%%%s%%" % txt})
  File "/home/rohan/psych/apps/frappe/frappe/database/database.py", line 156, in sql
    self._cursor.execute(query, values)
  File "/home/rohan/psych/env/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/rohan/psych/env/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/rohan/psych/env/lib/python3.6/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/rohan/psych/env/lib/python3.6/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/rohan/psych/env/lib/python3.6/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/rohan/psych/env/lib/python3.6/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/rohan/psych/env/lib/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/rohan/psych/env/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1054, "Unknown column 'quality_inspection' in 'where clause'")
```

</details>

2020-08-26 07:12 UTC, Alchez commented on erpnext/stock/doctype/quality_inspection/quality_inspection.py
> +				"production_item":"item_code",
Map the `doctype` in Job Card to the `reference_type` in Quality Inspection

2020-08-26 07:12 UTC, Alchez commented on erpnext/manufacturing/doctype/job_card/job_card.js
> +		})
Run all link triggers when you're mapping the job card with the key:

```js
run_link_triggers: true
```

2020-08-26 07:12 UTC, Alchez commented on erpnext/manufacturing/doctype/job_card/job_card.py
> +					.format(d.idx, d.item_code), QualityInspectionRejectedError)
The `d` variable is not defined

2020-08-26 07:12 UTC, Alchez commented on erpnext/manufacturing/doctype/job_card/job_card.py
> +				reference_type = 'Job Card'
No need to use variables here, just set these directly on line 229-230

2020-08-26 07:12 UTC, Alchez commented on erpnext/manufacturing/doctype/job_card/job_card.py
> +				frappe.db.set_value("Quality Inspection", self.quality_inspection, {
This should be in the `if self.quality_inspection:` block

2020-08-28 07:44 UTC, vishdha commented
> @vishdha, I'm getting an error if I select Job Card and try to select an item
> 
> ![job-card-issue](https://user-images.githubusercontent.com/13396535/91272197-fe8e3800-e798-11ea-990a-99f2c29e00f4.gif)
> 
> Details

Try Bench migrate

2020-08-31 08:30 UTC, Alchez commented
@vishdha, I'm still getting the error after the migrate, check the traceback I've added below the GIF

2020-08-31 10:11 UTC, vishdha commented
> @vishdha, I'm still getting the error after the migrate, check the traceback I've added below the GIF

@Alchez  get filter query try to find parent table which is not present in JOB Card. Item filter query modified according to Job Card.
you may review the PR

2020-08-31 10:28 UTC, Alchez requested changes

2020-08-31 10:28 UTC, Alchez commented on erpnext/stock/doctype/quality_inspection/quality_inspection.js
> +	: (doc.reference_type == "Job Card") ? "Job Card" : doc.reference_type + " Item";
Nested tertiary operators are not readable, use a simple `if...else if...else`:

```suggestion
	let doctype;
	if (doc.reference_type == "Stock Entry") {
		doctype = "Stock Entry Detail";
	} else if (doc.reference_type == "Job Card") {
		doctype = "Job Card";
	} else {
		doctype = doc.reference_type + " Item";
	}
```

2020-08-31 10:28 UTC, Alchez commented on erpnext/stock/doctype/quality_inspection/quality_inspection.py
> +			template = frappe.db.get_value('Job Card', self.job_card, 'quality_inspection_template')
```suggestion
		if self.reference_type == "Job Card" and self.job_card:
			template = frappe.db.get_value('Job Card', self.job_card, 'quality_inspection_template')
		elif self.bom_no:
			template = frappe.db.get_value('BOM', self.bom_no, 'quality_inspection_template')
```

2020-08-31 10:28 UTC, Alchez commented on erpnext/stock/doctype/quality_inspection/quality_inspection.py
> +			if not doctype == "Job Card":
```suggestion
			if doctype != "Job Card":
```

2020-09-01 05:52 UTC, Alchez requested changes

2020-09-01 05:52 UTC, Alchez commented on erpnext/stock/doctype/quality_inspection/quality_inspection.js
> +	console.log("doctype", doctype)
Remove log

2020-09-01 09:25 UTC, Alchez requested changes
I see this while fetching the item, can you have a look at the query again? I don't see this for the other doctypes.

![image](https://user-images.githubusercontent.com/13396535/91832409-018a9c00-ec63-11ea-9101-92e485fcd298.png)

2020-09-01 15:51 UTC, vishdha commented
> I see this while fetching the item, can you have a look at the query again? I don't see this for the other doctypes.
> 
> ![image](https://user-images.githubusercontent.com/13396535/91832409-018a9c00-ec63-11ea-9101-92e485fcd298.png)

@Alchez  this is resolved

2020-09-02 06:06 UTC, Alchez approved these changes

2020-09-02 07:17 UTC, merged