Auto-generate Sales Invoices for relapsed Contracts
DigiThinkIT/erpnext pull request #51
Opened 2018-08-17 10:01 UTC by Alchez

- Added daily hook to check for relapsed contracts
- If relapsed, gather all orders placed since the contract's start date
- Sum up all the discounts applied in the orders and auto-generate sales invoice(s)
- Send notification to Contract Manager with the links to the created invoices

2018-08-20 08:23 UTC, vjFaLk commented
fix conflicts boi

2018-08-20 08:26 UTC, Alchez commented
Fixed boi

2018-08-21 06:00 UTC, vjFaLk requested changes

2018-08-21 06:00 UTC, vjFaLk commented on erpnext/crm/doctype/contract/contract.py
> +	contracts = frappe.get_all("Contract", filters={"docstatus": 1})
Let's try to avoid pulling ALL Contracts? This will progressively get slower.

2018-08-21 06:00 UTC, vjFaLk commented on erpnext/crm/doctype/contract/contract.py
> +		"start_date": ["not in", [0, None, ""]],
Is it necessary to check for multiple types of "none"?

2018-08-21 06:00 UTC, vjFaLk commented on erpnext/crm/doctype/contract/contract.py
> +	recipients = get_emails_from_role("Contract Manager")
How do these get created?

2018-08-21 06:00 UTC, vjFaLk commented on erpnext/crm/doctype/contract/contract.py
> +		subject = "Sales Invoices Generated for Relapsed Contracts"
Only capitalize names that are DocTypes

2018-08-21 06:00 UTC, vjFaLk commented on erpnext/crm/doctype/contract/contract.py
> +def create_invoice_for_lapsed_contracts():
invoice should be plural

2018-08-21 06:29 UTC, Alchez commented on erpnext/crm/doctype/contract/contract.py
> +	contracts = frappe.get_all("Contract", filters={"docstatus": 1})
Hm, true. Should I put in a time-based filter?

2018-08-21 06:29 UTC, Alchez commented on erpnext/crm/doctype/contract/contract.py
> +		"start_date": ["not in", [0, None, ""]],
The `0` can be removed, but the other two are valid values for date fields.

2018-08-21 06:30 UTC, Alchez commented on erpnext/crm/doctype/contract/contract.py
> +	recipients = get_emails_from_role("Contract Manager")
The role? We'll need to create it manually, AFAIK.

2018-08-22 06:26 UTC, vjFaLk approved these changes

2018-08-22 06:27 UTC, merged