[feat] Rearranged fields in Contract, Added Party Address
DigiThinkIT/erpnext pull request #523
Opened 2020-08-28 14:21 UTC by neilLasrado

2020-08-31 08:58 UTC, Alchez approved these changes, later dismissed

2020-09-08 10:36 UTC, Alchez commented
@neilLasrado, please resolve conflicts

2020-09-11 07:15 UTC, hrwX approved these changes, later dismissed

2020-09-11 07:15 UTC, hrwX commented
@neilLasrado Can you resolve the conflicts

2020-09-25 06:02 UTC, hrwX approved these changes

2020-09-29 09:34 UTC, Alchez requested changes

2020-09-29 09:34 UTC, Alchez commented on erpnext/crm/doctype/contract/contract.json
> +   "label": "Party Address"
Why is this Small Text? Shouldn't think be Link?

2020-10-05 13:21 UTC, merged