fix: changed sticker to label
DigiThinkIT/erpnext pull request #527
Opened 2020-09-01 10:01 UTC by nmimsnikhil

Changed Sticker to Label throughout the program

2020-09-01 10:13 UTC, Alchez requested changes

2020-09-01 10:13 UTC, Alchez commented on erpnext/stock/doctype/material_request_item/material_request_item.json
> +   "collapsible_depends_on": "eval:doc.request_for!='Labes'",
```suggestion
   "collapsible_depends_on": "eval:doc.request_for!='Labels'",
```

2020-09-01 10:13 UTC, Alchez commented on erpnext/stock/doctype/material_request_item/material_request_item.json
> +   "fieldname": "label_details",
You'll have to include this in the patch, move the data from the old field to this

2020-09-02 09:53 UTC, Alchez commented on erpnext/patches/v13_0/update_label_details_in_batch.py
> +	frappe.db.sql("alter table `tabBatch` drop column sticker_details")
We actually don't care about removing this field, Frappe will handle it

2020-09-02 10:43 UTC, Alchez approved these changes

2020-09-02 11:10 UTC, bhattdevarsh approved these changes

2020-09-02 11:12 UTC, merged