fix: only show items that require manufacture
DigiThinkIT/erpnext pull request #574
Opened 2020-09-18 09:33 UTC by Alchez

2020-09-22 06:11 UTC, hrwX requested changes

2020-09-22 06:11 UTC, hrwX commented on erpnext/selling/doctype/sales_order/sales_order.py
> +						fields=["qty"])
```suggestion
						fields=["sum(qty) as qty"])
```

2020-09-22 06:11 UTC, hrwX commented on erpnext/selling/doctype/sales_order/sales_order.py
> +						pending_qty -= total_work_order_qty
```suggestion
					pending_qty -= total_work_order_qty.qty
```

2020-09-24 08:49 UTC, neilLasrado approved these changes

2020-09-28 06:10 UTC, merged