fix: employee name display in sales person name field
DigiThinkIT/erpnext pull request #586
Opened 2020-09-22 10:36 UTC by nmimsnikhil

task link: https://app.asana.com/0/inbox/1192407899689070
![sales_person](https://user-images.githubusercontent.com/56826544/93872263-852d2b00-fced-11ea-988b-0fdcc43095e4.gif)

2020-09-22 11:56 UTC, Alchez requested changes

2020-09-22 11:56 UTC, Alchez commented on erpnext/setup/doctype/sales_person/sales_person.js
> +		}
Shouldn't the sales person name reset happen automatically with the fetch defined in the JSON?

```suggestion
		frm.toggle_enable("sales_person_name", !!frm.doc.employee);
		if (!frm.doc.employee) {
			frm.set_value("sales_person_name", "");
		}
```

2020-09-23 11:09 UTC, Alchez commented on erpnext/setup/doctype/sales_person/sales_person.js
> +		}
@nmimsnikhil, I tested this out. I've tweaked the suggestion, check it out.

2020-09-23 12:06 UTC, Alchez approved these changes

2020-09-23 18:42 UTC, bhattdevarsh approved these changes

2020-09-24 05:52 UTC, merged