fix: Quality Inspection Rejection issue fixed
DigiThinkIT/erpnext pull request #606
Opened 2020-09-28 11:42 UTC by bhattdevarsh

[TASK](https://app.asana.com/0/1194641031921089/1194255585286558)

[Reported Isssue](https://app.asana.com/0/inbox/1192407897688003/1191669362063705/1192444072310326)
[PR Reference](https://github.com/DigiThinkIT/erpnext/pull/547)

1. If Reading Parameter set as "Rejected" and clicked "Yes" in Confirm box > QI status will be set as Rejected
2. If Reading Parameter set as "Rejected" and clicked "No" in Confirm box > QI status will remain same and Reading Parameter status will Rollback.
3. If ONE Reading Parameter set as "Rejected" and later changed to "Accepted" > QI status will also set as "Accepted"
4. If MULTIPLE Reading Parameter set as "Rejected" and ONE Parameter Changed to "Accepted" > QI status will remain "Rejected"

![QI_error_msg](https://user-images.githubusercontent.com/58166671/94427149-48a97580-01ac-11eb-9119-feb5661a0cae.gif)

2020-09-29 09:39 UTC, Alchez requested changes

2020-09-29 09:39 UTC, Alchez commented on erpnext/stock/doctype/quality_inspection/quality_inspection.js
> +		let not_rejected = true;
Couldn't this be:

```suggestion
		let rejected = false;
```

Seems like that'll be more readable

2020-09-29 09:39 UTC, Alchez commented on erpnext/stock/doctype/quality_inspection/quality_inspection.js
> +		}
This should happen on the server side as well

2020-10-01 13:00 UTC, hrwX requested changes

2020-10-01 13:00 UTC, hrwX commented on erpnext/stock/doctype/quality_inspection/quality_inspection.py
> +		rejected = False
```suggestion
		self.status = "Accepted"
```

2020-10-01 13:00 UTC, hrwX commented on erpnext/stock/doctype/quality_inspection/quality_inspection.py
> +				rejected = True
```suggestion
```

2020-10-01 13:00 UTC, hrwX commented on erpnext/stock/doctype/quality_inspection/quality_inspection.py
> +			self.status = "Accepted"
```suggestion
```

2020-10-06 05:36 UTC, hrwX requested changes

2020-10-06 05:36 UTC, hrwX commented on erpnext/stock/doctype/quality_inspection/quality_inspection.js
> +		}
```suggestion
		let status = "Accepted";
		frm.doc.readings.forEach(reading => {
			if (reading.status === "Rejected") {
				status = "Rejected";
			}
		});
		frm.set_value("status", status);
```

2020-10-08 05:51 UTC, hrwX requested changes

2020-10-08 05:51 UTC, hrwX commented on erpnext/stock/doctype/quality_inspection/quality_inspection.js
> +		let rejected = false;
```suggestion
```

2020-10-13 06:51 UTC, hrwX approved these changes

2020-10-13 06:52 UTC, merged