feat: Fetchiing COA Batch from Source Pachage Tag through Pick List
DigiThinkIT/erpnext pull request #612
Opened 2020-09-30 13:25 UTC by bhattdevarsh

[TASK](https://app.asana.com/0/1194641031921089/1193623458395340)

![coa_batch_delivery](https://user-images.githubusercontent.com/58166671/94690961-5c8cdd00-034e-11eb-81c3-9fe67b61ddc4.gif)

2020-10-01 04:12 UTC, hrwX requested changes

2020-10-01 04:12 UTC, hrwX commented on erpnext/stock/doctype/pick_list/pick_list.py
> +			coa_batch = frappe.db.get_value("Package Tag",location.source_package_tag,"coa_batch_no")
```suggestion
			coa_batch = frappe.db.get_value("Package Tag", location.source_package_tag, "coa_batch_no")
```

2020-10-01 12:57 UTC, hrwX approved these changes

2020-10-06 05:39 UTC, hrwX requested changes

2020-10-06 05:39 UTC, hrwX commented on erpnext/stock/doctype/pick_list/pick_list.py
> +			coa_batch = frappe.db.get_value("Package Tag", location.source_package_tag, "coa_batch_no")
```suggestion
			coa_batch = frappe.db.get_value("Package Tag", location.source_package_tag, "coa_batch_no")
			
```

2020-10-12 13:49 UTC, neilLasrado approved these changes, later dismissed

2020-10-13 05:19 UTC, hrwX requested changes

2020-10-13 05:19 UTC, hrwX commented on erpnext/stock/doctype/pick_list/pick_list.py
> +			coa_batch = frappe.db.get_value("Package Tag", location.source_package_tag, "coa_batch_no")
```suggestion
		coa_batch = None
		if location.source_package_tag:
			coa_batch = frappe.db.get_value("Package Tag", location.source_package_tag, "coa_batch_no")
```

2020-10-13 06:49 UTC, merged