feat: added ability to destory plants
DigiThinkIT/erpnext pull request #614
Opened 2020-10-01 05:42 UTC by MyuddinKhatri

Ref: [Asana](https://app.asana.com/0/1194641031921089/1188496226446181)

2020-10-12 13:43 UTC, neilLasrado requested changes
Can you change the checkbox to a Select field with 2 options, Plant or Plant Batch?

2020-10-19 05:14 UTC, hrwX requested changes

2020-10-19 05:14 UTC, hrwX commented on erpnext/agriculture/doctype/destroyed_plant_log/destroyed_plant_log.json
>     "fieldtype": "Link",
Use Dynamic Link for this

2020-10-22 12:51 UTC, hrwX commented
@MyuddinKhatri check if this is a duplicate https://github.com/Bloomstack/erpnext/pull/633

2020-10-28 07:53 UTC, MyuddinKhatri commented
> @MyuddinKhatri check if this is a duplicate #633

@hrwX I checked #633 it is same as what i did in this PR, as well as #633 has some more enhancements so can i close this PR?

2020-10-28 08:22 UTC, closed without merging