fix: fixed the job opening fields
DigiThinkIT/erpnext pull request #619
Opened 2020-10-01 15:41 UTC by nehasacher143

**Task:** https://app.asana.com/0/1188825723958741/1192539579604115/f

**Description:** Just fetching the fields here

2020-10-01 17:50 UTC, hrwX requested changes

2020-10-01 17:50 UTC, hrwX commented on erpnext/hr/doctype/job_opening/job_opening.py
> +	context.result_heading_template = "bloomstack_website/www/career.html"
- There should be a better way of overriding Job Opening html, because this might break someday if the website app is not installed.

2020-10-06 06:12 UTC, nehasacher143 commented
Hey @hrwX, Does this look good?

2020-10-06 06:22 UTC, hrwX approved these changes, later dismissed

2020-10-06 07:10 UTC, hrwX approved these changes

2020-10-06 12:37 UTC, neilLasrado approved these changes

2020-10-06 12:46 UTC, merged