Task item master po
DigiThinkIT/erpnext pull request #642
Opened 2020-10-16 13:40 UTC by nmimsnikhil

ref: https://app.asana.com/0/1197190500424417/1196782244694130

UOM is fetched while move stock from 'item master'

![uom](https://user-images.githubusercontent.com/56826544/96265603-41270080-0fe3-11eb-8726-756fff17e92f.gif)

2020-10-16 16:44 UTC, vishdha requested changes

2020-10-16 16:44 UTC, vishdha commented on erpnext/stock/dashboard/item_dashboard.js
> +			let uom = cur_frm.doc.stock_uom;
@nmimsnikhil  dont use cur_frm.doc.stock_uom instead add stock_uom in items list in stock_dashboard.py
add data-stock_uom in stock_dashboard_list.html

let uom = unescape(element.attr('data-stock_uom'));

2020-10-20 15:01 UTC, hrwX approved these changes

2020-10-20 15:30 UTC, bhattdevarsh approved these changes

2020-10-21 06:58 UTC, merged