fix: Fixed minor changes of statement of account print format
DigiThinkIT/erpnext pull request #667
Opened 2020-10-26 10:51 UTC by meshramsaroj

Description:
Fixed table view and statement date view of portrait mode print format.

Screenshot : 

- Before : 
![image](https://user-images.githubusercontent.com/53329367/97163686-04a79180-17a7-11eb-9d1a-2789dd392e7c.png)

- After:

![image](https://user-images.githubusercontent.com/53329367/97163848-40daf200-17a7-11eb-9d6e-3c2745fc7236.png)

2020-10-26 12:07 UTC, vishdha requested changes

2020-10-26 12:07 UTC, vishdha commented on erpnext/accounts/report/statement_of_account/statement_of_account.html
> +  	}
@meshramsaroj  Remove whitespaces

2020-10-27 04:36 UTC, hrwX commented on erpnext/accounts/report/statement_of_account/statement_of_account.html
> +  	}
```suggestion
  .px-0 {
    	padding-left: 0;
    	padding-right: 0;
  }
```

2020-10-27 04:38 UTC, hrwX commented on erpnext/accounts/report/statement_of_account/statement_of_account.html
> +  }
```suggestion
	.px-0 {
		padding-left: 0;
		padding-right: 0;
    	}
```

2020-10-27 04:38 UTC, hrwX approved these changes

2020-10-27 16:43 UTC, vishdha approved these changes

2020-10-28 08:10 UTC, merged