fix: Autofetch from Job Applicant to Employee
DigiThinkIT/erpnext pull request #668
Opened 2020-10-27 10:44 UTC by bhattdevarsh

[TASK](https://app.asana.com/0/1198503745878277/1197887681109521/f)

![job_applicant_emp](https://user-images.githubusercontent.com/58166671/97291097-764b1280-186f-11eb-81d9-5cdac9b146cf.gif)

2020-10-28 08:16 UTC, hrwX requested changes

2020-10-28 08:16 UTC, hrwX commented on erpnext/patches/v13_0/job_applicant_name_split.py
> +	applicant_list = frappe.get_all("Job Applicant",fields=["name", "applicant_name", ])
```suggestion
	applicant_list = frappe.get_all("Job Applicant",fields=["name", "applicant_name"])
	frappe.reload_doctype("Job Applicant")
```

2020-10-29 10:10 UTC, hrwX requested changes

2020-10-29 10:10 UTC, hrwX commented on erpnext/patches/v13_0/job_applicant_name_split.py
> +	applicant_list = frappe.get_all("Job Applicant",fields=["name", "applicant_name"])
- Reload doc ?

2020-11-11 06:25 UTC, hrwX approved these changes

2020-11-17 12:58 UTC, neilLasrado approved these changes

2020-11-17 12:58 UTC, merged