fix: added field title in harvest
DigiThinkIT/erpnext pull request #671
Opened 2020-10-28 07:25 UTC by nmimsnikhil

ref: https://app.asana.com/0/1198503745878277/1198919160907397

![image](https://user-images.githubusercontent.com/56826544/97404899-d0ee7800-191c-11eb-8909-6d39cd6f5f23.png)

2020-10-28 08:09 UTC, hrwX requested changes

2020-10-28 08:09 UTC, hrwX commented on erpnext/agriculture/doctype/harvest/harvest.json
> -  "status",
- Why was this status field removed ?

2020-10-28 08:09 UTC, hrwX commented on erpnext/agriculture/doctype/harvest/harvest.json
> +  "harvest_location",
- Task description doesn't mention about `harvest_location`.

2020-10-30 07:07 UTC, hrwX requested changes

2020-10-30 07:07 UTC, hrwX commented on erpnext/agriculture/doctype/harvest/harvest.json
> +  "title",
- You need to set this as name field

2020-11-03 08:16 UTC, hrwX approved these changes

2020-11-03 15:49 UTC, neilLasrado approved these changes

2020-11-06 11:55 UTC, sahil28297 approved these changes

2020-11-06 11:55 UTC, merged