feat: improve package doctye and adjust a package
DigiThinkIT/erpnext pull request #678
Opened 2020-10-29 07:08 UTC by MyuddinKhatri

Ref: [Asana/Improve Package Doctype](https://app.asana.com/0/1197190500424417/1194372507071349)
        [Asana/Adjust a Package](https://app.asana.com/0/1197190500424417/1188420657112916)

2020-11-11 06:28 UTC, hrwX requested changes

2020-11-11 06:28 UTC, hrwX commented on erpnext/compliance/doctype/package_tag/package_tag.js
> +							'default': $btn.attr('data-qty')
```suggestion
							default: $btn.attr('data-qty')
```

2020-11-11 06:28 UTC, hrwX commented on erpnext/compliance/doctype/package_tag/package_tag.py
> +		"adjustment_reason": adjustment_reason
```suggestion
			"item_code": item_code,
			"qty": qty,
			"warehouse": warehouse,
			"package_tag": package_tag,
			"batch_no": batch_no,
			"adjustment_reason": adjustment_reason
```

2020-11-18 20:31 UTC, neilLasrado submitted a review, later dismissed

2020-11-25 12:11 UTC, neilLasrado approved these changes

2020-11-25 13:14 UTC, sahil28297 approved these changes

2020-11-25 13:15 UTC, merged