fix: dut date will be >= sales order creation date
DigiThinkIT/erpnext pull request #682
Opened 2020-10-30 11:30 UTC by nmimsnikhil

ref: https://app.asana.com/0/inbox/1192407899689070/1198964881869501/1198976983838235

2020-10-30 12:17 UTC, neilLasrado submitted a review, later dismissed

2020-10-30 17:59 UTC, vishdha submitted a review, later dismissed

2020-11-01 15:26 UTC, hrwX requested changes

2020-11-01 15:26 UTC, hrwX commented on erpnext/selling/doctype/quotation/quotation.py
> +		if target.due_date < getdate(nowdate()):
```suggestion
		if getdate(target.due_date) < getdate(nowdate()):
```

Its always a good practise to wrap a date object in `get_date`.

2020-11-03 12:48 UTC, neilLasrado approved these changes

2020-11-03 15:45 UTC, vishdha approved these changes

2020-11-05 10:39 UTC, hrwX approved these changes

2020-11-06 11:53 UTC, sahil28297 approved these changes

2020-11-06 11:53 UTC, merged