fix: error while starting trip entering odometer value
DigiThinkIT/erpnext pull request #686
Opened 2020-11-02 12:31 UTC by MyuddinKhatri

fix: error while starting trip entering odometer value it was trying to update DN even if it does not exist in Delivery Stop
Ref: [Asana](https://app.asana.com/0/1198992588740629/1198881974636781)

2020-11-02 12:44 UTC, hrwX requested changes

2020-11-02 12:44 UTC, hrwX commented on erpnext/stock/doctype/delivery_trip/delivery_trip.js
> +									if(stop.delivery_note){
```suggestion
								for (let stop of frm.doc.delivery_stops) {
									if (stop.delivery_note) {
```

2020-11-04 10:21 UTC, neilLasrado submitted a review, later dismissed

2020-11-05 09:20 UTC, hrwX requested changes

2020-11-05 09:20 UTC, hrwX commented on erpnext/stock/doctype/delivery_trip/delivery_trip.js
> +									}
```suggestion
								for (let stop of frm.doc.delivery_stops) {
									if (stop.delivery_note) {
										frappe.db.set_value("Delivery Note", stop.delivery_note, "status", "In Transit");
									}
```

2020-11-05 09:20 UTC, hrwX commented on erpnext/stock/doctype/delivery_trip/delivery_trip.py
> +			self.status = status
```suggestion
```

2020-11-05 09:20 UTC, hrwX commented on erpnext/stock/doctype/delivery_trip/delivery_trip.py
>  			elif any(visited_stops):
```suggestion
			else:
```

2020-11-06 06:59 UTC, rvpasari commented on erpnext/stock/doctype/delivery_trip/delivery_trip.js
> +									}
Please put in a comment following javascript conventions explaining what this function call does. Will help better document our code

2020-11-16 12:01 UTC, sahil28297 approved these changes

2020-11-16 12:01 UTC, merged