feat: fetch COA Batch from Source Package Tag into Pick List Item
DigiThinkIT/erpnext pull request #705
Opened 2020-11-05 10:39 UTC by bhattdevarsh

[TASK](https://app.asana.com/0/1198992588740629/1198976222956314/f)

Added COA Batch field in Pick list Item which auto fetched the COA Batch on selection of Source Package Tag 

![coa_batch_picklist](https://user-images.githubusercontent.com/58166671/98230456-29f38700-1f81-11eb-931f-8b0614a2a20f.gif)

2020-11-05 11:39 UTC, hrwX requested changes

2020-11-05 11:39 UTC, hrwX commented on erpnext/stock/doctype/pick_list_item/pick_list_item.json
> +  "coa_batch_no",
- this field should be in the right column.
- Move the package tag field to left column and coa to right one.

2020-11-06 11:34 UTC, hrwX approved these changes

2020-11-06 12:01 UTC, sahil28297 approved these changes

2020-11-06 12:01 UTC, merged