feat: fetch COA Batch from Package Tag into Stock Entry Details
DigiThinkIT/erpnext pull request #706
Opened 2020-11-05 12:09 UTC by bhattdevarsh

[TASK](https://app.asana.com/0/1198992588740629/1198976222956309/f)

![coa_batch_stock_entry](https://user-images.githubusercontent.com/58166671/98239364-dcc9e200-1f8d-11eb-9234-0a6c05167690.gif)

2020-11-05 12:24 UTC, hrwX requested changes

2020-11-05 12:24 UTC, hrwX commented on erpnext/stock/doctype/stock_entry_detail/stock_entry_detail.json
> +  "coa_batch_no",
- Move this field below package_tag

2020-11-06 11:35 UTC, hrwX approved these changes

2020-11-06 12:00 UTC, sahil28297 approved these changes

2020-11-06 12:00 UTC, merged