fix: proper credit card validations for authorisenet
DigiThinkIT/erpnext pull request #725
Opened 2020-11-13 13:57 UTC by sahil28297

[Asana Task](https://app.asana.com/0/1188891334286761/1199162213851361)

![image](https://user-images.githubusercontent.com/37302950/99079583-29449b80-25e6-11eb-9353-5622372e58b2.png)

2020-11-13 14:27 UTC, DeveloperMetal requested changes
Looking good, just small change on the onkeypress event handling

2020-11-13 14:27 UTC, DeveloperMetal commented on erpnext/templates/pages/integrations/authorizenet_checkout.html
> +							onkeypress="return (event.charCode !=8 && event.charCode ==0 || (event.charCode >= 48 && event.charCode <= 57))"
Please don't inline js events put it within authorizenet_checkout.js please. You can either use jquery.on or addeventlistener if you like but keep all js in one place.

2020-11-13 14:27 UTC, DeveloperMetal commented on erpnext/templates/pages/integrations/authorizenet_checkout.html
> +							onkeypress="return (event.charCode !=8 && event.charCode ==0 || (event.charCode >= 48 && event.charCode <= 57))"
Same issue with the inline js. please move to the authorizenet_checkout.js file

2020-11-13 15:49 UTC, DeveloperMetal submitted a review, later dismissed

2020-11-13 21:30 UTC, DeveloperMetal approved these changes

2020-11-15 19:33 UTC, neilLasrado approved these changes

2020-11-16 06:33 UTC, merged