fix: fixed fetching base_grand_total from sales order in production plan
DigiThinkIT/erpnext pull request #728
Opened 2020-11-17 11:30 UTC by MyuddinKhatri

Ref: [Asana](https://app.asana.com/0/1199205301822135/1199109549379709)

![production_plan](https://user-images.githubusercontent.com/53251406/99385037-649cde00-28f6-11eb-8a9b-3acc33735727.gif)

2020-11-18 12:55 UTC, neilLasrado requested changes

2020-11-18 12:55 UTC, neilLasrado commented on erpnext/manufacturing/doctype/production_plan/production_plan.py
> +				'grand_total': data.base_grand_total
why are we mapping Grand Total against Base Grand Total? They are 2 different things.

2020-11-18 14:42 UTC, neilLasrado submitted a review, later dismissed

2020-11-20 07:35 UTC, nmimsnikhil approved these changes

2020-11-23 07:29 UTC, sahil28297 approved these changes

2020-11-23 07:34 UTC, merged