feat: luhn based card validation
DigiThinkIT/erpnext pull request #758
Opened 2020-11-24 19:40 UTC by hrwX

- Card Number validation using luhn algorithm

2020-11-25 04:54 UTC, rvpasari approved these changes, later dismissed

2020-11-25 12:12 UTC, neilLasrado approved these changes, later dismissed

2020-11-25 12:12 UTC, neilLasrado commented
@DeveloperMetal Can you also please review this?

2020-11-26 13:44 UTC, DeveloperMetal requested changes
Looking good, just minor spacing issues

2020-11-26 13:44 UTC, DeveloperMetal commented on erpnext/public/build.json
> +		"public/js/utils/card_validator.js"
fix spacing please

2020-11-26 13:44 UTC, DeveloperMetal commented on erpnext/public/build.json
> +		"public/js/utils/card_validator.js"
Fix spacing here as well

2020-11-27 05:44 UTC, hrwX commented on erpnext/public/build.json
> +		"public/js/utils/card_validator.js"
Changes spaces to tabs

2020-11-27 05:44 UTC, hrwX commented on erpnext/public/build.json
> +		"public/js/utils/card_validator.js"
Changes spaces to tabs

2020-11-27 09:31 UTC, sahil28297 approved these changes

2020-11-27 09:31 UTC, merged