feat: create Production plan from sales order
DigiThinkIT/erpnext pull request #771
Opened 2020-11-30 10:43 UTC by nmimsnikhil

Create production plan from sales order dashboard.
Transfer of function from bloomstack_core to erpnext.
![pp gif](https://user-images.githubusercontent.com/56826544/100600201-f9580080-3326-11eb-8b69-871ad421b486.gif)

![multiple pp](https://user-images.githubusercontent.com/56826544/100599959-b138de00-3326-11eb-9352-f60bcd7d29ff.png)

2020-11-30 10:51 UTC, nmimsnikhil commented on erpnext/selling/doctype/sales_order/sales_order.py
> +	return doc
create Production plan and assign values to the items.

2020-11-30 10:51 UTC, nmimsnikhil commented on erpnext/selling/doctype/sales_order/sales_order.py
> +
Pull from bloomstack_core.

2020-11-30 10:51 UTC, nmimsnikhil commented on erpnext/selling/doctype/sales_order/sales_order.py
> +	return created_orders
To create different production plan of multiples sales order.

2020-11-30 10:51 UTC, nmimsnikhil commented on erpnext/selling/doctype/sales_order/sales_order_list.js
> +		};
Pull from bloomstack_core.

2020-11-30 10:51 UTC, nmimsnikhil commented on erpnext/selling/doctype/sales_order/sales_order_list.js
> +		listview.page.add_actions_menu_item(__('Email'), send_email_action, true);
pull from bloomstack_core

2020-11-30 11:31 UTC, vishdha requested changes

2020-11-30 11:31 UTC, vishdha commented on erpnext/selling/doctype/sales_order/sales_order.py
> +"""
@nmimsnikhil it should be inside the function not outside

2020-11-30 11:44 UTC, vishdha requested changes

2020-11-30 11:44 UTC, vishdha commented on erpnext/selling/doctype/sales_order/sales_order.py
> +"""
it should be inside the function

2020-11-30 12:15 UTC, vishdha requested changes

2020-11-30 12:15 UTC, vishdha commented on erpnext/selling/doctype/sales_order/sales_order_list.js
> +					method: "bloomstack_core.utils.get_contact",
@nmimsnikhil here is a dependency with bloomstack module. move this stuff to erpnext too

2020-11-30 12:15 UTC, vishdha commented on erpnext/selling/doctype/sales_order/sales_order_list.js
> +							args: { "doctype": doctype, "docs": selected_docs },
@nmimsnikhil here is a dependency with bloomstack module. move this stuff to erpnext too

2020-11-30 18:29 UTC, rvpasari requested changes
All these functions are elaborate, and as specified by Himanshu in the group, will require comments and docstrings. Ideally, a dev should not have to enter the function definition and read through what the function is doing and what value (and type of value) its returning. All of it can be put in the docstring

2020-12-01 08:38 UTC, rvpasari requested changes
Please update all the functions marked in green with docstrings and comments. (When something shows up highlighted in green, it automatically means that the code snippet has been added/modified by the dev).

2020-12-02 06:42 UTC, vishdha requested changes

2020-12-02 06:42 UTC, vishdha commented on erpnext/selling/doctype/sales_order/sales_order.py
> +			"sales_order": "SAL-ORD-2020-00293",
@nmimsnikhil Remove this and make the appropriate change here

2020-12-04 10:08 UTC, hrwX requested changes

2020-12-04 10:08 UTC, hrwX commented on erpnext/selling/doctype/sales_order/sales_order_list.js
> +							method: "erpnext.utils.get_document_links",
Check the frappe.call method

2020-12-04 10:08 UTC, hrwX commented on erpnext/selling/doctype/sales_order/sales_order.py
> +			})
```suggestion
		bom_no = frappe.get_value("BOM", {"item": target.item_code, "is_default": 1})
```

2020-12-04 10:08 UTC, hrwX commented on erpnext/selling/doctype/sales_order/sales_order.py
> +			target.total_workstations = frappe.db.count("BOM Operation", {"parent": bom_no, "workstation": ["!=", ""]})
```suggestion
			target.total_workstations = frappe.db.count("BOM Operation", {"parent": bom_no, "workstation": ["is", "set"]})
```

2020-12-04 10:08 UTC, hrwX commented on erpnext/selling/doctype/sales_order/sales_order.py
> +			distinct=True)
```suggestion
		pick_lists = frappe.get_all("Pick List", filters=[
				["Pick List", "docstatus", "<", 2],
				["Pick List Item", "sales_order", "=", order]
			], distinct=True)
```

2020-12-04 10:08 UTC, hrwX commented on erpnext/selling/doctype/sales_order/sales_order.py
> +		pick_lists = [item.name for item in pick_lists if item.name]
```suggestion
```
You dont have to loop over it again. ORM will always return data. Use `as_list` param for get_all

2020-12-04 10:08 UTC, hrwX commented on erpnext/selling/doctype/sales_order/sales_order.py
> +		sales_invoices = [item.name for item in sales_invoices if item.name]
Similar to the above change

2020-12-04 10:08 UTC, hrwX commented on erpnext/selling/doctype/sales_order/sales_order.py
> +		delivery_notes = [item.name for item in delivery_notes if item.name]
Same changes as suggested above

2020-12-05 09:14 UTC, hrwX approved these changes

2020-12-05 11:41 UTC, vishdha approved these changes

2020-12-06 07:58 UTC, merged