refactor: modified overproduction limit message
DigiThinkIT/erpnext pull request #776
Opened 2020-12-01 12:23 UTC by vishdha

TASK ID: [ASANA](https://app.asana.com/0/1192407894480744/1199358689152854)

2020-12-01 14:11 UTC, neilLasrado requested changes

2020-12-01 14:11 UTC, neilLasrado commented on erpnext/manufacturing/doctype/work_order/work_order.py
> +				frappe.throw(_("Overproduction percentage limit has been surpassed, please adjust completed qty or change over production percentages in Manufacturing Settings."))
Can you also show the max_allowed_qty_for_wo in the Error?

Something along the lines of, 'Maximum Allowed Qty is max_allowed_qty_for_wo'

2020-12-02 06:02 UTC, hrwX submitted a review, later dismissed

2020-12-02 08:26 UTC, sahil28297 approved these changes

2020-12-02 08:27 UTC, merged

2020-12-02 08:29 UTC, sahil28297 commented
@vishdha send a PR on develop branch as well