feat: Production plan status is set to Material Received on the basis of Material Request Received
DigiThinkIT/erpnext pull request #788
Opened 2020-12-03 08:10 UTC by MyuddinKhatri

Production plan status is set to Material Received on the basis of Material Request Received

Ref: [Asana](https://app.asana.com/0/1192407896547052/1199138927951885)

![production_plan_status](https://user-images.githubusercontent.com/53251406/100981643-10882f80-356d-11eb-894c-36b84db7c78b.gif)

2020-12-05 09:33 UTC, hrwX requested changes

2020-12-05 09:33 UTC, hrwX commented on erpnext/buying/doctype/purchase_order_item/purchase_order_item.json
> +   "label": "Production Plan item"
```suggestion
   "label": "Production Plan Item"
```

2020-12-05 09:33 UTC, hrwX commented on erpnext/manufacturing/doctype/production_plan/production_plan.py
> +	def set_status(self, update=None):
```suggestion
	def set_status(self, update=None):
```
Update parameter is not used.

2020-12-05 09:33 UTC, hrwX commented on erpnext/manufacturing/doctype/production_plan/production_plan.py
> +		self.set_status(update=True)
```suggestion
		self.set_status()
```

2020-12-05 09:33 UTC, hrwX commented on erpnext/manufacturing/doctype/production_plan/production_plan.py
> +		self.set_status(update=True)
```suggestion
		self.set_status()
```

2020-12-05 11:38 UTC, vishdha requested changes

2020-12-05 11:38 UTC, vishdha commented on erpnext/manufacturing/doctype/production_plan/production_plan.py
> +			self.db_set("status", "Material Received")
@MyuddinKhatri  This not need because you already calling it on line number 222

2020-12-05 16:39 UTC, hrwX submitted a review, later dismissed

2020-12-06 07:56 UTC, hrwX commented
@MyuddinKhatri  resolve conflicts

2020-12-06 12:38 UTC, hrwX approved these changes

2020-12-07 04:51 UTC, sahil28297 approved these changes

2020-12-07 04:52 UTC, merged