fix: creating sales invoice after capturing affirm payment
DigiThinkIT/erpnext pull request #793
Opened 2020-12-03 11:42 UTC by rvpasari

2020-12-04 04:55 UTC, hrwX requested changes

2020-12-04 04:55 UTC, hrwX commented on erpnext/erpnext_integrations/doctype/affirm_settings/affirm_settings.py
> +def make_sales_invoice(sales_order_name):
Can you change the name of the function ??
It'll create a lot of confusion

2020-12-04 18:06 UTC, sahil28297 approved these changes

2020-12-06 11:39 UTC, hrwX approved these changes

2020-12-07 03:20 UTC, vishdha approved these changes

2020-12-07 05:08 UTC, merged