fix:  fixed autonaming item without default company being triggered on save
DigiThinkIT/erpnext pull request #802
Opened 2020-12-07 05:28 UTC by MyuddinKhatri

Ref: [Asana](https://app.asana.com/0/1188592895233593/1198958632787845)

2020-12-07 06:23 UTC, hrwX requested changes

2020-12-07 06:23 UTC, hrwX commented on erpnext/stock/doctype/item/item.py
> +		item_code = "-".join(params)
```suggestion
```

2020-12-07 06:23 UTC, hrwX commented on erpnext/stock/doctype/item/item.py
> +		item_code = "-".join(params)
```suggestion
	
	item_code = "-".join(params)
```

2020-12-07 06:55 UTC, neilLasrado approved these changes

2020-12-08 04:05 UTC, vishdha approved these changes

2020-12-09 05:33 UTC, hrwX approved these changes

2020-12-09 05:34 UTC, merged