fix: Task package tag
DigiThinkIT/erpnext pull request #812
Opened 2020-12-09 06:48 UTC by nmimsnikhil

[Asana](https://app.asana.com/0/1192407899754728/1199386726415517)
![image](https://user-images.githubusercontent.com/56826544/101594723-2c318100-3a18-11eb-8e22-e65d64300009.png)

2020-12-09 09:16 UTC, rvpasari approved these changes, later dismissed

2020-12-10 03:38 UTC, hrwX requested changes

2020-12-10 03:38 UTC, hrwX commented on erpnext/patches/v13_0/update_global_search.py
> +    frappe.reload_doc("desk", "doctype", "global_search_settings")
```suggestion
```

2020-12-10 03:38 UTC, hrwX commented on erpnext/patches/v13_0/update_global_search.py
> +    update_global_search_doctypes()
- add `Package Tag` using get_doc

2020-12-10 03:38 UTC, hrwX commented on erpnext/hooks.py
> +		{"doctype": "Package Tag", "index": 47},
Add this above Pick List

2020-12-10 13:15 UTC, hrwX requested changes

2020-12-10 13:15 UTC, hrwX commented on erpnext/patches/v13_0/update_global_search.py
> +    doc.save()
doc.allowed_in_global_search.insert(18, {
	"document_type": "Package Tag",
	"idx":  18
})
doc.save()

2020-12-14 04:34 UTC, hrwX approved these changes

2020-12-14 08:33 UTC, sahil28297 approved these changes

2020-12-14 08:33 UTC, merged