Attached name field mod
DigiThinkIT/erpnext pull request #827
Opened 2020-12-14 14:40 UTC by hitenshKharva

Ref: [https://app.asana.com/0/1199082161983365/1199376239709583](url)

Edited modification date for job applicant doctype in reference to previous merged [PR](https://github.com/Bloomstack/erpnext/pull/823)

2020-12-14 18:08 UTC, hrwX commented
@hitenshKharva resolve conflicts and change the PR title

2020-12-15 04:54 UTC, hrwX commented
Create a new PR you have pushed to the merged branch. Else rebase this branch.

2020-12-16 08:47 UTC, vishdha requested changes

2020-12-16 08:47 UTC, vishdha commented on erpnext/hr/doctype/job_applicant/job_applicant.js
> +		frm.set_df_property('resume_attachment', 'reqd', frm.is_new() ? 0 : 1)
```suggestion
		frm.toggle_reqd('resume_attachment', !frm.is_new());
```

2020-12-16 08:48 UTC, vishdha requested changes
@hitenshKharva  Remove conflicts

2020-12-16 09:06 UTC, vishdha requested changes
@hitenshKharva You need to do the same for webform.

2020-12-17 10:21 UTC, neilLasrado commented
@hitenshKharva can you please resolve the merge conflicts?

2020-12-17 10:28 UTC, hitenshKharva commented
@neilLasrado @vishdha Closing this branch. New updated PRs for the same have been raised and merged on develop and staging.

2020-12-17 10:28 UTC, closed without merging