fix: auto fetch Batch No from Source Package Tag to Pick List Item
DigiThinkIT/erpnext pull request #841
Opened 2020-12-17 08:06 UTC by bhattdevarsh

- on selection of `source_package_tag` it will auto fetch batch no. instead of on selection of 'package_tag'

![pick_list_batch_no](https://user-images.githubusercontent.com/58166671/102460260-bf983100-406c-11eb-94f3-5994165188cb.gif)

2020-12-18 05:42 UTC, hrwX requested changes

2020-12-18 05:42 UTC, hrwX commented on erpnext/stock/doctype/pick_list/pick_list.js
> +						frappe.throw(__(`The "${row.source_package_tag}" tag is linked to a different batch (${r.batch_no})`));
```suggestion
						frappe.throw(__("The {0} tag is linked to a different batch {1}.", [row.source_package_tag, r.batch_no]));
```

2020-12-22 07:27 UTC, hrwX approved these changes

2020-12-23 05:01 UTC, sahil28297 approved these changes

2020-12-23 05:01 UTC, merged