fix: changed error message when creating PP from SO
DigiThinkIT/erpnext pull request #842
Opened 2020-12-17 10:02 UTC by nmimsnikhil

changed error message when creating Production Plan from Sales Order using Action button.
![image](https://user-images.githubusercontent.com/56826544/102473032-f7a77000-407c-11eb-9cf3-8fbe59e73fa3.png)

2020-12-18 10:15 UTC, hrwX requested changes

2020-12-18 10:15 UTC, hrwX commented on erpnext/manufacturing/doctype/production_plan/production_plan.py
> +			frappe.throw(_("In Sales Order '{0}' Please set default BOM for Item {1}".format(sales_order,items)))
Display an ordered list

2020-12-21 05:34 UTC, hrwX requested changes

2020-12-21 05:34 UTC, hrwX commented on erpnext/manufacturing/doctype/production_plan/production_plan.py
> +		items = []
```suggestion
		items = []
		show_default_bom_msg = False
```

2020-12-21 05:34 UTC, hrwX commented on erpnext/manufacturing/doctype/production_plan/production_plan.py
> +				sales_order = d.sales_order
```suggestion
				show_default_bom_msg = True

```

2020-12-21 05:34 UTC, hrwX commented on erpnext/manufacturing/doctype/production_plan/production_plan.py
> +		if sales_order:
```suggestion
		if show_default_bom_msg:
```

2020-12-21 05:34 UTC, hrwX commented on erpnext/manufacturing/doctype/production_plan/production_plan.py
> +			items = list(dict.fromkeys(items))
`items` is already a list

2020-12-21 05:34 UTC, hrwX commented on erpnext/manufacturing/doctype/production_plan/production_plan.py
> +			frappe.throw(_("In Sales Order '{0}' Please set default BOM for Item: <ol><li>{1}</li></ol>".format(sales_order,'<li>'.join(items))))
```suggestion
			frappe.throw(_("In Sales Order '{0}' Please set default BOM for Item: <ol>{1}</ol>".format(sales_order,'<li>'.join(items))))
```

2020-12-21 12:04 UTC, nmimsnikhil commented on erpnext/manufacturing/doctype/production_plan/production_plan.py
> +			frappe.throw(_("In Sales Order '{0}' Please set default BOM for Item: <ol><li>{1}</li></ol>".format(sales_order,'<li>'.join(items))))
![image](https://user-images.githubusercontent.com/56826544/102775401-cd262180-43b2-11eb-93d5-6762898d5261.png)

2020-12-21 12:05 UTC, nmimsnikhil commented on erpnext/manufacturing/doctype/production_plan/production_plan.py
> +			frappe.throw(_("In Sales Order '{0}' Please set default BOM for Item: <ol><li>{1}</li></ol>".format(sales_order,'<li>'.join(items))))
if i remove <li> after <ol>

2020-12-23 12:22 UTC, hrwX approved these changes

2020-12-24 05:04 UTC, sahil28297 approved these changes

2020-12-24 05:04 UTC, merged