feat: added new field title in bom
DigiThinkIT/erpnext pull request #847
Opened 2020-12-18 10:57 UTC by nmimsnikhil

[Asana](https://app.asana.com/0/1192407899754728/1199576473848633/f)
Rename BOM title
![image](https://user-images.githubusercontent.com/56826544/102607159-d06ca380-414d-11eb-84a6-289984a21e56.png)

2020-12-18 12:37 UTC, hrwX requested changes

2020-12-18 12:37 UTC, hrwX commented on erpnext/manufacturing/doctype/bom/bom.json
> +   "hidden": 1,
Do not hide this

2020-12-18 12:38 UTC, hrwX requested changes

2020-12-18 12:38 UTC, hrwX commented on erpnext/patches/v13_0/update_title_field_in_bom.py
> +    	frappe.db.set_value("BOM", bom.name, "title", bom.item_name, update_modified=False)
use a simple db.sql to copy from one column to another

2020-12-19 07:20 UTC, hrwX approved these changes

2020-12-21 07:33 UTC, sahil28297 approved these changes

2020-12-21 07:34 UTC, merged