feat: show list of suppliers while creating purchase order from material request
DigiThinkIT/erpnext pull request #853
Opened 2020-12-21 09:48 UTC by MyuddinKhatri

Ref: [Asana](https://app.asana.com/0/1192407896547052/1199536704671393)

2020-12-22 07:31 UTC, hrwX requested changes

2020-12-22 07:31 UTC, hrwX commented on erpnext/stock/doctype/material_request/material_request.py
> +# @frappe.whitelist()
```suggestion
@frappe.whitelist()
```

2020-12-22 07:31 UTC, hrwX commented on erpnext/stock/doctype/material_request/material_request.py
> +		""".format(', '.join(['%s']*len(item_list))),tuple(item_list))
```suggestion
	data = frappe.db.sql("""select supplier
		from `tabItem Supplier`
		where parent in ({0})
		""".format(', '.join(['%s']*len(item_list))),tuple(item_list))
```
Use ORM

2020-12-22 07:31 UTC, hrwX commented on erpnext/stock/doctype/material_request/material_request.py
> +		""".format(', '.join(['%s']*len(item_list))), {'item': tuple(item_list), 'supplier': supplier})
Use ORM

2020-12-22 11:15 UTC, rvpasari requested changes

2020-12-22 11:15 UTC, rvpasari commented on erpnext/stock/doctype/material_request/material_request.py
> +	doc = frappe.get_doc("Material Request", doc)
Docstring/comments

2020-12-23 12:35 UTC, hrwX approved these changes

2020-12-24 05:03 UTC, sahil28297 approved these changes

2020-12-24 05:03 UTC, merged