feat: added batch_no hidden field in purchase receipt
DigiThinkIT/erpnext pull request #860
Opened 2020-12-23 12:00 UTC by nmimsnikhil

![image](https://user-images.githubusercontent.com/56826544/102994156-87995e00-4544-11eb-95d3-8f4a962738b0.png)

2020-12-23 12:25 UTC, hrwX requested changes

2020-12-23 12:25 UTC, hrwX commented on erpnext/patches/v13_0/update_batch_no_in_purchase_receipt.py
> +    docs = frappe.get_all("Purchase Receipt")
```suggestion
    docs = frappe.get_all("Purchase Receipt", fields=["name", "batch_no"])
```

2020-12-23 12:25 UTC, hrwX commented on erpnext/stock/doctype/purchase_receipt/purchase_receipt.json
> +   "in_list_view": 1,
```suggestion
   "in_list_view": 0,
```

2020-12-24 03:37 UTC, hrwX approved these changes

2020-12-24 04:59 UTC, sahil28297 approved these changes

2020-12-24 05:00 UTC, merged