fix: change labels in company master
DigiThinkIT/erpnext pull request #874
Opened 2020-12-29 04:55 UTC by nmimsnikhil

[Asana](https://app.asana.com/0/1192407899754728/1199513885200605/f)

![image](https://user-images.githubusercontent.com/56826544/103259619-2d731f80-49c0-11eb-9f73-2364481e5e12.png)

2020-12-29 11:20 UTC, hrwX requested changes

2020-12-29 11:20 UTC, hrwX commented on erpnext/setup/doctype/company/company.json
> +   "label": "Purchase Discounts",
- fieldnames are always singular

2020-12-29 11:20 UTC, hrwX commented on erpnext/setup/doctype/company/company.json
> +   "label": "Sales Discounts",
- fieldnames are always singular

2021-01-04 07:08 UTC, hrwX approved these changes

2021-01-04 08:07 UTC, sahil28297 approved these changes

2021-01-04 08:07 UTC, merged