fix: made item_code and alernative_item_code mandatory
DigiThinkIT/erpnext pull request #894
Opened 2021-01-04 11:45 UTC by nmimsnikhil

[Asana](https://app.asana.com/0/1192407899754728/1199706321989639/f)
![item alternative](https://user-images.githubusercontent.com/56826544/103531914-4001c300-4eb0-11eb-858b-df9abfa962fd.gif)

2021-01-04 13:07 UTC, hrwX approved these changes, later dismissed

2021-01-05 05:58 UTC, vishdha requested changes

2021-01-05 05:58 UTC, vishdha commented on erpnext/stock/doctype/item_alternative/item_alternative.json
> + "modified_by": "nikhil1@bloomstack.com",
@nmimsnikhil  Remove this Change

2021-01-05 06:07 UTC, vishdha approved these changes

2021-01-05 12:14 UTC, hrwX approved these changes

2021-01-08 05:50 UTC, rvpasari approved these changes

2021-01-08 10:08 UTC, sahil28297 approved these changes

2021-01-08 10:08 UTC, merged