feat: status update for production plan if material request type is manufacture
DigiThinkIT/erpnext pull request #902
Opened 2021-01-05 08:31 UTC by MyuddinKhatri

Ref: [Asana](https://app.asana.com/0/1192407896547052/1199693860932069)

2021-01-05 12:10 UTC, nmimsnikhil commented
@MyuddinKhatri please uload 'gif' for better understanding.

2021-01-07 07:29 UTC, rvpasari commented on erpnext/manufacturing/doctype/production_plan/production_plan.py
> +def update_per_received_in_production_plan(purchase_receipt):
This is a function called from the frontend. Docstrings should be in format

2021-01-07 08:15 UTC, rvpasari approved these changes

2021-01-07 08:16 UTC, rvpasari requested changes

2021-01-07 08:16 UTC, rvpasari commented on erpnext/manufacturing/doctype/production_plan/production_plan.py
> +def update_per_received_in_production_plan(purchase_receipt):
Please correct the details in the docstring - it doesn't reflect what the function is doing

2021-01-08 06:05 UTC, vishdha reviewed
@MyuddinKhatri. On cancel purchase receipt it not updating the production plan status it still shows material received. if you need help to connect concern person

2021-01-08 06:48 UTC, MyuddinKhatri commented
> @MyuddinKhatri. On cancel purchase receipt it not updating the production plan status it still shows material received. if you need help to connect concern person



![screencast-bloomstack_demo_8000-2021 01 08-11_57_34](https://user-images.githubusercontent.com/53251406/103983539-6d4dba00-51ab-11eb-8588-db54be4f44e0.gif)

2021-01-11 06:38 UTC, hrwX requested changes

2021-01-11 06:38 UTC, hrwX commented on erpnext/manufacturing/doctype/production_plan/production_plan.py
> +				data.db_update()
- Do not update in for loop.
- Update once the for loop is done

2021-01-11 06:38 UTC, hrwX commented on erpnext/manufacturing/doctype/production_plan/production_plan.py
> +	all_received =[item.per_received for item in production_plan.mr_items if item.material_request_type == "Purchase"]
```suggestion
	all_received = [item.per_received for item in production_plan.mr_items if item.material_request_type == "Purchase"]
```

2021-01-11 06:38 UTC, hrwX commented on erpnext/manufacturing/doctype/production_plan/production_plan.py
> +	produced_qty =[item.produced_qty for item in production_plan.mr_items if item.material_request_type == "Manufacture" and item.requested_qty == item.produced_qty]
```suggestion
	produced_qty = [item.produced_qty for item in production_plan.mr_items if item.material_request_type == "Manufacture" and item.requested_qty == item.produced_qty]
```

2021-01-11 06:58 UTC, MyuddinKhatri commented on erpnext/manufacturing/doctype/production_plan/production_plan.py
> +				data.db_update()
then produced qty is not getting update

2021-01-11 08:21 UTC, hrwX commented on erpnext/manufacturing/doctype/production_plan/production_plan.py
> +				data.db_update()
Once you update all the rows in child table, then only update the doc.

2021-01-12 05:45 UTC, hrwX approved these changes

2021-01-12 06:33 UTC, sahil28297 approved these changes

2021-01-12 06:33 UTC, merged