chore: rename bank reconciliation to bank clearance
DigiThinkIT/erpnext pull request #904
Opened 2021-01-05 09:10 UTC by vishdha

Rename Bank Reconciliation to Bank Clearance.

2021-01-05 12:18 UTC, nmimsnikhil commented on erpnext/patches/v12_0/rename_bank_reconciliation.py
> +from frappe.model.utils.rename_field import rename_field
```suggestion

```

2021-01-05 12:20 UTC, nmimsnikhil commented on erpnext/patches/v12_0/rename_bank_reconciliation.py
> +from frappe.model.utils.rename_field import rename_field
codacy failed.

2021-01-11 06:40 UTC, hrwX requested changes

2021-01-11 06:40 UTC, hrwX commented on erpnext/patches/v12_0/rename_bank_reconciliation_fields.py
> +	frappe.reload_doc("Accounts", "doctype", "Bank Clearance")
Can we merge the two patches

2021-01-12 06:28 UTC, hrwX approved these changes

2021-01-12 06:30 UTC, sahil28297 approved these changes

2021-01-12 06:30 UTC, merged