feat: Early Payment Discounting
DigiThinkIT/erpnext pull request #914
Opened 2021-01-06 06:54 UTC by vishdha

TASK : [ASANA](https://app.asana.com/0/1192407894480744/1199000235912990)
![Peek 2021-01-04 10-19](https://user-images.githubusercontent.com/6947417/103738487-1369ba80-501a-11eb-84ae-e62fe80c477a.gif)

2021-01-11 06:50 UTC, hrwX requested changes

2021-01-11 06:50 UTC, hrwX commented on erpnext/accounts/doctype/payment_entry/payment_entry.js
> +		var base_total_discounted_amount = 0.0;
```suggestion
		let total_discounted_amount = 0.0;
		let base_total_discounted_amount = 0.0;
```

2021-01-11 06:50 UTC, hrwX commented on erpnext/accounts/doctype/payment_entry/payment_entry.py
> +				against_account =  self.paid_to
```suggestion
				against_account = self.paid_to
```

2021-01-12 06:26 UTC, hrwX approved these changes

2021-01-12 06:28 UTC, sahil28297 approved these changes

2021-01-12 06:28 UTC, merged