feat: API to List all Expense Claims for given Employee
DigiThinkIT/erpnext pull request #927
Opened 2021-01-07 12:50 UTC by bhattdevarsh

[TASK](https://app.asana.com/0/inbox/1192407897688003/1199514490117781/1199514495378656)

Added New API to List all the Expense claim created By the Given Employee

2021-01-07 13:01 UTC, hrwX requested changes

2021-01-07 13:01 UTC, hrwX commented on erpnext/hr/doctype/expense_claim/expense_claim.py
> +def list_expense_claim(user):
```suggestion
def get_expense_claims(user):
```

2021-01-07 13:01 UTC, hrwX commented on erpnext/hr/doctype/expense_claim/expense_claim.py
> +		return "Employee's E-mail ID Not Found, Please Add 'Company Email' Under 'Employee' Document"
```suggestion
		return __("Employee's E-mail ID Not Found, Please Add 'Company Email' Under 'Employee' Document.")
```

2021-01-07 13:01 UTC, hrwX commented on erpnext/hr/doctype/expense_claim/expense_claim.py
> +	claim_list = frappe.get_list("Expense Claim", filters={"title": employee})
```suggestion
	expense_claims = frappe.get_all("Expense Claim", filters={"title": employee}, fields=["*"])
```

2021-01-07 13:01 UTC, hrwX commented on erpnext/hr/doctype/expense_claim/expense_claim.py
> +		expense_claim.append(frappe.get_doc("Expense Claim", claim))
`
```suggestion
```

2021-01-07 13:01 UTC, hrwX commented on erpnext/hr/doctype/expense_claim/expense_claim.py
> +	claim_list = frappe.get_list("Expense Claim", filters={"title": employee})
- Add filter for Employee Link field in Expense Claim and not title

2021-01-07 13:01 UTC, hrwX commented on erpnext/hr/doctype/expense_claim/expense_claim.py
> +	return expense_claim
```suggestion
	return expense_claims
```

2021-01-08 07:05 UTC, bhattdevarsh commented on erpnext/hr/doctype/expense_claim/expense_claim.py
> +		expense_claim.append(frappe.get_doc("Expense Claim", claim))
we need Child table as well, fields=[*] is not giving the required output so we had to iterate it through loop

2021-01-11 06:54 UTC, hrwX requested changes

2021-01-11 06:54 UTC, hrwX commented on erpnext/hr/doctype/expense_claim/expense_claim.py
> +	employee = frappe.get_value("Employee", {"company_email": user}, "name" )
```suggestion
	employee = frappe.get_value("Employee", {"company_email": user}, "name")
```

2021-01-11 06:54 UTC, hrwX commented on erpnext/hr/doctype/expense_claim/expense_claim.py
> +		return "No Claim Found For "+ employee
```suggestion
		return _("No Claim Found for {0}.").format(employee)
```

2021-01-11 06:54 UTC, hrwX commented on erpnext/hr/doctype/expense_claim/expense_claim.py
> +	expense_claims = frappe.get_all("Expense Claim", filters={"employee": employee})
```suggestion
	expense_claims = frappe.get_all("Expense Claim", filters={"employee": employee}. fields=["*"])
```

2021-01-11 06:54 UTC, hrwX commented on erpnext/hr/doctype/expense_claim/expense_claim.py
> +		expense_claim_list.append(frappe.get_doc("Expense Claim", claim))
You do not need to do a `get_doc` since you can get all the fields in `get_all` itself

2021-01-12 11:43 UTC, hrwX requested changes

2021-01-12 11:43 UTC, hrwX commented on erpnext/hr/doctype/expense_claim/expense_claim.py
> +	if amount: expense_claim_details.update({"amount":amount})
```suggestion
	if expense_date:
		expense_claim_details.update({"expense_date":expense_date})
		
	if description:
		expense_claim_details.update({"description":description})
		
	if expense_claim_type:
		expense_claim_details.update({"expense_claim_type":expense_claim_type})
		
	if amount:
		expense_claim_details.update({"amount":amount})
		
```

2021-01-12 11:43 UTC, hrwX commented on erpnext/hr/doctype/expense_claim/expense_claim.py
> +	ARGS:
```suggestion

	Args:
```

2021-01-12 11:43 UTC, hrwX commented on erpnext/hr/doctype/expense_claim/expense_claim.py
> +def update_expense_claim(expense_claim_details_name, expense_date = None, expense_claim_type = None, description = None, amount = None):
```suggestion
def update_expense_claim(expense_claim_detail, expense_date=None, expense_claim_type=None, description=None, amount=None):
```

2021-01-12 11:43 UTC, hrwX commented on erpnext/hr/doctype/expense_claim/expense_claim.py
> +	expense_claim_details = frappe.get_doc("Expense Claim Detail", expense_claim_details_name)
```suggestion
	expense_claim_detail = frappe.get_doc("Expense Claim Detail", expense_claim_detail)
	
```

2021-01-12 11:43 UTC, hrwX commented on erpnext/hr/doctype/expense_claim/expense_claim.py
> +	expense_claim_details_name: Expense Claim Details ID to upddate perticular child data (This Data Can be found in 'list_expense_claims' api as 'name' key)
```suggestion
	expense_claim_detail: Expense Claim Details ID to upddate perticular child data (This Data Can be found in 'list_expense_claims' api as 'name' key)
```

2021-01-12 11:56 UTC, hrwX commented on erpnext/hr/doctype/expense_claim/expense_claim.py
> +								)
```suggestion
	expense_claims = frappe.get_all("Expense Claim", filters={
		"employee": employee
	}, fields=["name", "employee_name", "approval_status", "expense_approver", "`tabExpense Claim Detail`.*"])
```

2021-01-12 11:58 UTC, hrwX commented on erpnext/hr/doctype/expense_claim/expense_claim.py
> +	employee = frappe.get_value("Employee", {"company_email": user}, "name")
```suggestion
	employee = frappe.db.exists("Employee", {"company_email": user})
```

2021-01-12 12:50 UTC, hrwX commented on erpnext/hr/doctype/expense_claim/expense_claim.py
> +	# updated_values
```suggestion

```

2021-01-12 12:51 UTC, hrwX approved these changes, later dismissed

2021-01-14 07:05 UTC, sahil28297 approved these changes

2021-01-14 07:05 UTC, merged