feat: added package tag quantity to package tag
DigiThinkIT/erpnext pull request #933
Opened 2021-01-08 12:04 UTC by MyuddinKhatri

Ref:[Asana](https://app.asana.com/0/1192407896547052/1199607948060389)

![screenshot-bloomstack_demo_8000-2021 01 08-17_33_23](https://user-images.githubusercontent.com/53251406/104013690-cc292880-51d7-11eb-9e33-1a29ba59d211.png)

2021-01-11 06:58 UTC, hrwX requested changes

2021-01-11 06:58 UTC, hrwX commented on erpnext/patches/v13_0/set_package_tag_qty_in_package_tag.py
> +			frappe.db.set_value("Package Tag", package_tag.name, "package_tag_qty", package_tag_qty)
Use SQL directly since there will be many entries in Stock Ledger Entry

2021-01-12 05:42 UTC, hrwX requested changes

2021-01-12 05:42 UTC, hrwX commented on erpnext/patches/v13_0/set_package_tag_qty_in_package_tag.py
> +		if package_tag_qty[0].qty:
```suggestion
		if package_tag_qty and package_tag_qty[0].qty:
```

2021-01-12 05:48 UTC, hrwX approved these changes

2021-01-12 06:20 UTC, sahil28297 approved these changes

2021-01-12 06:24 UTC, merged