fix: changed modified_time for bom.json
DigiThinkIT/erpnext pull request #988
Opened 2021-01-27 16:14 UTC by MyuddinKhatri

2021-01-28 11:23 UTC, hrwX requested changes

2021-01-28 11:23 UTC, hrwX commented on erpnext/manufacturing/doctype/bom/bom.json
> + "modified": "2021-01-08 03:02:32.714649",
```suggestion
 "modified": "2021-01-28 03:02:32.714649",
```

2021-01-28 11:28 UTC, hrwX commented
@MyuddinKhatri What does this PR do ?

2021-01-28 11:56 UTC, MyuddinKhatri commented
> @MyuddinKhatri What does this PR do ?

Avg_manufactured_qty field was not available in doctype on garden sites though it was merge and deployed, other changes were reflected.

2021-01-29 07:59 UTC, sahil28297 approved these changes

2021-01-29 08:00 UTC, merged