feat: Update rate of submiited purchase receipt
DigiThinkIT/erpnext pull request #993
Opened 2021-01-29 09:50 UTC by vishdha

TASK ID: [ASANA](https://app.asana.com/0/1199693776410411/1199705081069234)

![Peek 2021-01-29 15-19](https://user-images.githubusercontent.com/6947417/106259592-77605700-6245-11eb-942c-2172a3b83b1c.gif)

2021-02-11 14:30 UTC, vishdha commented
@sahil28297 dti-bot needed for testing the pr

2021-02-12 06:59 UTC, sahil28297 commented
@dti-deploy create instance

2021-02-12 07:08 UTC, dti-deploy commented
An error occurred while executing the following command:
					```bench migrate```
You may manually fix the issue using: `ssh 128.199.20.135 -l frappe`
					Traceback:
```b'Migrating site1.local\nExecuting frappe.patches.v12_0.change_existing_dashboard_chart_filters in site1.local (_1bd3e0294da19198)\nSuccess: Done in 0.264s\nExecuting frappe.patches.v12_0.set_existing_dashboard_charts_as_public in site1.local (_1bd3e0294da19198)\nSuccess: Done in 0.664s\nExecuting frappe.patches.v12_0.remove_title_from_search_fields in site1.local (_1bd3e0294da19198)\nSuccess: Done in 4.771s\nExecuting erpnext.patches.v13_0.set_per_picked_in_sales_order in site1.local (_1bd3e0294da19198)\nSuccess: Done in 2.091s\nExecuting erpnext.patches.v13_0.job_applicant_name_split in site1.local (_1bd3e0294da19198)\nSuccess: Done in 0.478s\nExecuting erpnext.patches.v13_0.add_default_statement_of_account_email_template in site1.local (_1bd3e0294da19198)\nSuccess: Done in 1.342s\nExecuting erpnext.patches.v13_0.create_default_issue_priorities in site1.local (_1bd3e0294da19198)\nSuccess: Done in 0.1s\nExecuting erpnext.patches.v13_0.update_advance_received_in_sales_order in site1.local (_1bd3e0294da19198)\nSuccess: Done in '
b'0.182s\nExecuting erpnext.patches.v13_0.update_global_search in site1.local (_1bd3e0294da19198)\nSuccess: Done in 4.83s\nExecuting erpnext.patches.v13_0.update_title_field_in_bom in site1.local (_1bd3e0294da19198)\nSuccess: Done in 0.729s\nExecuting erpnext.patches.v13_0.update_batch_no_in_purchase_receipt in site1.local (_1bd3e0294da19198)\nSuccess: Done in 1.861s\nExecuting erpnext.patches.v13_0.set_package_tag_qty_in_package_tag in site1.local (_1bd3e0294da19198)\nSuccess: Done in 0.567s\nExecuting execute:frappe.delete_doc_if_exists("Custom Field", "Sales Order Item-batch_no") in site1.local (_1bd3e0294da19198)\nSuccess: Done in 0.252s\nExecuting erpnext.patches.v13_0.delete_package_tag_property_setter_search_fields in site1.local (_1bd3e0294da19198)\nSuccess: Done in 0.022s\n\rUpdating DocTypes for frappe        : [                                        ]\rUpdating DocTypes for frappe        : [                                        ]'
b'\rUpdating DocTypes for frappe        : [                                        ]\rUpdating DocTypes for frappe        : [                                        ]'
b'\rUpdating DocTypes for frappe        : [                                        ]'
b'\rUpdating DocTypes for frappe        : [=                                       ]'
b'\rUpdating DocTypes for frappe        : [=                                       ]\rUpdating DocTypes for frappe        : [=                                       ]'
b'\rUpdating DocTypes for frappe        : [=                                       ]\rUpdating DocTypes for frappe        : [=                                       ]'
b'\rUpdating DocTypes for frappe        : [=                                       ]\rUpdating DocTypes for frappe        : [==                                      ]\rUpdating DocTypes for frappe        : [==                                      ]'
b'\rUpdating DocTypes for frappe        : [==                                      ]\rUpdating DocTypes for frappe        : [==                                      ]\rUpdating DocTypes for frappe        : [==                                      ]'
b'\rUpdating DocTypes for frappe        : [===                                     ]\rUpdating DocTypes for frappe        : [===                                     ]'
b'\rUpdating DocTypes for frappe        : [===                                     ]\rUpdating DocTypes for frappe        : [===                                     ]\rUpdating DocTypes for frappe        : [===                                     ]'
b'\rUpdating DocTypes for frappe        : [===                                     ]\rUpdating DocTypes for frappe        : [====                                    ]'
b'\rUpdating DocTypes for frappe        : [====                                    ]\rUpdating DocTypes for frappe        : [====                                    ]\rUpdating DocTypes for frappe        : [====                                    ]'
b'\rUpdating DocTypes for frappe        : [====                                    ]\rUpdating DocTypes for frappe        : [=====                                   ]'
b'\rUpdating DocTypes for frappe        : [=====                                   ]\rUpdating DocTypes for frappe        : [=====                                   ]\rUpdating DocTypes for frappe        : [=====                                   ]'
b'\rUpdating DocTypes for frappe        : [=====                                   ]\rUpdating DocTypes for frappe        : [=====                                   ]\rUpdating DocTypes for frappe        : [======                                  ]'
b'\rUpdating DocTypes for frappe        : [======                                  ]'
b'\rUpdating DocTypes for frappe        : [======                                  ]\rUpdating DocTypes for frappe        : [======                                  ]\rUpdating DocTypes for frappe        : [======                                  ]'
b'\rUpdating DocTypes for frappe        : [=======                                 ]\rUpdating DocTypes for frappe        : [=======                                 ]'
b'\rUpdating DocTypes for frappe        : [=======                                 ]\rUpdating DocTypes for frappe        : [=======                                 ]'
b'\rUpdating DocTypes for frappe        : [=======                                 ]\rUpdating DocTypes for frappe        : [=======                                 ]\rUpdating DocTypes for frappe        : [========                                ]'
b'\rUpdating DocTypes for frappe        : [========                                ]'
b'\rUpdating DocTypes for frappe        : [========                                ]\rUpdating DocTypes for frappe        : [========                                ]'
b'\rUpdating DocTypes for frappe        : [========                                ]\rUpdating DocTypes for frappe        : [=========                               ]\rUpdating DocTypes for frappe        : [=========                               ]'
b'\rUpdating DocTypes for frappe        : [=========                               ]\rUpdating DocTypes for frappe        : [=========                               ]\rUpdating DocTypes for frappe        : [=========                               ]'
b'\rUpdating DocTypes for frappe        : [=========                               ]\rUpdating DocTypes for frappe        : [==========                              ]\rUpdating DocTypes for frappe        : [==========                              ]'
b'\rUpdating DocTypes for frappe        : [==========                              ]\rUpdating DocTypes for frappe        : [==========                              ]'
b'\rUpdating DocTypes for frappe        : [==========                              ]\rUpdating DocTypes for frappe        : [===========                             ]'
b'\rUpdating DocTypes for frappe        : [===========                             ]'
b'\rUpdating DocTypes for frappe        : [===========                             ]\rUpdating DocTypes for frappe        : [===========                             ]\rUpdating DocTypes for frappe        : [===========                             ]'
b'\rUpdating DocTypes for frappe        : [===========                             ]\rUpdating DocTypes for frappe        : [============                            ]'
b'\rUpdating DocTypes for frappe        : [============                            ]\rUpdating DocTypes for frappe        : [============                            ]'
b'\rUpdating DocTypes for frappe        : [============                            ]\rUpdating DocTypes for frappe        : [============                            ]'
b'\rUpdating DocTypes for frappe        : [== [...]

2021-02-16 07:52 UTC, hrwX requested changes

2021-02-16 07:52 UTC, hrwX commented on erpnext/controllers/accounts_controller.py
> +def set_purchase_receipt_defaults(parent_doctype, parent_doctype_name, child_docname, trans_item):
```suggestion
def set_purchase_receipt_defaults(parent_doctype, parent_doctype_name, child_docname, transaction_item):
```

2021-02-16 12:02 UTC, hrwX approved these changes

2021-02-16 12:06 UTC, merged